// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.105Z
// Collection: ads/$adId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-managed promotional ads displayed in a rotating carousel on the Trade page for logged-out visitors. Each ad has a title, short description, an uploaded image or video media URL, and an optional click-through link URL. Publicly readable; only the project owner admin can create, update, or delete ads.
 */

export interface AdsRequest {
  title: string;
  description: string;
  mediaUrl: string;
  mediaType: string;
  active: boolean;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  linkUrl?: string;
}

export interface AdsResponse {
  title: string;
  description: string;
  mediaUrl: string;
  mediaType: string;
  active: boolean;
  createdAt: number;
  linkUrl?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Ads operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildAds(adId: string, data: AdsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `ads/${adId}`, document: doc };
}

/**
 * Only the project owner admin wallet (@user.address == @constants.ADMIN_ADDRESS) can create ads. Frontend must provide title, description, mediaUrl (public URL of uploaded media), mediaType ('image' or 'video'), active (Bool, typically true), and createdAt (Unix seconds). Optionally provide linkUrl (a click-through destination URL); when set, the carousel slide becomes clickable and opens this URL. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setAds(adId: string, data: AdsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`ads/${adId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Ads: ${formatError(error)}`);
    return false;
  }
}

export type AdsRequestUpdate = Partial<AdsRequest>;

/**
 * Build a Ads update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateAds(adId: string, data: AdsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `ads/${adId}`, document: doc };
}

/**
 * Only the admin wallet can update ads, including toggling the 'active' flag to show/hide an ad or editing title/description/media/linkUrl. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateAds(adId: string, data: AdsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`ads/${adId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Ads: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone (including logged-out visitors) can read all ads. Returns all fields. Frontend filters by active==true for the public carousel.
   (Get Single Item)
 */
export async function getAds(adId: string): Promise<AdsResponse | null> {
  try {
    const result = await get(`ads/${adId}`);
    return result as AdsResponse | null;
  } catch (error) {
    console.error(`Error getting Ads: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Ads document. (
  Read Operation Details: Anyone (including logged-out visitors) can read all ads. Returns all fields. Frontend filters by active==true for the public carousel.
  )
 */
export function subscribeAds(callback: (data: AdsResponse | null) => void, adId: string): Promise<() => Promise<void>> {
  return subscribe(`ads/${adId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as AdsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Ads at path '${`ads/${adId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Ads items from collection ads
 
  Read Operation Details: Anyone (including logged-out visitors) can read all ads. Returns all fields. Frontend filters by active==true for the public carousel.
  
 */
export async function getManyAds(filter: string = ""): Promise<AdsResponse[]> {
  try {
    const results = await get("ads", { prompt: filter });
    return Array.isArray(results) ? results as AdsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Ads collection at path 'ads': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Ads collection at ads
 
  Read Operation Details: Anyone (including logged-out visitors) can read all ads. Returns all fields. Frontend filters by active==true for the public carousel.
  
 */
export function subscribeManyAds(callback: (data: AdsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("ads", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AdsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Ads collection at path '${"ads"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Ads items from collection ads
 
  Read Operation Details: Anyone (including logged-out visitors) can read all ads. Returns all fields. Frontend filters by active==true for the public carousel.
  
 */
export async function getAllAds(filter: string = ""): Promise<AdsResponse[]> {
  try {
    const results = await get("ads", { prompt: filter });
    return Array.isArray(results) ? results as AdsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Ads collection at path 'ads': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Ads collection at ads
 
  Read Operation Details: Anyone (including logged-out visitors) can read all ads. Returns all fields. Frontend filters by active==true for the public carousel.
  
 */
export function subscribeAllAds(callback: (data: AdsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("ads", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AdsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Ads collection at path '${"ads"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Ads items in collection ads.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countAds(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("ads", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Ads at path 'ads': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Ads items in collection ads.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateAds(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("ads", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Ads at path 'ads': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Only the admin wallet can delete ads.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAds(adId: string): Promise<boolean> {
  try {
    const succeeded = await set(`ads/${adId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Ads: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Ads for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteAds(adId: string): DocumentOperation {
  return { path: `ads/${adId}`, document: null };
}

