// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: analyses/$analysisId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * A user-posted trading analysis (technical analysis writeup) on the Discovery community feed. Publicly readable; only the author can create, edit, or delete their own post.
 */

export interface AnalysesRequest {
  author: AddressType;
  title: string;
  body: string;
  imageUrl?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface AnalysesResponse {
  author: string;
  title: string;
  body: string;
  imageUrl?: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Analyses operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildAnalyses(analysisId: string, data: AnalysesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `analyses/${analysisId}`, document: doc };
}

/**
 * Authenticated users only (@user.address != null). The author field must equal @user.address and is immutable (Address!). Frontend sets createdAt to current server time (Unix seconds). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setAnalyses(analysisId: string, data: AnalysesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`analyses/${analysisId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Analyses: ${formatError(error)}`);
    return false;
  }
}

export type AnalysesRequestUpdate = Partial<AnalysesRequest>;

/**
 * Build a Analyses update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateAnalyses(analysisId: string, data: AnalysesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `analyses/${analysisId}`, document: doc };
}

/**
 * Only the original author (@data.author == @user.address) may edit their own post. The author field cannot be changed (readonly). Title, body, and imageUrl can be updated. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateAnalyses(analysisId: string, data: AnalysesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`analyses/${analysisId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Analyses: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read all analysis posts and all fields. Public community feed.
   (Get Single Item)
 */
export async function getAnalyses(analysisId: string): Promise<AnalysesResponse | null> {
  try {
    const result = await get(`analyses/${analysisId}`);
    return result as AnalysesResponse | null;
  } catch (error) {
    console.error(`Error getting Analyses: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Analyses document. (
  Read Operation Details: Anyone can read all analysis posts and all fields. Public community feed.
  )
 */
export function subscribeAnalyses(callback: (data: AnalysesResponse | null) => void, analysisId: string): Promise<() => Promise<void>> {
  return subscribe(`analyses/${analysisId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as AnalysesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Analyses at path '${`analyses/${analysisId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Analyses items from collection analyses
 
  Read Operation Details: Anyone can read all analysis posts and all fields. Public community feed.
  
 */
export async function getManyAnalyses(filter: string = ""): Promise<AnalysesResponse[]> {
  try {
    const results = await get("analyses", { prompt: filter });
    return Array.isArray(results) ? results as AnalysesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Analyses collection at path 'analyses': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Analyses collection at analyses
 
  Read Operation Details: Anyone can read all analysis posts and all fields. Public community feed.
  
 */
export function subscribeManyAnalyses(callback: (data: AnalysesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("analyses", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AnalysesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Analyses collection at path '${"analyses"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Analyses items from collection analyses
 
  Read Operation Details: Anyone can read all analysis posts and all fields. Public community feed.
  
 */
export async function getAllAnalyses(filter: string = ""): Promise<AnalysesResponse[]> {
  try {
    const results = await get("analyses", { prompt: filter });
    return Array.isArray(results) ? results as AnalysesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Analyses collection at path 'analyses': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Analyses collection at analyses
 
  Read Operation Details: Anyone can read all analysis posts and all fields. Public community feed.
  
 */
export function subscribeAllAnalyses(callback: (data: AnalysesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("analyses", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AnalysesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Analyses collection at path '${"analyses"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Analyses items in collection analyses.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countAnalyses(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("analyses", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Analyses at path 'analyses': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Analyses items in collection analyses.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateAnalyses(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("analyses", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Analyses at path 'analyses': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Only the original author (@data.author == @user.address) may delete their own post.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAnalyses(analysisId: string): Promise<boolean> {
  try {
    const succeeded = await set(`analyses/${analysisId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Analyses: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Analyses for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteAnalyses(analysisId: string): DocumentOperation {
  return { path: `analyses/${analysisId}`, document: null };
}

