// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.105Z
// Collection: apkFiles/$fileId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * APK file storage for the Aeonian Android dApp. Admin uploads release APKs here; files are publicly readable so anyone can download via the returned public URL.
 */

/**
 * Handles ApkFiles files (Get Single File based on its ID, null if not found)
 */
export async function getApkFiles(fileId: string): Promise<FileItem | null> {
  try {
    const rawResult = await getFiles(`apkFiles/${fileId}`);
    if (!rawResult || !Array.isArray(rawResult) || rawResult.length === 0) return null;
    return rawResult[0] as FileItem;
  } catch (error) {
    console.error(`Error getting file ApkFiles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Handles ApkFiles files (Upload/Replace a File and persist it keyed by its ID) To get the file URL use the getApkFiles function right after this one.
 * @returns A boolean indicating whether the upload succeeded (true) or failed (false). Always check this value to confirm the upload worked.
 */
export async function uploadApkFiles(fileId: string, file: File): Promise<boolean> {
  try {
    const pathUsed = `apkFiles/${fileId}`;
    const result = await setFile(pathUsed, file);
    return !!result;
  } catch (error) {
    console.error(`Error uploading file ApkFiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Handles ApkFiles files (Delete File based on its ID)
 * @returns A boolean indicating whether the delete succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteApkFiles(fileId: string): Promise<boolean> {
  try {
    await setFile(`apkFiles/${fileId}`, null);
    return true;
  } catch (error) {
    console.error(`Error deleting file ApkFiles: ${formatError(error)}`);
    return false;
  }
}

