// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: apkRelease/$releaseId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Current Aeonian Android dApp release metadata. Single shared document keyed by the constant id 'current' (apkRelease/current). Publicly readable so the /download page can show the latest release; admin-only create/update.
 */

export interface ApkReleaseRequest {
  fileUrl: string;
  version: string;
  fileName: string;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ApkReleaseResponse {
  fileUrl: string;
  version: string;
  fileName: string;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a ApkRelease operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildApkRelease(releaseId: string, data: ApkReleaseRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `apkRelease/${releaseId}`, document: doc };
}

/**
 * Admin only (@user.address == @constants.ADMIN_ADDRESS). Document id must equal @constants.APK_RELEASE_ID ('current'), enforcing a single shared release doc at apkRelease/current. Admin creates it on first upload via the UI. updatedAt is a Unix-seconds timestamp. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setApkRelease(releaseId: string, data: ApkReleaseRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`apkRelease/${releaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting ApkRelease: ${formatError(error)}`);
    return false;
  }
}

export type ApkReleaseRequestUpdate = Partial<ApkReleaseRequest>;

/**
 * Build a ApkRelease update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateApkRelease(releaseId: string, data: ApkReleaseRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `apkRelease/${releaseId}`, document: doc };
}

/**
 * Admin only (@user.address == @constants.ADMIN_ADDRESS). Document id must equal @constants.APK_RELEASE_ID ('current'). Admin overwrites fileUrl, version, fileName, and updatedAt when publishing a new release. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateApkRelease(releaseId: string, data: ApkReleaseRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`apkRelease/${releaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating ApkRelease: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone (no auth required). Public read so the /download page can display the current release metadata (fileUrl, version, fileName, updatedAt).
   (Get Single Item)
 */
export async function getApkRelease(releaseId: string): Promise<ApkReleaseResponse | null> {
  try {
    const result = await get(`apkRelease/${releaseId}`);
    return result as ApkReleaseResponse | null;
  } catch (error) {
    console.error(`Error getting ApkRelease: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single ApkRelease document. (
  Read Operation Details: Anyone (no auth required). Public read so the /download page can display the current release metadata (fileUrl, version, fileName, updatedAt).
  )
 */
export function subscribeApkRelease(callback: (data: ApkReleaseResponse | null) => void, releaseId: string): Promise<() => Promise<void>> {
  return subscribe(`apkRelease/${releaseId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ApkReleaseResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to ApkRelease at path '${`apkRelease/${releaseId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many ApkRelease items from collection apkRelease
 
  Read Operation Details: Anyone (no auth required). Public read so the /download page can display the current release metadata (fileUrl, version, fileName, updatedAt).
  
 */
export async function getManyApkRelease(filter: string = ""): Promise<ApkReleaseResponse[]> {
  try {
    const results = await get("apkRelease", { prompt: filter });
    return Array.isArray(results) ? results as ApkReleaseResponse[] : [];
  } catch (error) {
    console.error(`Error getting ApkRelease collection at path 'apkRelease': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ApkRelease collection at apkRelease
 
  Read Operation Details: Anyone (no auth required). Public read so the /download page can display the current release metadata (fileUrl, version, fileName, updatedAt).
  
 */
export function subscribeManyApkRelease(callback: (data: ApkReleaseResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("apkRelease", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ApkReleaseResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ApkRelease collection at path '${"apkRelease"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all ApkRelease items from collection apkRelease
 
  Read Operation Details: Anyone (no auth required). Public read so the /download page can display the current release metadata (fileUrl, version, fileName, updatedAt).
  
 */
export async function getAllApkRelease(filter: string = ""): Promise<ApkReleaseResponse[]> {
  try {
    const results = await get("apkRelease", { prompt: filter });
    return Array.isArray(results) ? results as ApkReleaseResponse[] : [];
  } catch (error) {
    console.error(`Error getting ApkRelease collection at path 'apkRelease': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ApkRelease collection at apkRelease
 
  Read Operation Details: Anyone (no auth required). Public read so the /download page can display the current release metadata (fileUrl, version, fileName, updatedAt).
  
 */
export function subscribeAllApkRelease(callback: (data: ApkReleaseResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("apkRelease", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ApkReleaseResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ApkRelease collection at path '${"apkRelease"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count ApkRelease items in collection apkRelease.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countApkRelease(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("apkRelease", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting ApkRelease at path 'apkRelease': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on ApkRelease items in collection apkRelease.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateApkRelease(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("apkRelease", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating ApkRelease at path 'apkRelease': ${formatError(error)}`);
    return { value: 0 };
  }
}

