// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.104Z
// Collection: appSettings/$settingId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Stores app-wide settings like logo URL. Admin-writable, publicly readable.
 */

export interface AppSettingsRequest {
  value: string;
  label: string;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface AppSettingsResponse {
  value: string;
  label: string;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a AppSettings operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildAppSettings(settingId: string, data: AppSettingsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `appSettings/${settingId}`, document: doc };
}

/**
 * Admin only. Creates a new app setting entry. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setAppSettings(settingId: string, data: AppSettingsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`appSettings/${settingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting AppSettings: ${formatError(error)}`);
    return false;
  }
}

export type AppSettingsRequestUpdate = Partial<AppSettingsRequest>;

/**
 * Build a AppSettings update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateAppSettings(settingId: string, data: AppSettingsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `appSettings/${settingId}`, document: doc };
}

/**
 * Admin only. Modifies an existing app setting value, label, or timestamp. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateAppSettings(settingId: string, data: AppSettingsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`appSettings/${settingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating AppSettings: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read app settings.
   (Get Single Item)
 */
export async function getAppSettings(settingId: string): Promise<AppSettingsResponse | null> {
  try {
    const result = await get(`appSettings/${settingId}`);
    return result as AppSettingsResponse | null;
  } catch (error) {
    console.error(`Error getting AppSettings: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single AppSettings document. (
  Read Operation Details: Anyone can read app settings.
  )
 */
export function subscribeAppSettings(callback: (data: AppSettingsResponse | null) => void, settingId: string): Promise<() => Promise<void>> {
  return subscribe(`appSettings/${settingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as AppSettingsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to AppSettings at path '${`appSettings/${settingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many AppSettings items from collection appSettings
 
  Read Operation Details: Anyone can read app settings.
  
 */
export async function getManyAppSettings(filter: string = ""): Promise<AppSettingsResponse[]> {
  try {
    const results = await get("appSettings", { prompt: filter });
    return Array.isArray(results) ? results as AppSettingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting AppSettings collection at path 'appSettings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in AppSettings collection at appSettings
 
  Read Operation Details: Anyone can read app settings.
  
 */
export function subscribeManyAppSettings(callback: (data: AppSettingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("appSettings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AppSettingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to AppSettings collection at path '${"appSettings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all AppSettings items from collection appSettings
 
  Read Operation Details: Anyone can read app settings.
  
 */
export async function getAllAppSettings(filter: string = ""): Promise<AppSettingsResponse[]> {
  try {
    const results = await get("appSettings", { prompt: filter });
    return Array.isArray(results) ? results as AppSettingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting AppSettings collection at path 'appSettings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in AppSettings collection at appSettings
 
  Read Operation Details: Anyone can read app settings.
  
 */
export function subscribeAllAppSettings(callback: (data: AppSettingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("appSettings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AppSettingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to AppSettings collection at path '${"appSettings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count AppSettings items in collection appSettings.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countAppSettings(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("appSettings", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting AppSettings at path 'appSettings': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on AppSettings items in collection appSettings.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateAppSettings(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("appSettings", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating AppSettings at path 'appSettings': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only. Removes an app setting entry.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAppSettings(settingId: string): Promise<boolean> {
  try {
    const succeeded = await set(`appSettings/${settingId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting AppSettings: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for AppSettings for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteAppSettings(settingId: string): DocumentOperation {
  return { path: `appSettings/${settingId}`, document: null };
}

