// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: articles/$articleId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-posted trading news/articles displayed in a public feed on the Discovery landing page. Publicly readable by anyone (including unauthenticated visitors); only the project admin can create, update, or delete entries.
 */

export interface ArticlesRequest {
  title: string;
  link: string;
  imageUrl?: string;
  body?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ArticlesResponse {
  title: string;
  link: string;
  imageUrl?: string;
  body?: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Articles operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildArticles(articleId: string, data: ArticlesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `articles/${articleId}`, document: doc };
}

/**
 * Admin only. Caller's @user.address must equal @constants.ADMIN_ADDRESS (project owner wallet). Frontend must provide title, link, and createdAt (Unix seconds); imageUrl and body are optional. No hooks or token operations. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setArticles(articleId: string, data: ArticlesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`articles/${articleId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Articles: ${formatError(error)}`);
    return false;
  }
}

export type ArticlesRequestUpdate = Partial<ArticlesRequest>;

/**
 * Build a Articles update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateArticles(articleId: string, data: ArticlesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `articles/${articleId}`, document: doc };
}

/**
 * Admin only. Caller's @user.address must equal @constants.ADMIN_ADDRESS. Any field may be edited. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateArticles(articleId: string, data: ArticlesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`articles/${articleId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Articles: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public. Anyone, including unauthenticated visitors, can read all article fields. Used for the Discovery landing page feed.
   (Get Single Item)
 */
export async function getArticles(articleId: string): Promise<ArticlesResponse | null> {
  try {
    const result = await get(`articles/${articleId}`);
    return result as ArticlesResponse | null;
  } catch (error) {
    console.error(`Error getting Articles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Articles document. (
  Read Operation Details: Public. Anyone, including unauthenticated visitors, can read all article fields. Used for the Discovery landing page feed.
  )
 */
export function subscribeArticles(callback: (data: ArticlesResponse | null) => void, articleId: string): Promise<() => Promise<void>> {
  return subscribe(`articles/${articleId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ArticlesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Articles at path '${`articles/${articleId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Articles items from collection articles
 
  Read Operation Details: Public. Anyone, including unauthenticated visitors, can read all article fields. Used for the Discovery landing page feed.
  
 */
export async function getManyArticles(filter: string = ""): Promise<ArticlesResponse[]> {
  try {
    const results = await get("articles", { prompt: filter });
    return Array.isArray(results) ? results as ArticlesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Articles collection at path 'articles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Articles collection at articles
 
  Read Operation Details: Public. Anyone, including unauthenticated visitors, can read all article fields. Used for the Discovery landing page feed.
  
 */
export function subscribeManyArticles(callback: (data: ArticlesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("articles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ArticlesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Articles collection at path '${"articles"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Articles items from collection articles
 
  Read Operation Details: Public. Anyone, including unauthenticated visitors, can read all article fields. Used for the Discovery landing page feed.
  
 */
export async function getAllArticles(filter: string = ""): Promise<ArticlesResponse[]> {
  try {
    const results = await get("articles", { prompt: filter });
    return Array.isArray(results) ? results as ArticlesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Articles collection at path 'articles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Articles collection at articles
 
  Read Operation Details: Public. Anyone, including unauthenticated visitors, can read all article fields. Used for the Discovery landing page feed.
  
 */
export function subscribeAllArticles(callback: (data: ArticlesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("articles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ArticlesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Articles collection at path '${"articles"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Articles items in collection articles.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countArticles(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("articles", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Articles at path 'articles': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Articles items in collection articles.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateArticles(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("articles", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Articles at path 'articles': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only. Caller's @user.address must equal @constants.ADMIN_ADDRESS. Removes the article from the feed.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteArticles(articleId: string): Promise<boolean> {
  try {
    const succeeded = await set(`articles/${articleId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Articles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Articles for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteArticles(articleId: string): DocumentOperation {
  return { path: `articles/${articleId}`, document: null };
}

