// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.203Z
// Collection: battles/$battleId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Trading battle metadata + state. Head-to-head Phoenix perps PnL competition. Offchain state collection; token escrow happens in battleParticipants (onchain). Backend (PROJECT_VAULT_ADDRESS) marks active/ended and sets winner after evaluating Phoenix PnL via @PhoenixPerpsPlugin.getUnrealizedPnl.
 */

export interface BattlesRequest {
  challenger: AddressType;
  opponent?: AddressType;
  betAmountMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  startTime: number | TimeOperation | IncrementOperation | TokenAmount;
  endTime: number | TimeOperation | IncrementOperation | TokenAmount;
  durationSeconds: number | TimeOperation | IncrementOperation | TokenAmount;
  status: string;
  challengerXHandle?: string;
  opponentXHandle?: string;
  winner?: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  type?: string;
  minParticipants?: number | TimeOperation | IncrementOperation | TokenAmount;
  maxParticipants?: number | TimeOperation | IncrementOperation | TokenAmount;
  title?: string;
}

export interface BattlesResponse {
  challenger: string;
  opponent?: string;
  betAmountMicro: number;
  startTime: number;
  endTime: number;
  durationSeconds: number;
  status: string;
  challengerXHandle?: string;
  opponentXHandle?: string;
  winner?: string;
  createdAt: number;
  type?: string;
  minParticipants?: number;
  maxParticipants?: number;
  title?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Battles operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBattles(battleId: string, data: BattlesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `battles/${battleId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal @newData.challenger (challenger creates the battle for themselves). betAmountMicro must be > 0 (micro-USDC, 6 decimals). Status must start as 'pending'. opponent is null for open challenges (anyone can accept) or set to a specific wallet for direct challenges. startTime/endTime are set later by the backend when the battle becomes active. No token transfer occurs here — actual USDC escrow happens when each player joins via battleParticipants. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBattles(battleId: string, data: BattlesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`battles/${battleId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Battles: ${formatError(error)}`);
    return false;
  }
}

export type BattlesRequestUpdate = Partial<BattlesRequest>;

/**
 * Build a Battles update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateBattles(battleId: string, data: BattlesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `battles/${battleId}`, document: doc };
}

/**
 * Two paths: (1) PROJECT_VAULT_ADDRESS (backend) can update any field — used to mark 'pending'→'active' once both participants joined (sets startTime/endTime), 'active'→'ended' after endTime, set 'winner' after evaluating Phoenix PnL, and mark 'ended'→'claimed' after winner claims. (2) The original challenger can update a pending battle to status='cancelled' only if no opponent has joined yet (used to cancel an open challenge they posted). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateBattles(battleId: string, data: BattlesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`battles/${battleId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Battles: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public — anyone can read all battle records for browsing open challenges, watching battles, etc.
   (Get Single Item)
 */
export async function getBattles(battleId: string): Promise<BattlesResponse | null> {
  try {
    const result = await get(`battles/${battleId}`);
    return result as BattlesResponse | null;
  } catch (error) {
    console.error(`Error getting Battles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Battles document. (
  Read Operation Details: Public — anyone can read all battle records for browsing open challenges, watching battles, etc.
  )
 */
export function subscribeBattles(callback: (data: BattlesResponse | null) => void, battleId: string): Promise<() => Promise<void>> {
  return subscribe(`battles/${battleId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BattlesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Battles at path '${`battles/${battleId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Battles items from collection battles
 
  Read Operation Details: Public — anyone can read all battle records for browsing open challenges, watching battles, etc.
  
 */
export async function getManyBattles(filter: string = ""): Promise<BattlesResponse[]> {
  try {
    const results = await get("battles", { prompt: filter });
    return Array.isArray(results) ? results as BattlesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Battles collection at path 'battles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Battles collection at battles
 
  Read Operation Details: Public — anyone can read all battle records for browsing open challenges, watching battles, etc.
  
 */
export function subscribeManyBattles(callback: (data: BattlesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattlesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Battles collection at path '${"battles"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Battles items from collection battles
 
  Read Operation Details: Public — anyone can read all battle records for browsing open challenges, watching battles, etc.
  
 */
export async function getAllBattles(filter: string = ""): Promise<BattlesResponse[]> {
  try {
    const results = await get("battles", { prompt: filter });
    return Array.isArray(results) ? results as BattlesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Battles collection at path 'battles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Battles collection at battles
 
  Read Operation Details: Public — anyone can read all battle records for browsing open challenges, watching battles, etc.
  
 */
export function subscribeAllBattles(callback: (data: BattlesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattlesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Battles collection at path '${"battles"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Battles items in collection battles.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBattles(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("battles", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Battles at path 'battles': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Battles items in collection battles.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBattles(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("battles", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Battles at path 'battles': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only. The admin wallet (@constants.ADMIN_ADDRESS, the project owner) can delete/remove any battle record regardless of status (pending, active, ended, cancelled, or claimed — including inactive ones). Used for cleanup/moderation of battle history.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteBattles(battleId: string): Promise<boolean> {
  try {
    const succeeded = await set(`battles/${battleId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Battles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Battles for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteBattles(battleId: string): DocumentOperation {
  return { path: `battles/${battleId}`, document: null };
}

