// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: battleMessages/$messageId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Trash talk chat messages posted by authenticated wallets during trading battles. Public and immutable.
 */

export interface BattleMessagesRequest {
  battleId: string;
  senderAddress: AddressType;
  text: string;
  emoji?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface BattleMessagesResponse {
  battleId: string;
  senderAddress: string;
  text: string;
  emoji?: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a BattleMessages operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBattleMessages(messageId: string, data?: BattleMessagesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `battleMessages/${messageId}`, document: doc };
}

/**
 * Authenticated users only. Caller must have a connected wallet and must post as themselves (@newData.senderAddress == @user.address). Messages are tied to a battle via battleId. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBattleMessages(messageId: string, data?: BattleMessagesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`battleMessages/${messageId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting BattleMessages: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read battle messages. No authentication required. Useful for spectators and participants viewing trash talk tied to a specific battle.
   (Get Single Item)
 */
export async function getBattleMessages(messageId: string): Promise<BattleMessagesResponse | null> {
  try {
    const result = await get(`battleMessages/${messageId}`);
    return result as BattleMessagesResponse | null;
  } catch (error) {
    console.error(`Error getting BattleMessages: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single BattleMessages document. (
  Read Operation Details: Anyone can read battle messages. No authentication required. Useful for spectators and participants viewing trash talk tied to a specific battle.
  )
 */
export function subscribeBattleMessages(callback: (data: BattleMessagesResponse | null) => void, messageId: string): Promise<() => Promise<void>> {
  return subscribe(`battleMessages/${messageId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BattleMessagesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to BattleMessages at path '${`battleMessages/${messageId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many BattleMessages items from collection battleMessages
 
  Read Operation Details: Anyone can read battle messages. No authentication required. Useful for spectators and participants viewing trash talk tied to a specific battle.
  
 */
export async function getManyBattleMessages(filter: string = ""): Promise<BattleMessagesResponse[]> {
  try {
    const results = await get("battleMessages", { prompt: filter });
    return Array.isArray(results) ? results as BattleMessagesResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleMessages collection at path 'battleMessages': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleMessages collection at battleMessages
 
  Read Operation Details: Anyone can read battle messages. No authentication required. Useful for spectators and participants viewing trash talk tied to a specific battle.
  
 */
export function subscribeManyBattleMessages(callback: (data: BattleMessagesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleMessages", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleMessagesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleMessages collection at path '${"battleMessages"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all BattleMessages items from collection battleMessages
 
  Read Operation Details: Anyone can read battle messages. No authentication required. Useful for spectators and participants viewing trash talk tied to a specific battle.
  
 */
export async function getAllBattleMessages(filter: string = ""): Promise<BattleMessagesResponse[]> {
  try {
    const results = await get("battleMessages", { prompt: filter });
    return Array.isArray(results) ? results as BattleMessagesResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleMessages collection at path 'battleMessages': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleMessages collection at battleMessages
 
  Read Operation Details: Anyone can read battle messages. No authentication required. Useful for spectators and participants viewing trash talk tied to a specific battle.
  
 */
export function subscribeAllBattleMessages(callback: (data: BattleMessagesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleMessages", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleMessagesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleMessages collection at path '${"battleMessages"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count BattleMessages items in collection battleMessages.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBattleMessages(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("battleMessages", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting BattleMessages at path 'battleMessages': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on BattleMessages items in collection battleMessages.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBattleMessages(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("battleMessages", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating BattleMessages at path 'battleMessages': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin-only (cascade cleanup). Only @constants.ADMIN_ADDRESS can delete. When an admin deletes a battle, related battleMessages are removed alongside it. Offchain chat records, safe to delete permanently.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteBattleMessages(messageId: string): Promise<boolean> {
  try {
    const succeeded = await set(`battleMessages/${messageId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting BattleMessages: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for BattleMessages for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteBattleMessages(messageId: string): DocumentOperation {
  return { path: `battleMessages/${messageId}`, document: null };
}

