// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: defaultAvatars/$avatarId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-managed pool of default avatar image URLs assigned to users who haven't connected their X profile. Image bytes live in the existing appFiles storage collection; this collection just holds the public URL pointing at them.
 */

export interface DefaultAvatarsRequest {
  url: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface DefaultAvatarsResponse {
  url: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a DefaultAvatars operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDefaultAvatars(avatarId: string, data: DefaultAvatarsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `defaultAvatars/${avatarId}`, document: doc };
}

/**
 * Admin only — caller must equal @constants.ADMIN_ADDRESS. The admin wallet signs the write directly from the frontend (same pattern as logo upload and promotion moderation). No backend/PROJECT_VAULT writes involved. Frontend should pass url (public image URL) and createdAt (Unix seconds). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setDefaultAvatars(avatarId: string, data: DefaultAvatarsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`defaultAvatars/${avatarId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting DefaultAvatars: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read (public, no auth). Avatars surface on public leaderboards and profiles. Returns url and createdAt fields.
   (Get Single Item)
 */
export async function getDefaultAvatars(avatarId: string): Promise<DefaultAvatarsResponse | null> {
  try {
    const result = await get(`defaultAvatars/${avatarId}`);
    return result as DefaultAvatarsResponse | null;
  } catch (error) {
    console.error(`Error getting DefaultAvatars: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single DefaultAvatars document. (
  Read Operation Details: Anyone can read (public, no auth). Avatars surface on public leaderboards and profiles. Returns url and createdAt fields.
  )
 */
export function subscribeDefaultAvatars(callback: (data: DefaultAvatarsResponse | null) => void, avatarId: string): Promise<() => Promise<void>> {
  return subscribe(`defaultAvatars/${avatarId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as DefaultAvatarsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to DefaultAvatars at path '${`defaultAvatars/${avatarId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many DefaultAvatars items from collection defaultAvatars
 
  Read Operation Details: Anyone can read (public, no auth). Avatars surface on public leaderboards and profiles. Returns url and createdAt fields.
  
 */
export async function getManyDefaultAvatars(filter: string = ""): Promise<DefaultAvatarsResponse[]> {
  try {
    const results = await get("defaultAvatars", { prompt: filter });
    return Array.isArray(results) ? results as DefaultAvatarsResponse[] : [];
  } catch (error) {
    console.error(`Error getting DefaultAvatars collection at path 'defaultAvatars': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in DefaultAvatars collection at defaultAvatars
 
  Read Operation Details: Anyone can read (public, no auth). Avatars surface on public leaderboards and profiles. Returns url and createdAt fields.
  
 */
export function subscribeManyDefaultAvatars(callback: (data: DefaultAvatarsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("defaultAvatars", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DefaultAvatarsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to DefaultAvatars collection at path '${"defaultAvatars"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all DefaultAvatars items from collection defaultAvatars
 
  Read Operation Details: Anyone can read (public, no auth). Avatars surface on public leaderboards and profiles. Returns url and createdAt fields.
  
 */
export async function getAllDefaultAvatars(filter: string = ""): Promise<DefaultAvatarsResponse[]> {
  try {
    const results = await get("defaultAvatars", { prompt: filter });
    return Array.isArray(results) ? results as DefaultAvatarsResponse[] : [];
  } catch (error) {
    console.error(`Error getting DefaultAvatars collection at path 'defaultAvatars': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in DefaultAvatars collection at defaultAvatars
 
  Read Operation Details: Anyone can read (public, no auth). Avatars surface on public leaderboards and profiles. Returns url and createdAt fields.
  
 */
export function subscribeAllDefaultAvatars(callback: (data: DefaultAvatarsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("defaultAvatars", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DefaultAvatarsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to DefaultAvatars collection at path '${"defaultAvatars"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count DefaultAvatars items in collection defaultAvatars.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countDefaultAvatars(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("defaultAvatars", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting DefaultAvatars at path 'defaultAvatars': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on DefaultAvatars items in collection defaultAvatars.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateDefaultAvatars(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("defaultAvatars", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating DefaultAvatars at path 'defaultAvatars': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only — caller must equal @constants.ADMIN_ADDRESS. Removes an avatar from the default pool.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteDefaultAvatars(avatarId: string): Promise<boolean> {
  try {
    const succeeded = await set(`defaultAvatars/${avatarId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting DefaultAvatars: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for DefaultAvatars for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteDefaultAvatars(avatarId: string): DocumentOperation {
  return { path: `defaultAvatars/${avatarId}`, document: null };
}

