// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: follows/$followId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Directed follow relationship. One user (follower) follows a trader (followed). Created and deleted directly by users from the frontend (user-signed). $followId is a deterministic composite '{followerAddress}:{followedAddress}' so a user can follow a given trader at most once. Follower/following counts are computed by the UI via where-clause queries, not denormalized.
 */

export interface FollowsRequest {
  follower: AddressType;
  followed: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FollowsResponse {
  follower: string;
  followed: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Follows operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFollows(followId: string, data?: FollowsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `follows/${followId}`, document: doc };
}

/**
 * Authenticated users only, and only for themselves: caller wallet (@user.address) must equal @newData.follower. Frontend generates $followId as the deterministic composite '{followerAddress}:{followedAddress}' (colon separator) to enforce at-most-one follow per (follower, followed) pair. No hooks. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFollows(followId: string, data?: FollowsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`follows/${followId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Follows: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read (public). Needed so the UI can compute follower counts via where-clause queries on 'followed' and 'who am I following' via queries on 'follower'. Shows all fields.
   (Get Single Item)
 */
export async function getFollows(followId: string): Promise<FollowsResponse | null> {
  try {
    const result = await get(`follows/${followId}`);
    return result as FollowsResponse | null;
  } catch (error) {
    console.error(`Error getting Follows: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Follows document. (
  Read Operation Details: Anyone can read (public). Needed so the UI can compute follower counts via where-clause queries on 'followed' and 'who am I following' via queries on 'follower'. Shows all fields.
  )
 */
export function subscribeFollows(callback: (data: FollowsResponse | null) => void, followId: string): Promise<() => Promise<void>> {
  return subscribe(`follows/${followId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FollowsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Follows at path '${`follows/${followId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Follows items from collection follows
 
  Read Operation Details: Anyone can read (public). Needed so the UI can compute follower counts via where-clause queries on 'followed' and 'who am I following' via queries on 'follower'. Shows all fields.
  
 */
export async function getManyFollows(filter: string = ""): Promise<FollowsResponse[]> {
  try {
    const results = await get("follows", { prompt: filter });
    return Array.isArray(results) ? results as FollowsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Follows collection at path 'follows': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Follows collection at follows
 
  Read Operation Details: Anyone can read (public). Needed so the UI can compute follower counts via where-clause queries on 'followed' and 'who am I following' via queries on 'follower'. Shows all fields.
  
 */
export function subscribeManyFollows(callback: (data: FollowsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("follows", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FollowsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Follows collection at path '${"follows"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Follows items from collection follows
 
  Read Operation Details: Anyone can read (public). Needed so the UI can compute follower counts via where-clause queries on 'followed' and 'who am I following' via queries on 'follower'. Shows all fields.
  
 */
export async function getAllFollows(filter: string = ""): Promise<FollowsResponse[]> {
  try {
    const results = await get("follows", { prompt: filter });
    return Array.isArray(results) ? results as FollowsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Follows collection at path 'follows': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Follows collection at follows
 
  Read Operation Details: Anyone can read (public). Needed so the UI can compute follower counts via where-clause queries on 'followed' and 'who am I following' via queries on 'follower'. Shows all fields.
  
 */
export function subscribeAllFollows(callback: (data: FollowsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("follows", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FollowsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Follows collection at path '${"follows"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Follows items in collection follows.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countFollows(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("follows", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Follows at path 'follows': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Follows items in collection follows.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateFollows(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("follows", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Follows at path 'follows': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: The follower themselves (@user.address == @data.follower) or the backend vault (@constants.PROJECT_VAULT_ADDRESS) for cleanup. Unfollow = delete.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteFollows(followId: string): Promise<boolean> {
  try {
    const succeeded = await set(`follows/${followId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Follows: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Follows for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteFollows(followId: string): DocumentOperation {
  return { path: `follows/${followId}`, document: null };
}

