// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.105Z
// Collection: liquidations/$liquidationId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * A public-read record of a detected liquidation event, written ONLY by the backend (signing as PROJECT_VAULT_ADDRESS) from the liquidation-detection Heartbeat task. The frontend trades feed reads these to render a red 'Liquidated' marker. This is intentionally SEPARATE from phoenixTradeRecord because phoenixTradeRecord's offchain create hook awards trading points and a liquidation must NOT award points — so this collection has NO hooks. $liquidationId is a backend-generated unique id.
 */

export interface LiquidationsRequest {
  trader: AddressType;
  market?: AddressType;
  symbol: string;
  side: string;
  sizeBaseLots?: number | TimeOperation | IncrementOperation | TokenAmount;
  collateralCentsBefore?: number | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface LiquidationsResponse {
  trader: string;
  market?: string;
  symbol: string;
  side: string;
  sizeBaseLots?: number;
  collateralCentsBefore?: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Liquidations operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildLiquidations(liquidationId: string, data?: LiquidationsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `liquidations/${liquidationId}`, document: doc };
}

/**
 * Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task records detected liquidations. trader is the liquidated trader's wallet (readonly), symbol is the market symbol (e.g. 'SOL'), side is 'long' or 'short', createdAt is Unix seconds when the liquidation was detected. market (perp market address), sizeBaseLots (last-known position size), and collateralCentsBefore (collateral in US cents on the previous tick, can be negative) are optional. No hooks run — deliberately does NOT award trading points, unlike phoenixTradeRecord. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setLiquidations(liquidationId: string, data?: LiquidationsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`liquidations/${liquidationId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Liquidations: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (true). Anyone can read liquidation records so the frontend trades feed can render a red 'Liquidated' marker.
   (Get Single Item)
 */
export async function getLiquidations(liquidationId: string): Promise<LiquidationsResponse | null> {
  try {
    const result = await get(`liquidations/${liquidationId}`);
    return result as LiquidationsResponse | null;
  } catch (error) {
    console.error(`Error getting Liquidations: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Liquidations document. (
  Read Operation Details: Public (true). Anyone can read liquidation records so the frontend trades feed can render a red 'Liquidated' marker.
  )
 */
export function subscribeLiquidations(callback: (data: LiquidationsResponse | null) => void, liquidationId: string): Promise<() => Promise<void>> {
  return subscribe(`liquidations/${liquidationId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as LiquidationsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Liquidations at path '${`liquidations/${liquidationId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Liquidations items from collection liquidations
 
  Read Operation Details: Public (true). Anyone can read liquidation records so the frontend trades feed can render a red 'Liquidated' marker.
  
 */
export async function getManyLiquidations(filter: string = ""): Promise<LiquidationsResponse[]> {
  try {
    const results = await get("liquidations", { prompt: filter });
    return Array.isArray(results) ? results as LiquidationsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Liquidations collection at path 'liquidations': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Liquidations collection at liquidations
 
  Read Operation Details: Public (true). Anyone can read liquidation records so the frontend trades feed can render a red 'Liquidated' marker.
  
 */
export function subscribeManyLiquidations(callback: (data: LiquidationsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("liquidations", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LiquidationsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Liquidations collection at path '${"liquidations"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Liquidations items from collection liquidations
 
  Read Operation Details: Public (true). Anyone can read liquidation records so the frontend trades feed can render a red 'Liquidated' marker.
  
 */
export async function getAllLiquidations(filter: string = ""): Promise<LiquidationsResponse[]> {
  try {
    const results = await get("liquidations", { prompt: filter });
    return Array.isArray(results) ? results as LiquidationsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Liquidations collection at path 'liquidations': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Liquidations collection at liquidations
 
  Read Operation Details: Public (true). Anyone can read liquidation records so the frontend trades feed can render a red 'Liquidated' marker.
  
 */
export function subscribeAllLiquidations(callback: (data: LiquidationsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("liquidations", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LiquidationsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Liquidations collection at path '${"liquidations"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Liquidations items in collection liquidations.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countLiquidations(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("liquidations", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Liquidations at path 'liquidations': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Liquidations items in collection liquidations.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateLiquidations(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("liquidations", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Liquidations at path 'liquidations': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). Allows the backend to remove erroneous records.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteLiquidations(liquidationId: string): Promise<boolean> {
  try {
    const succeeded = await set(`liquidations/${liquidationId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Liquidations: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Liquidations for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteLiquidations(liquidationId: string): DocumentOperation {
  return { path: `liquidations/${liquidationId}`, document: null };
}

