// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: monthlyRewardTarget/$monthKey
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-set fundraising target for a calendar month's prize pot, used by the public prize pot card to render a deposited-vs-target progress bar. Document id is the month key string (e.g. '2026-06'); one doc per month. Target amount is stored in the token's on-chain base units to match monthlyRewardDeposit.amount.
 */

export interface MonthlyRewardTargetRequest {
  monthKey: string;
  targetMint: AddressType;
  targetAmount: number | TimeOperation | IncrementOperation | TokenAmount;
  updatedBy: AddressType;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  currentAmount: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MonthlyRewardTargetResponse {
  monthKey: string;
  targetMint: string;
  targetAmount: number;
  updatedBy: string;
  updatedAt: number;
  currentAmount: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a MonthlyRewardTarget operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMonthlyRewardTarget(monthKey: string, data: MonthlyRewardTargetRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `monthlyRewardTarget/${monthKey}`, document: doc };
}

/**
 * Admin only — @user.address must equal @constants.ADMIN_ADDRESS. Written directly from the admin frontend (not the backend). Document id must be the month key string (e.g. '2026-06'). targetAmount and currentAmount are in the token's on-chain base units. currentAmount is the real current prize-pot amount the admin sets directly on top-up. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMonthlyRewardTarget(monthKey: string, data: MonthlyRewardTargetRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`monthlyRewardTarget/${monthKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting MonthlyRewardTarget: ${formatError(error)}`);
    return false;
  }
}

export type MonthlyRewardTargetRequestUpdate = Partial<MonthlyRewardTargetRequest>;

/**
 * Build a MonthlyRewardTarget update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateMonthlyRewardTarget(monthKey: string, data: MonthlyRewardTargetRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `monthlyRewardTarget/${monthKey}`, document: doc };
}

/**
 * Admin only — @user.address must equal @constants.ADMIN_ADDRESS. Admin can revise the target, the real currentAmount on top-up, the target token mint, or metadata for an existing month. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateMonthlyRewardTarget(monthKey: string, data: MonthlyRewardTargetRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`monthlyRewardTarget/${monthKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating MonthlyRewardTarget: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read (public). The public-facing prize pot card reads currentAmount (the real displayed pot number) and targetAmount (aspirational target for the projected-split feature). All fields are returned.
   (Get Single Item)
 */
export async function getMonthlyRewardTarget(monthKey: string): Promise<MonthlyRewardTargetResponse | null> {
  try {
    const result = await get(`monthlyRewardTarget/${monthKey}`);
    return result as MonthlyRewardTargetResponse | null;
  } catch (error) {
    console.error(`Error getting MonthlyRewardTarget: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single MonthlyRewardTarget document. (
  Read Operation Details: Anyone can read (public). The public-facing prize pot card reads currentAmount (the real displayed pot number) and targetAmount (aspirational target for the projected-split feature). All fields are returned.
  )
 */
export function subscribeMonthlyRewardTarget(callback: (data: MonthlyRewardTargetResponse | null) => void, monthKey: string): Promise<() => Promise<void>> {
  return subscribe(`monthlyRewardTarget/${monthKey}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MonthlyRewardTargetResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to MonthlyRewardTarget at path '${`monthlyRewardTarget/${monthKey}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many MonthlyRewardTarget items from collection monthlyRewardTarget
 
  Read Operation Details: Anyone can read (public). The public-facing prize pot card reads currentAmount (the real displayed pot number) and targetAmount (aspirational target for the projected-split feature). All fields are returned.
  
 */
export async function getManyMonthlyRewardTarget(filter: string = ""): Promise<MonthlyRewardTargetResponse[]> {
  try {
    const results = await get("monthlyRewardTarget", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardTargetResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardTarget collection at path 'monthlyRewardTarget': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardTarget collection at monthlyRewardTarget
 
  Read Operation Details: Anyone can read (public). The public-facing prize pot card reads currentAmount (the real displayed pot number) and targetAmount (aspirational target for the projected-split feature). All fields are returned.
  
 */
export function subscribeManyMonthlyRewardTarget(callback: (data: MonthlyRewardTargetResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardTarget", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardTargetResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardTarget collection at path '${"monthlyRewardTarget"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all MonthlyRewardTarget items from collection monthlyRewardTarget
 
  Read Operation Details: Anyone can read (public). The public-facing prize pot card reads currentAmount (the real displayed pot number) and targetAmount (aspirational target for the projected-split feature). All fields are returned.
  
 */
export async function getAllMonthlyRewardTarget(filter: string = ""): Promise<MonthlyRewardTargetResponse[]> {
  try {
    const results = await get("monthlyRewardTarget", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardTargetResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardTarget collection at path 'monthlyRewardTarget': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardTarget collection at monthlyRewardTarget
 
  Read Operation Details: Anyone can read (public). The public-facing prize pot card reads currentAmount (the real displayed pot number) and targetAmount (aspirational target for the projected-split feature). All fields are returned.
  
 */
export function subscribeAllMonthlyRewardTarget(callback: (data: MonthlyRewardTargetResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardTarget", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardTargetResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardTarget collection at path '${"monthlyRewardTarget"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count MonthlyRewardTarget items in collection monthlyRewardTarget.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countMonthlyRewardTarget(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("monthlyRewardTarget", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting MonthlyRewardTarget at path 'monthlyRewardTarget': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on MonthlyRewardTarget items in collection monthlyRewardTarget.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateMonthlyRewardTarget(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("monthlyRewardTarget", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating MonthlyRewardTarget at path 'monthlyRewardTarget': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only — @user.address must equal @constants.ADMIN_ADDRESS. Admin can remove a month's target if set in error.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteMonthlyRewardTarget(monthKey: string): Promise<boolean> {
  try {
    const succeeded = await set(`monthlyRewardTarget/${monthKey}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting MonthlyRewardTarget: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for MonthlyRewardTarget for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteMonthlyRewardTarget(monthKey: string): DocumentOperation {
  return { path: `monthlyRewardTarget/${monthKey}`, document: null };
}

