// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: monthlyRewardWithdrawal/$withdrawalId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * ONCHAIN passthrough. Admin-only WITHDRAW that pulls a token back OUT of the CURRENT, not-yet-finalized month's prize pot PDA (per-token, partial or full) — to fix a wrong-amount or wrong-token deposit. Reverse of monthlyRewardDeposit. The onchain hook transfers `amount` base units of `mint` FROM the pot PDA (potAccountId) back to the admin caller; the program signs for the PDA exactly like the allotment payout. Does NOT call createAccount — the PDA already exists from prior deposits. NOT-FINALIZED GUARD (enforced on-chain): the create rule reads the rank-1 allotment doc for this month and requires it to NOT exist yet (the backend Heartbeat creates monthlyRewardAllotment/{potAccountId}_1 at finalization). The rank-1 allotment id is supplied by the frontend as rank1AllotmentId so the guard uses the proven get(/coll/@newData.field) path-interpolation form (avoids the +-concat-as-arithmetic path bug). monthKey UNDERSCORE format e.g. '2026_06'. potAccountId deterministic e.g. 'monthlyPot_2026_06' (alphanumeric + underscore only). rank1AllotmentId is the rank-1 allotment id for the month, built by the frontend as '{potAccountId}_1' e.g. 'monthlyPot_2026_06_1'. Frontend builds $withdrawalId as '{potAccountId}_{unixSecs}' (underscores only). amount in the token's base units (lamports for SOL, micro-units for SPL).
 */

export interface MonthlyRewardWithdrawalRequest {
  monthKey: string;
  potAccountId: string;
  mint: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  rank1AllotmentId: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MonthlyRewardWithdrawalResponse {
  monthKey: string;
  potAccountId: string;
  mint: string;
  amount: number;
  rank1AllotmentId: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a MonthlyRewardWithdrawal operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMonthlyRewardWithdrawal(withdrawalId: string, data?: MonthlyRewardWithdrawalRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `monthlyRewardWithdrawal/${withdrawalId}`, document: doc };
}

/**
 * Admin-only (@constants.ADMIN_ADDRESS). amount > 0. NOT-FINALIZED GUARD: the onchain rule reads get(/monthlyRewardAllotment/{rank1AllotmentId}) (rank1AllotmentId supplied by the frontend as '{potAccountId}_1') and requires it to be null — i.e. the month has NOT been finalized yet (the Heartbeat pre-creates the rank-1 allotment at finalization). This blocks any withdrawal once winners are locked. Onchain hook (atomic): @TokenPlugin.transfer moves `amount` base units of `mint` FROM the pot PDA (@newData.potAccountId — the program signs for it, same mechanism as the allotment payout) back to the admin caller (@user.address). Does NOT createAccount; the PDA already exists from prior deposits. Withdrawing more than the PDA holds for that mint will fail the transfer and roll back the whole tx. Pass @constants.SOL as mint for native test-SOL. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMonthlyRewardWithdrawal(withdrawalId: string, data?: MonthlyRewardWithdrawalRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`monthlyRewardWithdrawal/${withdrawalId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting MonthlyRewardWithdrawal: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read withdrawal records (audit trail of admin pot corrections).
   (Get Single Item)
 */
export async function getMonthlyRewardWithdrawal(withdrawalId: string): Promise<MonthlyRewardWithdrawalResponse | null> {
  try {
    const result = await get(`monthlyRewardWithdrawal/${withdrawalId}`);
    return result as MonthlyRewardWithdrawalResponse | null;
  } catch (error) {
    console.error(`Error getting MonthlyRewardWithdrawal: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single MonthlyRewardWithdrawal document. (
  Read Operation Details: Public (onchain). Anyone can read withdrawal records (audit trail of admin pot corrections).
  )
 */
export function subscribeMonthlyRewardWithdrawal(callback: (data: MonthlyRewardWithdrawalResponse | null) => void, withdrawalId: string): Promise<() => Promise<void>> {
  return subscribe(`monthlyRewardWithdrawal/${withdrawalId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MonthlyRewardWithdrawalResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to MonthlyRewardWithdrawal at path '${`monthlyRewardWithdrawal/${withdrawalId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many MonthlyRewardWithdrawal items from collection monthlyRewardWithdrawal
 
  Read Operation Details: Public (onchain). Anyone can read withdrawal records (audit trail of admin pot corrections).
  
 */
export async function getManyMonthlyRewardWithdrawal(filter: string = ""): Promise<MonthlyRewardWithdrawalResponse[]> {
  try {
    const results = await get("monthlyRewardWithdrawal", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardWithdrawalResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardWithdrawal collection at path 'monthlyRewardWithdrawal': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardWithdrawal collection at monthlyRewardWithdrawal
 
  Read Operation Details: Public (onchain). Anyone can read withdrawal records (audit trail of admin pot corrections).
  
 */
export function subscribeManyMonthlyRewardWithdrawal(callback: (data: MonthlyRewardWithdrawalResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardWithdrawal", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardWithdrawalResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardWithdrawal collection at path '${"monthlyRewardWithdrawal"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all MonthlyRewardWithdrawal items from collection monthlyRewardWithdrawal
 
  Read Operation Details: Public (onchain). Anyone can read withdrawal records (audit trail of admin pot corrections).
  
 */
export async function getAllMonthlyRewardWithdrawal(filter: string = ""): Promise<MonthlyRewardWithdrawalResponse[]> {
  try {
    const results = await get("monthlyRewardWithdrawal", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardWithdrawalResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardWithdrawal collection at path 'monthlyRewardWithdrawal': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardWithdrawal collection at monthlyRewardWithdrawal
 
  Read Operation Details: Public (onchain). Anyone can read withdrawal records (audit trail of admin pot corrections).
  
 */
export function subscribeAllMonthlyRewardWithdrawal(callback: (data: MonthlyRewardWithdrawalResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardWithdrawal", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardWithdrawalResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardWithdrawal collection at path '${"monthlyRewardWithdrawal"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count MonthlyRewardWithdrawal items in collection monthlyRewardWithdrawal.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countMonthlyRewardWithdrawal(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("monthlyRewardWithdrawal", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting MonthlyRewardWithdrawal at path 'monthlyRewardWithdrawal': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on MonthlyRewardWithdrawal items in collection monthlyRewardWithdrawal.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateMonthlyRewardWithdrawal(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("monthlyRewardWithdrawal", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating MonthlyRewardWithdrawal at path 'monthlyRewardWithdrawal': ${formatError(error)}`);
    return { value: 0 };
  }
}

/** Arguments accepted by the "getPotVaultAddress" query on MonthlyRewardWithdrawal. */
interface MonthlyRewardWithdrawalGetPotVaultAddressArgs {
  potAccountId: string;
}

/**
 * Runs the "getPotVaultAddress" query on MonthlyRewardWithdrawal.
 * Query Logic: @AccountPlugin.getAccountAddress(@newData.potAccountId)
 */
export async function runGetPotVaultAddressQueryForMonthlyRewardWithdrawal(withdrawalId: string, args: MonthlyRewardWithdrawalGetPotVaultAddressArgs): Promise<string> {
  try {
    const result = await runQuery(`monthlyRewardWithdrawal/${withdrawalId}`, "getPotVaultAddress", args);
    return result as string;
  } catch (error) {
    console.error(`Error running query "getPotVaultAddress" on MonthlyRewardWithdrawal: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "getPotTokenBalance" query on MonthlyRewardWithdrawal. */
interface MonthlyRewardWithdrawalGetPotTokenBalanceArgs {
  potAccountId: string;
  mint: string;
}

/**
 * Runs the "getPotTokenBalance" query on MonthlyRewardWithdrawal.
 * Query Logic: @TokenPlugin.getBalance(@AccountPlugin.getAccountAddress(@newData.potAccountId), @newData.mint)
 */
export async function runGetPotTokenBalanceQueryForMonthlyRewardWithdrawal(withdrawalId: string, args: MonthlyRewardWithdrawalGetPotTokenBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`monthlyRewardWithdrawal/${withdrawalId}`, "getPotTokenBalance", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getPotTokenBalance" on MonthlyRewardWithdrawal: ${formatError(error)}`);
    throw error;
  }
}

