// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: monthlyRewardAllotment/$allotmentId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * ONCHAIN. The per-winner authorization + single-tx multi-token claim record. The backend Heartbeat PRE-CREATES one doc per winner at finalization (gated to PROJECT_VAULT_ADDRESS), baking in: the winner address, the rank, the potAccountId (the PDA to pay FROM), and the EXACT per-token amounts owed to THIS winner across up to 5 fixed slots (mint1..mint5 + amt1..amt5, already rank-split, e.g. rank1 = 50% of each token's pot). claimed starts false. THE WINNER THEN CLAIMS by UPDATING this same doc (claimed false->true) — this is the single winner-signed transaction. Because the doc was pre-created with the amounts, the onchain update rule/hook reads @data (no offchain cross-read needed): it requires @user.address == @data.winner and !@data.claimed (exactly-once), charges the flat 0.01 test-SOL fee from the winner to REWARD_FEE_WALLET, and transfers every populated token slot from the pot PDA to the winner — all atomically in ONE approval. Frontend builds $allotmentId as '{potAccountId}_{rank}' e.g. 'monthlyPot_2026_06_1' (winner address NOT used as id since it could collide with PDA-id rules; rank disambiguates the 3 winners). Empty slots are no-ops (amtN == 0) guarded so they never abort the transfer chain.
 */

export interface MonthlyRewardAllotmentRequest {
  monthKey: string;
  potAccountId: string;
  rank: number | TimeOperation | IncrementOperation | TokenAmount;
  winner: AddressType;
  claimed: boolean;
  mint1?: AddressType;
  amt1: number | TimeOperation | IncrementOperation | TokenAmount;
  mint2?: AddressType;
  amt2: number | TimeOperation | IncrementOperation | TokenAmount;
  mint3?: AddressType;
  amt3: number | TimeOperation | IncrementOperation | TokenAmount;
  mint4?: AddressType;
  amt4: number | TimeOperation | IncrementOperation | TokenAmount;
  mint5?: AddressType;
  amt5: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MonthlyRewardAllotmentResponse {
  monthKey: string;
  potAccountId: string;
  rank: number;
  winner: string;
  claimed: boolean;
  mint1?: string;
  amt1: number;
  mint2?: string;
  amt2: number;
  mint3?: string;
  amt3: number;
  mint4?: string;
  amt4: number;
  mint5?: string;
  amt5: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a MonthlyRewardAllotment operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMonthlyRewardAllotment(allotmentId: string, data: MonthlyRewardAllotmentRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `monthlyRewardAllotment/${allotmentId}`, document: doc };
}

/**
 * Backend Heartbeat only (PROJECT_VAULT_ADDRESS). At finalization the backend creates 3 docs (one per rank). It bakes the rank-split per-token amounts directly into amt1..amt5 (rank1 = 50% of each pot token, rank2 = 35%, rank3 = 15%, using multiply-before-divide integer math, e.g. (totalN * 5000)//10000). mintN must match the pot's deposited mints; set amtN = 0 (and mintN may be omitted) for unused slots. claimed must be false; rank in 1..3. potAccountId is the PDA the payout transfers FROM. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMonthlyRewardAllotment(allotmentId: string, data: MonthlyRewardAllotmentRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`monthlyRewardAllotment/${allotmentId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting MonthlyRewardAllotment: ${formatError(error)}`);
    return false;
  }
}

export type MonthlyRewardAllotmentRequestUpdate = Partial<MonthlyRewardAllotmentRequest>;

/**
 * Build a MonthlyRewardAllotment update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateMonthlyRewardAllotment(allotmentId: string, data: MonthlyRewardAllotmentRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `monthlyRewardAllotment/${allotmentId}`, document: doc };
}

/**
 * Winner-signed claim — the ONE transaction. Caller must equal @data.winner and the doc must be unclaimed (@data.claimed == false). The update may ONLY flip claimed false->true; winner, potAccountId and every amtN are required to be unchanged (prevents tampering with the baked amounts). Onchain hook (atomic, single approval): (1) transfers the flat MONTHLY_REWARD_CLAIM_FEE_LAMPORTS (0.01 test-SOL) from the WINNER (@user.address, who signs) to @constants.REWARD_FEE_WALLET; (2) for each of the 5 slots, if amtN > 0 transfers amtN of mintN from the pot PDA (@data.potAccountId — the program signs for it) to @data.winner, and if amtN == 0 it is a safe no-op that does not abort the chain. All transfers succeed-or-roll-back together. Setting claimed=true in the same update guarantees exactly-once (a second update fails the @data.claimed == false guard). Frontend must send a FULL update preserving winner/potAccountId/amtN unchanged and only setting claimed=true. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateMonthlyRewardAllotment(allotmentId: string, data: MonthlyRewardAllotmentRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`monthlyRewardAllotment/${allotmentId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating MonthlyRewardAllotment: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read allotment/claim records. A winner's frontend reads their own doc at '{potAccountId}_{rank}' to show what's claimable.
   (Get Single Item)
 */
export async function getMonthlyRewardAllotment(allotmentId: string): Promise<MonthlyRewardAllotmentResponse | null> {
  try {
    const result = await get(`monthlyRewardAllotment/${allotmentId}`);
    return result as MonthlyRewardAllotmentResponse | null;
  } catch (error) {
    console.error(`Error getting MonthlyRewardAllotment: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single MonthlyRewardAllotment document. (
  Read Operation Details: Public (onchain). Anyone can read allotment/claim records. A winner's frontend reads their own doc at '{potAccountId}_{rank}' to show what's claimable.
  )
 */
export function subscribeMonthlyRewardAllotment(callback: (data: MonthlyRewardAllotmentResponse | null) => void, allotmentId: string): Promise<() => Promise<void>> {
  return subscribe(`monthlyRewardAllotment/${allotmentId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MonthlyRewardAllotmentResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to MonthlyRewardAllotment at path '${`monthlyRewardAllotment/${allotmentId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many MonthlyRewardAllotment items from collection monthlyRewardAllotment
 
  Read Operation Details: Public (onchain). Anyone can read allotment/claim records. A winner's frontend reads their own doc at '{potAccountId}_{rank}' to show what's claimable.
  
 */
export async function getManyMonthlyRewardAllotment(filter: string = ""): Promise<MonthlyRewardAllotmentResponse[]> {
  try {
    const results = await get("monthlyRewardAllotment", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardAllotmentResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardAllotment collection at path 'monthlyRewardAllotment': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardAllotment collection at monthlyRewardAllotment
 
  Read Operation Details: Public (onchain). Anyone can read allotment/claim records. A winner's frontend reads their own doc at '{potAccountId}_{rank}' to show what's claimable.
  
 */
export function subscribeManyMonthlyRewardAllotment(callback: (data: MonthlyRewardAllotmentResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardAllotment", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardAllotmentResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardAllotment collection at path '${"monthlyRewardAllotment"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all MonthlyRewardAllotment items from collection monthlyRewardAllotment
 
  Read Operation Details: Public (onchain). Anyone can read allotment/claim records. A winner's frontend reads their own doc at '{potAccountId}_{rank}' to show what's claimable.
  
 */
export async function getAllMonthlyRewardAllotment(filter: string = ""): Promise<MonthlyRewardAllotmentResponse[]> {
  try {
    const results = await get("monthlyRewardAllotment", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardAllotmentResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardAllotment collection at path 'monthlyRewardAllotment': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardAllotment collection at monthlyRewardAllotment
 
  Read Operation Details: Public (onchain). Anyone can read allotment/claim records. A winner's frontend reads their own doc at '{potAccountId}_{rank}' to show what's claimable.
  
 */
export function subscribeAllMonthlyRewardAllotment(callback: (data: MonthlyRewardAllotmentResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardAllotment", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardAllotmentResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardAllotment collection at path '${"monthlyRewardAllotment"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count MonthlyRewardAllotment items in collection monthlyRewardAllotment.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countMonthlyRewardAllotment(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("monthlyRewardAllotment", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting MonthlyRewardAllotment at path 'monthlyRewardAllotment': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on MonthlyRewardAllotment items in collection monthlyRewardAllotment.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateMonthlyRewardAllotment(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("monthlyRewardAllotment", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating MonthlyRewardAllotment at path 'monthlyRewardAllotment': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getPotVaultAddress" query on MonthlyRewardAllotment.
 * Query Logic: @AccountPlugin.getAccountAddress(@data.potAccountId)
 */
export async function runGetPotVaultAddressQueryForMonthlyRewardAllotment(allotmentId: string, ): Promise<string> {
  try {
    const result = await runQuery(`monthlyRewardAllotment/${allotmentId}`, "getPotVaultAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getPotVaultAddress" on MonthlyRewardAllotment: ${formatError(error)}`);
    throw error;
  }
}

