// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: notifications/$notificationId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * In-app notification fanned out to a user. Created ONLY by the backend (signing as PROJECT_VAULT_ADDRESS). Supports four types: 'open'/'close' (a trader the recipient follows opened or closed a trade), 'follow' (the recipient gained a new follower), and 'liquidated' (a trader the recipient follows, or the recipient themselves, was liquidated on Phoenix). For trade notifications ('open'/'close'), symbol and side are present (and pnlUsdCents/bigWin for 'close' events). For 'follow' notifications, symbol/side/pnlUsdCents/bigWin are ABSENT, actor is the new follower and recipient is the trader who was followed. For 'liquidated' notifications, symbol and side are present (the liquidated position's market and direction), pnlUsdCents/bigWin are ABSENT, actor is the liquidated trader, recipient is either a follower of that trader OR the trader themselves (self-notification), and actorName is the liquidated trader's cached display name. The recipient can mark their own notification read (partial update of just the 'read' field) and delete their own. $notificationId is a backend-generated unique id.
 */

export interface NotificationsRequest {
  recipient: AddressType;
  actor: AddressType;
  actorName?: string;
  type: string;
  symbol?: string;
  side?: string;
  pnlUsdCents?: number | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  read: boolean;
  bigWin?: boolean;
}

export interface NotificationsResponse {
  recipient: string;
  actor: string;
  actorName?: string;
  type: string;
  symbol?: string;
  side?: string;
  pnlUsdCents?: number;
  createdAt: number;
  read: boolean;
  bigWin?: boolean;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Notifications operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildNotifications(notificationId: string, data: NotificationsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `notifications/${notificationId}`, document: doc };
}

/**
 * Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so backend fan-out resolves to this. Backend sets read=false on creation. type is 'open', 'close', 'follow', or 'liquidated'. For 'open'/'close' trade notifications: symbol is the market symbol, side is 'long' or 'short', pnlUsdCents is signed US cents present only for 'close' events (CAN BE NEGATIVE), and bigWin is an optional Bool flagging a 'close' whose realized PnL exceeds a highlight threshold. For 'follow' notifications: symbol, side, pnlUsdCents, and bigWin are ABSENT; actor is the new follower and recipient is the trader who was followed; actorName is the follower's cached display name. For 'liquidated' notifications: symbol and side are present (the liquidated position's market and direction), pnlUsdCents and bigWin are ABSENT, actor is the liquidated trader, recipient is either a follower of that trader OR the trader themselves (self-notification), and actorName is the liquidated trader's cached display name. createdAt is Unix seconds; actorName is optional cached display name. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setNotifications(notificationId: string, data: NotificationsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`notifications/${notificationId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Notifications: ${formatError(error)}`);
    return false;
  }
}

export type NotificationsRequestUpdate = Partial<NotificationsRequest>;

/**
 * Build a Notifications update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateNotifications(notificationId: string, data: NotificationsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `notifications/${notificationId}`, document: doc };
}

/**
 * Only the recipient (@user.address == @data.recipient), used to flip 'read' to true via a partial update of just the 'read' field. Fields are intentionally NOT marked readonly (no '!') so a partial { read: true } update succeeds without re-sending recipient/actor/createdAt/bigWin. recipient/actor/createdAt/bigWin are conceptually immutable; the recipient has no UI to change them and the rule restricts updates to the recipient only. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateNotifications(notificationId: string, data: NotificationsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`notifications/${notificationId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Notifications: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Only the recipient (@user.address == @data.recipient). Notifications are private to the recipient.
   (Get Single Item)
 */
export async function getNotifications(notificationId: string): Promise<NotificationsResponse | null> {
  try {
    const result = await get(`notifications/${notificationId}`);
    return result as NotificationsResponse | null;
  } catch (error) {
    console.error(`Error getting Notifications: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Notifications document. (
  Read Operation Details: Only the recipient (@user.address == @data.recipient). Notifications are private to the recipient.
  )
 */
export function subscribeNotifications(callback: (data: NotificationsResponse | null) => void, notificationId: string): Promise<() => Promise<void>> {
  return subscribe(`notifications/${notificationId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as NotificationsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Notifications at path '${`notifications/${notificationId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Notifications items from collection notifications
 
  Read Operation Details: Only the recipient (@user.address == @data.recipient). Notifications are private to the recipient.
  
 */
export async function getManyNotifications(filter: string = ""): Promise<NotificationsResponse[]> {
  try {
    const results = await get("notifications", { prompt: filter });
    return Array.isArray(results) ? results as NotificationsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Notifications collection at path 'notifications': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Notifications collection at notifications
 
  Read Operation Details: Only the recipient (@user.address == @data.recipient). Notifications are private to the recipient.
  
 */
export function subscribeManyNotifications(callback: (data: NotificationsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("notifications", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as NotificationsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Notifications collection at path '${"notifications"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Notifications items from collection notifications
 
  Read Operation Details: Only the recipient (@user.address == @data.recipient). Notifications are private to the recipient.
  
 */
export async function getAllNotifications(filter: string = ""): Promise<NotificationsResponse[]> {
  try {
    const results = await get("notifications", { prompt: filter });
    return Array.isArray(results) ? results as NotificationsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Notifications collection at path 'notifications': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Notifications collection at notifications
 
  Read Operation Details: Only the recipient (@user.address == @data.recipient). Notifications are private to the recipient.
  
 */
export function subscribeAllNotifications(callback: (data: NotificationsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("notifications", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as NotificationsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Notifications collection at path '${"notifications"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: The recipient (@user.address == @data.recipient) or the backend vault (@constants.PROJECT_VAULT_ADDRESS).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteNotifications(notificationId: string): Promise<boolean> {
  try {
    const succeeded = await set(`notifications/${notificationId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Notifications: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Notifications for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteNotifications(notificationId: string): DocumentOperation {
  return { path: `notifications/${notificationId}`, document: null };
}

