// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: phoenixSubaccount/$subaccountId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Isolated margin subaccount metadata. Offchain tracking of user-created isolated subaccounts for Phoenix Perps.
 */

export interface PhoenixSubaccountRequest {
  wallet: AddressType;
  index: number | TimeOperation | IncrementOperation | TokenAmount;
  name: string;
  collateral: number | TimeOperation | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixSubaccountResponse {
  wallet: string;
  index: number;
  name: string;
  collateral: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PhoenixSubaccount operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixSubaccount(subaccountId: string, data?: PhoenixSubaccountRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixSubaccount/${subaccountId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal @newData.wallet. index must be > 0 (0 is reserved for cross-margin). Stores metadata about an isolated subaccount including display name and collateral balance (in USDC decimals, 6). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixSubaccount(subaccountId: string, data?: PhoenixSubaccountRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixSubaccount/${subaccountId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixSubaccount: ${formatError(error)}`);
    return false;
  }
}

export type PhoenixSubaccountRequestUpdate = Partial<PhoenixSubaccountRequest>;

/**
 * Build a PhoenixSubaccount update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePhoenixSubaccount(subaccountId: string, data: PhoenixSubaccountRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `phoenixSubaccount/${subaccountId}`, document: doc };
}

/**
 * Owner only. Only the wallet that created the subaccount can update its metadata (e.g. name, collateral tracking). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePhoenixSubaccount(subaccountId: string, data: PhoenixSubaccountRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`phoenixSubaccount/${subaccountId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PhoenixSubaccount: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. UI filters by wallet to show a user's isolated subaccounts.
   (Get Single Item)
 */
export async function getPhoenixSubaccount(subaccountId: string): Promise<PhoenixSubaccountResponse | null> {
  try {
    const result = await get(`phoenixSubaccount/${subaccountId}`);
    return result as PhoenixSubaccountResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixSubaccount: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixSubaccount document. (
  Read Operation Details: Anyone can read. UI filters by wallet to show a user's isolated subaccounts.
  )
 */
export function subscribePhoenixSubaccount(callback: (data: PhoenixSubaccountResponse | null) => void, subaccountId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixSubaccount/${subaccountId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixSubaccountResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixSubaccount at path '${`phoenixSubaccount/${subaccountId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixSubaccount items from collection phoenixSubaccount
 
  Read Operation Details: Anyone can read. UI filters by wallet to show a user's isolated subaccounts.
  
 */
export async function getManyPhoenixSubaccount(filter: string = ""): Promise<PhoenixSubaccountResponse[]> {
  try {
    const results = await get("phoenixSubaccount", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixSubaccountResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixSubaccount collection at path 'phoenixSubaccount': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixSubaccount collection at phoenixSubaccount
 
  Read Operation Details: Anyone can read. UI filters by wallet to show a user's isolated subaccounts.
  
 */
export function subscribeManyPhoenixSubaccount(callback: (data: PhoenixSubaccountResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixSubaccount", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixSubaccountResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixSubaccount collection at path '${"phoenixSubaccount"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixSubaccount items from collection phoenixSubaccount
 
  Read Operation Details: Anyone can read. UI filters by wallet to show a user's isolated subaccounts.
  
 */
export async function getAllPhoenixSubaccount(filter: string = ""): Promise<PhoenixSubaccountResponse[]> {
  try {
    const results = await get("phoenixSubaccount", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixSubaccountResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixSubaccount collection at path 'phoenixSubaccount': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixSubaccount collection at phoenixSubaccount
 
  Read Operation Details: Anyone can read. UI filters by wallet to show a user's isolated subaccounts.
  
 */
export function subscribeAllPhoenixSubaccount(callback: (data: PhoenixSubaccountResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixSubaccount", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixSubaccountResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixSubaccount collection at path '${"phoenixSubaccount"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixSubaccount items in collection phoenixSubaccount.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixSubaccount(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixSubaccount", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixSubaccount at path 'phoenixSubaccount': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixSubaccount items in collection phoenixSubaccount.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixSubaccount(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixSubaccount", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixSubaccount at path 'phoenixSubaccount': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Owner only. Only the wallet that created the subaccount can delete its metadata record.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePhoenixSubaccount(subaccountId: string): Promise<boolean> {
  try {
    const succeeded = await set(`phoenixSubaccount/${subaccountId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PhoenixSubaccount: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PhoenixSubaccount for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePhoenixSubaccount(subaccountId: string): DocumentOperation {
  return { path: `phoenixSubaccount/${subaccountId}`, document: null };
}

