// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: phoenixIsolatedSweep/$sweepId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Sweep free collateral from an isolated subaccount back to cross-margin.
 */

export interface PhoenixIsolatedSweepRequest {
  subaccountIndex: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixIsolatedSweepResponse {
  subaccountIndex: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixIsolatedSweep operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixIsolatedSweep(sweepId: string, data?: PhoenixIsolatedSweepRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixIsolatedSweep/${sweepId}`, document: doc };
}

/**
 * Authenticated users only. Sweeps all free collateral from the isolated subaccount (subaccountIndex > 0) back to cross-margin. Any open positions in the isolated subaccount will block the sweep. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixIsolatedSweep(sweepId: string, data?: PhoenixIsolatedSweepRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixIsolatedSweep/${sweepId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixIsolatedSweep: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
   (Get Single Item)
 */
export async function getPhoenixIsolatedSweep(sweepId: string): Promise<PhoenixIsolatedSweepResponse | null> {
  try {
    const result = await get(`phoenixIsolatedSweep/${sweepId}`);
    return result as PhoenixIsolatedSweepResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedSweep: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixIsolatedSweep document. (
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  )
 */
export function subscribePhoenixIsolatedSweep(callback: (data: PhoenixIsolatedSweepResponse | null) => void, sweepId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixIsolatedSweep/${sweepId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixIsolatedSweepResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixIsolatedSweep at path '${`phoenixIsolatedSweep/${sweepId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixIsolatedSweep items from collection phoenixIsolatedSweep
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getManyPhoenixIsolatedSweep(filter: string = ""): Promise<PhoenixIsolatedSweepResponse[]> {
  try {
    const results = await get("phoenixIsolatedSweep", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsolatedSweepResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedSweep collection at path 'phoenixIsolatedSweep': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsolatedSweep collection at phoenixIsolatedSweep
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeManyPhoenixIsolatedSweep(callback: (data: PhoenixIsolatedSweepResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsolatedSweep", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsolatedSweepResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsolatedSweep collection at path '${"phoenixIsolatedSweep"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixIsolatedSweep items from collection phoenixIsolatedSweep
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getAllPhoenixIsolatedSweep(filter: string = ""): Promise<PhoenixIsolatedSweepResponse[]> {
  try {
    const results = await get("phoenixIsolatedSweep", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsolatedSweepResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedSweep collection at path 'phoenixIsolatedSweep': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsolatedSweep collection at phoenixIsolatedSweep
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeAllPhoenixIsolatedSweep(callback: (data: PhoenixIsolatedSweepResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsolatedSweep", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsolatedSweepResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsolatedSweep collection at path '${"phoenixIsolatedSweep"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixIsolatedSweep items in collection phoenixIsolatedSweep.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixIsolatedSweep(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixIsolatedSweep", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixIsolatedSweep at path 'phoenixIsolatedSweep': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixIsolatedSweep items in collection phoenixIsolatedSweep.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixIsolatedSweep(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixIsolatedSweep", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixIsolatedSweep at path 'phoenixIsolatedSweep': ${formatError(error)}`);
    return { value: 0 };
  }
}

