// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.203Z
// Collection: phoenixDeposit/$depositId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Deposit USDC as Phoenix margin (USDC -> PhUSD -> margin). Transient onchain action — no permanent state stored.
 */

export interface PhoenixDepositRequest {
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixDepositResponse {
  amt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixDeposit operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixDeposit(depositId: string, data?: PhoenixDepositRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixDeposit/${depositId}`, document: doc };
}

/**
 * Authenticated users only. Deposits USDC as Phoenix margin for the caller. Chains emberDeposit (USDC -> PhUSD) and depositFunds (PhUSD -> margin) in one onchain operation. `amt` is in USDC smallest units (6 decimals: 1 USDC = 1,000,000). Caller signs as the source — funds are deducted from @user.address. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixDeposit(depositId: string, data?: PhoenixDepositRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixDeposit/${depositId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixDeposit: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
   (Get Single Item)
 */
export async function getPhoenixDeposit(depositId: string): Promise<PhoenixDepositResponse | null> {
  try {
    const result = await get(`phoenixDeposit/${depositId}`);
    return result as PhoenixDepositResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixDeposit: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixDeposit document. (
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  )
 */
export function subscribePhoenixDeposit(callback: (data: PhoenixDepositResponse | null) => void, depositId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixDeposit/${depositId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixDepositResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixDeposit at path '${`phoenixDeposit/${depositId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixDeposit items from collection phoenixDeposit
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getManyPhoenixDeposit(filter: string = ""): Promise<PhoenixDepositResponse[]> {
  try {
    const results = await get("phoenixDeposit", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixDepositResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixDeposit collection at path 'phoenixDeposit': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixDeposit collection at phoenixDeposit
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeManyPhoenixDeposit(callback: (data: PhoenixDepositResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixDeposit", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixDepositResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixDeposit collection at path '${"phoenixDeposit"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixDeposit items from collection phoenixDeposit
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getAllPhoenixDeposit(filter: string = ""): Promise<PhoenixDepositResponse[]> {
  try {
    const results = await get("phoenixDeposit", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixDepositResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixDeposit collection at path 'phoenixDeposit': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixDeposit collection at phoenixDeposit
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeAllPhoenixDeposit(callback: (data: PhoenixDepositResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixDeposit", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixDepositResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixDeposit collection at path '${"phoenixDeposit"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixDeposit items in collection phoenixDeposit.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixDeposit(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixDeposit", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixDeposit at path 'phoenixDeposit': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixDeposit items in collection phoenixDeposit.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixDeposit(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixDeposit", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixDeposit at path 'phoenixDeposit': ${formatError(error)}`);
    return { value: 0 };
  }
}

