// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.104Z
// Collection: phoenixOrder/$orderId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Place a market order (long or short) on Phoenix Perps. Onchain hook calls @PhoenixPerpsPlugin.placeLong or placeShort based on side. Document is persistent (not passthrough) so the user can view their order history. Phoenix executes at best available price — no slippage/limit/SL/TP enforcement onchain (those fields are stored for UI display only).
 */

export interface PhoenixOrderRequest {
  trader: AddressType;
  market: AddressType;
  symbol: string;
  side: string;
  sizeBaseLots: number | TimeOperation | IncrementOperation | TokenAmount;
  leverage: number | TimeOperation | IncrementOperation | TokenAmount;
  orderType: string;
  limitPrice?: number | TimeOperation | IncrementOperation | TokenAmount;
  stopLoss?: number | TimeOperation | IncrementOperation | TokenAmount;
  takeProfit?: number | TimeOperation | IncrementOperation | TokenAmount;
  subaccountIndex: number | TimeOperation | IncrementOperation | TokenAmount;
  sizeUsd: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixOrderResponse {
  trader: string;
  market: string;
  symbol: string;
  side: string;
  sizeBaseLots: number;
  leverage: number;
  orderType: string;
  limitPrice?: number;
  stopLoss?: number;
  takeProfit?: number;
  subaccountIndex: number;
  sizeUsd: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixOrder operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixOrder(orderId: string, data?: PhoenixOrderRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixOrder/${orderId}`, document: doc };
}

/**
 * Authenticated users only. Caller wallet (@user.address) must equal @newData.trader. Side must be exactly 'long' or 'short'. The market pubkey is NOT enumerated against a per-market whitelist — any live Phoenix market is accepted so newly-listed markets work without policy edits. This is safe because the onchain hook uses @newData.market ONLY as the orderbook account passed into @PhoenixPerpsPlugin.placeLong/placeShort; the Phoenix on-chain program validates that account, so a non-Phoenix-market pubkey simply reverts the user's own transaction (no fund diversion possible — no transfer leg consumes @newData.market). On create the onchain hook calls placeLong (if side=='long') or placeShort with subaccountIndex (0 = cross margin, >0 = isolated margin). Phoenix executes at best available price. Caller must have already registered a Phoenix trader account and deposited margin. sizeBaseLots is in market-specific base lots. sizeUsd is the notional USD value used to award trading points ($1 = 1 point). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixOrder(orderId: string, data?: PhoenixOrderRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixOrder/${orderId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixOrder: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read (onchain data is public). UI typically filters by @data.trader == current wallet to show only that user's order history.
   (Get Single Item)
 */
export async function getPhoenixOrder(orderId: string): Promise<PhoenixOrderResponse | null> {
  try {
    const result = await get(`phoenixOrder/${orderId}`);
    return result as PhoenixOrderResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixOrder: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixOrder document. (
  Read Operation Details: Anyone can read (onchain data is public). UI typically filters by @data.trader == current wallet to show only that user's order history.
  )
 */
export function subscribePhoenixOrder(callback: (data: PhoenixOrderResponse | null) => void, orderId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixOrder/${orderId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixOrderResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixOrder at path '${`phoenixOrder/${orderId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixOrder items from collection phoenixOrder
 
  Read Operation Details: Anyone can read (onchain data is public). UI typically filters by @data.trader == current wallet to show only that user's order history.
  
 */
export async function getManyPhoenixOrder(filter: string = ""): Promise<PhoenixOrderResponse[]> {
  try {
    const results = await get("phoenixOrder", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixOrderResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixOrder collection at path 'phoenixOrder': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixOrder collection at phoenixOrder
 
  Read Operation Details: Anyone can read (onchain data is public). UI typically filters by @data.trader == current wallet to show only that user's order history.
  
 */
export function subscribeManyPhoenixOrder(callback: (data: PhoenixOrderResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixOrder", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixOrderResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixOrder collection at path '${"phoenixOrder"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixOrder items from collection phoenixOrder
 
  Read Operation Details: Anyone can read (onchain data is public). UI typically filters by @data.trader == current wallet to show only that user's order history.
  
 */
export async function getAllPhoenixOrder(filter: string = ""): Promise<PhoenixOrderResponse[]> {
  try {
    const results = await get("phoenixOrder", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixOrderResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixOrder collection at path 'phoenixOrder': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixOrder collection at phoenixOrder
 
  Read Operation Details: Anyone can read (onchain data is public). UI typically filters by @data.trader == current wallet to show only that user's order history.
  
 */
export function subscribeAllPhoenixOrder(callback: (data: PhoenixOrderResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixOrder", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixOrderResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixOrder collection at path '${"phoenixOrder"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixOrder items in collection phoenixOrder.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixOrder(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixOrder", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixOrder at path 'phoenixOrder': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixOrder items in collection phoenixOrder.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixOrder(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixOrder", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixOrder at path 'phoenixOrder': ${formatError(error)}`);
    return { value: 0 };
  }
}

