// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.105Z
// Collection: phoenixWins/$winId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Records profitable (winning) position closes for the public Arena Wins ticker. Written exclusively by the backend vault using a deterministic recordId (derived from txSignature + trader). Immutable once written.
 */

export interface PhoenixWinsRequest {
  trader: AddressType;
  symbol: string;
  market: AddressType;
  pnlUsdCents: number | IncrementOperation | TokenAmount;
  createdAt: number | IncrementOperation | TokenAmount;
}

export interface PhoenixWinsResponse {
  trader: string;
  symbol: string;
  market: string;
  pnlUsdCents: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PhoenixWins operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixWins(winId: string, data?: PhoenixWinsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixWins/${winId}`, document: doc };
}

/**
 * Backend vault only. @user.address must equal @constants.PROJECT_VAULT_ADDRESS (the Cloudflare Worker signs Tarobase requests as the vault). Document key is a deterministic recordId computed by the backend from txSignature + trader, so no auto-id. pnlUsdCents is only ever written when > 0 (enforced by the backend, not the rule). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixWins(winId: string, data?: PhoenixWinsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixWins/${winId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixWins: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public. Anyone can read all fields; powers the live Arena Wins ticker.
   (Get Single Item)
 */
export async function getPhoenixWins(winId: string): Promise<PhoenixWinsResponse | null> {
  try {
    const result = await get(`phoenixWins/${winId}`);
    return result as PhoenixWinsResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixWins: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixWins document. (
  Read Operation Details: Public. Anyone can read all fields; powers the live Arena Wins ticker.
  )
 */
export function subscribePhoenixWins(callback: (data: PhoenixWinsResponse | null) => void, winId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixWins/${winId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixWinsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixWins at path '${`phoenixWins/${winId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixWins items from collection phoenixWins
 
  Read Operation Details: Public. Anyone can read all fields; powers the live Arena Wins ticker.
  
 */
export async function getManyPhoenixWins(filter: string = ""): Promise<PhoenixWinsResponse[]> {
  try {
    const results = await get("phoenixWins", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixWinsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixWins collection at path 'phoenixWins': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixWins collection at phoenixWins
 
  Read Operation Details: Public. Anyone can read all fields; powers the live Arena Wins ticker.
  
 */
export function subscribeManyPhoenixWins(callback: (data: PhoenixWinsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixWins", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixWinsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixWins collection at path '${"phoenixWins"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixWins items from collection phoenixWins
 
  Read Operation Details: Public. Anyone can read all fields; powers the live Arena Wins ticker.
  
 */
export async function getAllPhoenixWins(filter: string = ""): Promise<PhoenixWinsResponse[]> {
  try {
    const results = await get("phoenixWins", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixWinsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixWins collection at path 'phoenixWins': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixWins collection at phoenixWins
 
  Read Operation Details: Public. Anyone can read all fields; powers the live Arena Wins ticker.
  
 */
export function subscribeAllPhoenixWins(callback: (data: PhoenixWinsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixWins", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixWinsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixWins collection at path '${"phoenixWins"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixWins items in collection phoenixWins.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixWins(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixWins", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixWins at path 'phoenixWins': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixWins items in collection phoenixWins.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixWins(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixWins", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixWins at path 'phoenixWins': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Backend vault only (moderation/cleanup). Normal users cannot delete.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePhoenixWins(winId: string): Promise<boolean> {
  try {
    const succeeded = await set(`phoenixWins/${winId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PhoenixWins: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PhoenixWins for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePhoenixWins(winId: string): DocumentOperation {
  return { path: `phoenixWins/${winId}`, document: null };
}

