// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: phoenixIsolatedTransfer/$transferId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Transfer collateral from cross-margin to an isolated subaccount.
 */

export interface PhoenixIsolatedTransferRequest {
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
  subaccountIndex: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixIsolatedTransferResponse {
  amt: number;
  subaccountIndex: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixIsolatedTransfer operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixIsolatedTransfer(transferId: string, data?: PhoenixIsolatedTransferRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixIsolatedTransfer/${transferId}`, document: doc };
}

/**
 * Authenticated users only. Transfers amt (in USDC/PhUSD base units, 6 decimals) from cross-margin to the isolated subaccount specified by subaccountIndex. Both amt and subaccountIndex must be > 0. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixIsolatedTransfer(transferId: string, data?: PhoenixIsolatedTransferRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixIsolatedTransfer/${transferId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixIsolatedTransfer: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
   (Get Single Item)
 */
export async function getPhoenixIsolatedTransfer(transferId: string): Promise<PhoenixIsolatedTransferResponse | null> {
  try {
    const result = await get(`phoenixIsolatedTransfer/${transferId}`);
    return result as PhoenixIsolatedTransferResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedTransfer: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixIsolatedTransfer document. (
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  )
 */
export function subscribePhoenixIsolatedTransfer(callback: (data: PhoenixIsolatedTransferResponse | null) => void, transferId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixIsolatedTransfer/${transferId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixIsolatedTransferResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixIsolatedTransfer at path '${`phoenixIsolatedTransfer/${transferId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixIsolatedTransfer items from collection phoenixIsolatedTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getManyPhoenixIsolatedTransfer(filter: string = ""): Promise<PhoenixIsolatedTransferResponse[]> {
  try {
    const results = await get("phoenixIsolatedTransfer", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsolatedTransferResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedTransfer collection at path 'phoenixIsolatedTransfer': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsolatedTransfer collection at phoenixIsolatedTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeManyPhoenixIsolatedTransfer(callback: (data: PhoenixIsolatedTransferResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsolatedTransfer", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsolatedTransferResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsolatedTransfer collection at path '${"phoenixIsolatedTransfer"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixIsolatedTransfer items from collection phoenixIsolatedTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getAllPhoenixIsolatedTransfer(filter: string = ""): Promise<PhoenixIsolatedTransferResponse[]> {
  try {
    const results = await get("phoenixIsolatedTransfer", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsolatedTransferResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedTransfer collection at path 'phoenixIsolatedTransfer': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsolatedTransfer collection at phoenixIsolatedTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeAllPhoenixIsolatedTransfer(callback: (data: PhoenixIsolatedTransferResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsolatedTransfer", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsolatedTransferResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsolatedTransfer collection at path '${"phoenixIsolatedTransfer"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixIsolatedTransfer items in collection phoenixIsolatedTransfer.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixIsolatedTransfer(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixIsolatedTransfer", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixIsolatedTransfer at path 'phoenixIsolatedTransfer': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixIsolatedTransfer items in collection phoenixIsolatedTransfer.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixIsolatedTransfer(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixIsolatedTransfer", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixIsolatedTransfer at path 'phoenixIsolatedTransfer': ${formatError(error)}`);
    return { value: 0 };
  }
}

