// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.104Z
// Collection: phoenixTrader/$traderId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * One-time trader registration on Phoenix Perps. Document existence = registered. ID should be the user's wallet address.
 */

export interface PhoenixTraderRequest {

}

export interface PhoenixTraderResponse {

  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixTrader operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixTrader(traderId: string, data?: PhoenixTraderRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixTrader/${traderId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal $traderId (the wallet registering). Registers a cross-margin trader account on Phoenix via @PhoenixPerpsPlugin.registerTrader. Call once per wallet before any other Phoenix action. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixTrader(traderId: string, data?: PhoenixTraderRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixTrader/${traderId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixTrader: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read; document existence indicates the wallet has registered a Phoenix trader account.
   (Get Single Item)
 */
export async function getPhoenixTrader(traderId: string): Promise<PhoenixTraderResponse | null> {
  try {
    const result = await get(`phoenixTrader/${traderId}`);
    return result as PhoenixTraderResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixTrader: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixTrader document. (
  Read Operation Details: Anyone can read; document existence indicates the wallet has registered a Phoenix trader account.
  )
 */
export function subscribePhoenixTrader(callback: (data: PhoenixTraderResponse | null) => void, traderId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixTrader/${traderId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixTraderResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixTrader at path '${`phoenixTrader/${traderId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixTrader items from collection phoenixTrader
 
  Read Operation Details: Anyone can read; document existence indicates the wallet has registered a Phoenix trader account.
  
 */
export async function getManyPhoenixTrader(filter: string = ""): Promise<PhoenixTraderResponse[]> {
  try {
    const results = await get("phoenixTrader", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixTraderResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixTrader collection at path 'phoenixTrader': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixTrader collection at phoenixTrader
 
  Read Operation Details: Anyone can read; document existence indicates the wallet has registered a Phoenix trader account.
  
 */
export function subscribeManyPhoenixTrader(callback: (data: PhoenixTraderResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixTrader", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixTraderResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixTrader collection at path '${"phoenixTrader"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixTrader items from collection phoenixTrader
 
  Read Operation Details: Anyone can read; document existence indicates the wallet has registered a Phoenix trader account.
  
 */
export async function getAllPhoenixTrader(filter: string = ""): Promise<PhoenixTraderResponse[]> {
  try {
    const results = await get("phoenixTrader", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixTraderResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixTrader collection at path 'phoenixTrader': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixTrader collection at phoenixTrader
 
  Read Operation Details: Anyone can read; document existence indicates the wallet has registered a Phoenix trader account.
  
 */
export function subscribeAllPhoenixTrader(callback: (data: PhoenixTraderResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixTrader", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixTraderResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixTrader collection at path '${"phoenixTrader"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixTrader items in collection phoenixTrader.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixTrader(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixTrader", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixTrader at path 'phoenixTrader': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixTrader items in collection phoenixTrader.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixTrader(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixTrader", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixTrader at path 'phoenixTrader': ${formatError(error)}`);
    return { value: 0 };
  }
}

