// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.105Z
// Collection: pnlLeaderboard/$entryId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Precomputed per-trader, per-period realized PnL aggregates for the public leaderboard. Written exclusively by the backend Heartbeat task signing as PROJECT_VAULT_ADDRESS. entryId is a deterministic composite like '{period}:{traderAddress}' so the task can upsert each row on every run. Read-only cache table with no hooks or side effects.
 */

export interface PnlLeaderboardRequest {
  trader: AddressType;
  period: string;
  realizedPnlUsdCents: number | IncrementOperation | TokenAmount;
  tradeCount: number | TimeOperation | IncrementOperation | TokenAmount;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  rank: number | TimeOperation | IncrementOperation | TokenAmount;
  pnlHidden: boolean;
}

export interface PnlLeaderboardResponse {
  trader: string;
  period: string;
  realizedPnlUsdCents: number;
  tradeCount: number;
  updatedAt: number;
  rank: number;
  pnlHidden: boolean;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PnlLeaderboard operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPnlLeaderboard(entryId: string, data: PnlLeaderboardRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `pnlLeaderboard/${entryId}`, document: doc };
}

/**
 * Backend Heartbeat task only (caller must equal @constants.PROJECT_VAULT_ADDRESS). Creates one row per trader per period. entryId is a deterministic composite such as '{period}:{traderAddress}'. realizedPnlUsdCents is a SIGNED Int and CAN BE NEGATIVE. rank is the 1-based leaderboard position computed from true PnL ordering so position is preserved even when PnL is withheld. pnlHidden is true when the trader opted to hide their PnL (read from leaderboardPrivacy). All numeric fields are required (no nulls). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPnlLeaderboard(entryId: string, data: PnlLeaderboardRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`pnlLeaderboard/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PnlLeaderboard: ${formatError(error)}`);
    return false;
  }
}

export type PnlLeaderboardRequestUpdate = Partial<PnlLeaderboardRequest>;

/**
 * Build a PnlLeaderboard update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePnlLeaderboard(entryId: string, data: PnlLeaderboardRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `pnlLeaderboard/${entryId}`, document: doc };
}

/**
 * Backend Heartbeat task only (caller must equal @constants.PROJECT_VAULT_ADDRESS). The task overwrites the full row on every run with refreshed PnL, tradeCount, updatedAt, rank, and pnlHidden. When pnlHidden is true the task does NOT write the real PnL value into realizedPnlUsdCents. No fields are immutable so the upsert can always rewrite. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePnlLeaderboard(entryId: string, data: PnlLeaderboardRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`pnlLeaderboard/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PnlLeaderboard: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Leaderboard is fully public. Exposes trader address, period, signed realized PnL in US cents, trade count, last-updated timestamp, 1-based rank, and whether the trader hid their PnL.
   (Get Single Item)
 */
export async function getPnlLeaderboard(entryId: string): Promise<PnlLeaderboardResponse | null> {
  try {
    const result = await get(`pnlLeaderboard/${entryId}`);
    return result as PnlLeaderboardResponse | null;
  } catch (error) {
    console.error(`Error getting PnlLeaderboard: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PnlLeaderboard document. (
  Read Operation Details: Anyone can read. Leaderboard is fully public. Exposes trader address, period, signed realized PnL in US cents, trade count, last-updated timestamp, 1-based rank, and whether the trader hid their PnL.
  )
 */
export function subscribePnlLeaderboard(callback: (data: PnlLeaderboardResponse | null) => void, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`pnlLeaderboard/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PnlLeaderboardResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PnlLeaderboard at path '${`pnlLeaderboard/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PnlLeaderboard items from collection pnlLeaderboard
 
  Read Operation Details: Anyone can read. Leaderboard is fully public. Exposes trader address, period, signed realized PnL in US cents, trade count, last-updated timestamp, 1-based rank, and whether the trader hid their PnL.
  
 */
export async function getManyPnlLeaderboard(filter: string = ""): Promise<PnlLeaderboardResponse[]> {
  try {
    const results = await get("pnlLeaderboard", { prompt: filter });
    return Array.isArray(results) ? results as PnlLeaderboardResponse[] : [];
  } catch (error) {
    console.error(`Error getting PnlLeaderboard collection at path 'pnlLeaderboard': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PnlLeaderboard collection at pnlLeaderboard
 
  Read Operation Details: Anyone can read. Leaderboard is fully public. Exposes trader address, period, signed realized PnL in US cents, trade count, last-updated timestamp, 1-based rank, and whether the trader hid their PnL.
  
 */
export function subscribeManyPnlLeaderboard(callback: (data: PnlLeaderboardResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("pnlLeaderboard", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PnlLeaderboardResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PnlLeaderboard collection at path '${"pnlLeaderboard"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PnlLeaderboard items from collection pnlLeaderboard
 
  Read Operation Details: Anyone can read. Leaderboard is fully public. Exposes trader address, period, signed realized PnL in US cents, trade count, last-updated timestamp, 1-based rank, and whether the trader hid their PnL.
  
 */
export async function getAllPnlLeaderboard(filter: string = ""): Promise<PnlLeaderboardResponse[]> {
  try {
    const results = await get("pnlLeaderboard", { prompt: filter });
    return Array.isArray(results) ? results as PnlLeaderboardResponse[] : [];
  } catch (error) {
    console.error(`Error getting PnlLeaderboard collection at path 'pnlLeaderboard': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PnlLeaderboard collection at pnlLeaderboard
 
  Read Operation Details: Anyone can read. Leaderboard is fully public. Exposes trader address, period, signed realized PnL in US cents, trade count, last-updated timestamp, 1-based rank, and whether the trader hid their PnL.
  
 */
export function subscribeAllPnlLeaderboard(callback: (data: PnlLeaderboardResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("pnlLeaderboard", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PnlLeaderboardResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PnlLeaderboard collection at path '${"pnlLeaderboard"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PnlLeaderboard items in collection pnlLeaderboard.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPnlLeaderboard(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("pnlLeaderboard", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PnlLeaderboard at path 'pnlLeaderboard': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PnlLeaderboard items in collection pnlLeaderboard.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePnlLeaderboard(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("pnlLeaderboard", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PnlLeaderboard at path 'pnlLeaderboard': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Backend Heartbeat task only (caller must equal @constants.PROJECT_VAULT_ADDRESS). Used to clear a trader who falls out of a rolling time window (daily/weekly/monthly).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePnlLeaderboard(entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`pnlLeaderboard/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PnlLeaderboard: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PnlLeaderboard for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePnlLeaderboard(entryId: string): DocumentOperation {
  return { path: `pnlLeaderboard/${entryId}`, document: null };
}

