// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.105Z
// Collection: positionSnapshots/$traderId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Internal backend-only state for the liquidation-detection Heartbeat task. Each tick the task overwrites this document with the trader's current open positions so the next tick can diff against it to detect liquidations. Keyed by the trader's wallet address ($traderId IS the trader's address). Written and read ONLY by the backend (signing as PROJECT_VAULT_ADDRESS). No hooks. Fields are intentionally NOT readonly so the per-tick overwrite (update) always succeeds.
 */

export interface PositionSnapshotsRequest {
  trader: AddressType;
  positions: string;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PositionSnapshotsResponse {
  trader: string;
  positions: string;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PositionSnapshots operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPositionSnapshots(traderId: string, data: PositionSnapshotsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `positionSnapshots/${traderId}`, document: doc };
}

/**
 * Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). On the first tick for a trader the Heartbeat task creates the snapshot. trader is the trader's wallet (equal to $traderId), positions is a JSON-serialized array/map of open positions (symbol, side, collateral in cents, size) opaque to the policy, updatedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPositionSnapshots(traderId: string, data: PositionSnapshotsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`positionSnapshots/${traderId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PositionSnapshots: ${formatError(error)}`);
    return false;
  }
}

export type PositionSnapshotsRequestUpdate = Partial<PositionSnapshotsRequest>;

/**
 * Build a PositionSnapshots update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePositionSnapshots(traderId: string, data: PositionSnapshotsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `positionSnapshots/${traderId}`, document: doc };
}

/**
 * Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). Each subsequent tick overwrites the document with the trader's current positions. Fields are NOT readonly so the overwrite succeeds. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePositionSnapshots(traderId: string, data: PositionSnapshotsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`positionSnapshots/${traderId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PositionSnapshots: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task can read the previous tick's snapshot. Internal state, not exposed to clients.
   (Get Single Item)
 */
export async function getPositionSnapshots(traderId: string): Promise<PositionSnapshotsResponse | null> {
  try {
    const result = await get(`positionSnapshots/${traderId}`);
    return result as PositionSnapshotsResponse | null;
  } catch (error) {
    console.error(`Error getting PositionSnapshots: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PositionSnapshots document. (
  Read Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task can read the previous tick's snapshot. Internal state, not exposed to clients.
  )
 */
export function subscribePositionSnapshots(callback: (data: PositionSnapshotsResponse | null) => void, traderId: string): Promise<() => Promise<void>> {
  return subscribe(`positionSnapshots/${traderId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PositionSnapshotsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PositionSnapshots at path '${`positionSnapshots/${traderId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PositionSnapshots items from collection positionSnapshots
 
  Read Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task can read the previous tick's snapshot. Internal state, not exposed to clients.
  
 */
export async function getManyPositionSnapshots(filter: string = ""): Promise<PositionSnapshotsResponse[]> {
  try {
    const results = await get("positionSnapshots", { prompt: filter });
    return Array.isArray(results) ? results as PositionSnapshotsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PositionSnapshots collection at path 'positionSnapshots': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PositionSnapshots collection at positionSnapshots
 
  Read Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task can read the previous tick's snapshot. Internal state, not exposed to clients.
  
 */
export function subscribeManyPositionSnapshots(callback: (data: PositionSnapshotsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("positionSnapshots", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PositionSnapshotsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PositionSnapshots collection at path '${"positionSnapshots"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PositionSnapshots items from collection positionSnapshots
 
  Read Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task can read the previous tick's snapshot. Internal state, not exposed to clients.
  
 */
export async function getAllPositionSnapshots(filter: string = ""): Promise<PositionSnapshotsResponse[]> {
  try {
    const results = await get("positionSnapshots", { prompt: filter });
    return Array.isArray(results) ? results as PositionSnapshotsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PositionSnapshots collection at path 'positionSnapshots': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PositionSnapshots collection at positionSnapshots
 
  Read Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). The Cloudflare Worker signs Tarobase requests as PROJECT_VAULT_ADDRESS, so the Heartbeat task can read the previous tick's snapshot. Internal state, not exposed to clients.
  
 */
export function subscribeAllPositionSnapshots(callback: (data: PositionSnapshotsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("positionSnapshots", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PositionSnapshotsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PositionSnapshots collection at path '${"positionSnapshots"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Backend only (@user.address == @constants.PROJECT_VAULT_ADDRESS). Allows the backend to clean up snapshots for traders no longer tracked.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePositionSnapshots(traderId: string): Promise<boolean> {
  try {
    const succeeded = await set(`positionSnapshots/${traderId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PositionSnapshots: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PositionSnapshots for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePositionSnapshots(traderId: string): DocumentOperation {
  return { path: `positionSnapshots/${traderId}`, document: null };
}

