// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: potContributions/$contributionId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * USDC pot boost contributions for any battle. Anyone can add to the prize pool. Onchain transfer into the battle PDA vault.
 */

export interface PotContributionsRequest {
  battleId: string;
  contributorAddress: AddressType;
  amountMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  note?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PotContributionsResponse {
  battleId: string;
  contributorAddress: string;
  amountMicro: number;
  note?: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PotContributions operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPotContributions(contributionId: string, data?: PotContributionsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `potContributions/${contributionId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal @newData.contributorAddress. amountMicro must be > 0 (micro-USDC, 6 decimals). Onchain hook transfers amountMicro USDC from the contributor's wallet into the battle's PDA vault (same PDA as participant bets, keyed by battleId). The battle-resolver sums all contributions + participant bets to compute the total pot at resolution time. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPotContributions(contributionId: string, data?: PotContributionsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`potContributions/${contributionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PotContributions: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read contribution records.
   (Get Single Item)
 */
export async function getPotContributions(contributionId: string): Promise<PotContributionsResponse | null> {
  try {
    const result = await get(`potContributions/${contributionId}`);
    return result as PotContributionsResponse | null;
  } catch (error) {
    console.error(`Error getting PotContributions: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PotContributions document. (
  Read Operation Details: Public (onchain). Anyone can read contribution records.
  )
 */
export function subscribePotContributions(callback: (data: PotContributionsResponse | null) => void, contributionId: string): Promise<() => Promise<void>> {
  return subscribe(`potContributions/${contributionId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PotContributionsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PotContributions at path '${`potContributions/${contributionId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PotContributions items from collection potContributions
 
  Read Operation Details: Public (onchain). Anyone can read contribution records.
  
 */
export async function getManyPotContributions(filter: string = ""): Promise<PotContributionsResponse[]> {
  try {
    const results = await get("potContributions", { prompt: filter });
    return Array.isArray(results) ? results as PotContributionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PotContributions collection at path 'potContributions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PotContributions collection at potContributions
 
  Read Operation Details: Public (onchain). Anyone can read contribution records.
  
 */
export function subscribeManyPotContributions(callback: (data: PotContributionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("potContributions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PotContributionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PotContributions collection at path '${"potContributions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PotContributions items from collection potContributions
 
  Read Operation Details: Public (onchain). Anyone can read contribution records.
  
 */
export async function getAllPotContributions(filter: string = ""): Promise<PotContributionsResponse[]> {
  try {
    const results = await get("potContributions", { prompt: filter });
    return Array.isArray(results) ? results as PotContributionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PotContributions collection at path 'potContributions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PotContributions collection at potContributions
 
  Read Operation Details: Public (onchain). Anyone can read contribution records.
  
 */
export function subscribeAllPotContributions(callback: (data: PotContributionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("potContributions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PotContributionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PotContributions collection at path '${"potContributions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PotContributions items in collection potContributions.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPotContributions(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("potContributions", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PotContributions at path 'potContributions': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PotContributions items in collection potContributions.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePotContributions(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("potContributions", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PotContributions at path 'potContributions': ${formatError(error)}`);
    return { value: 0 };
  }
}

