// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.204Z
// Collection: promotionClaims/$claimId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Promotion link claims submitted by users. Each claim is reviewed by an admin. On approval, 1000 social and total points are auto-awarded via offchain hooks; on rejection from an approved state, points are deducted.
 */

export interface PromotionClaimsRequest {
  userAddress: AddressType;
  link: string;
  status: string;
  pointsAwarded: number | TimeOperation | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  awarded?: boolean;
}

export interface PromotionClaimsResponse {
  userAddress: string;
  link: string;
  status: string;
  pointsAwarded: number;
  createdAt: number;
  updatedAt: number;
  awarded?: boolean;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PromotionClaims operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPromotionClaims(claimId: string, data: PromotionClaimsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `promotionClaims/${claimId}`, document: doc };
}

/**
 * Backend only. The promotion-claim submission now happens via the vault-signed Cloudflare Worker, so only PROJECT_VAULT_ADDRESS may create a claim. status must be 'pending' and pointsAwarded must be 1000. The backend enforces the 24h resubmit cooldown and the duplicate-link check (against promotionLinkRegistry) in code before writing. $claimId and userAddress remain the user's wallet address so the points-award hook keeps working unchanged. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPromotionClaims(claimId: string, data: PromotionClaimsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`promotionClaims/${claimId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PromotionClaims: ${formatError(error)}`);
    return false;
  }
}

export type PromotionClaimsRequestUpdate = Partial<PromotionClaimsRequest>;

/**
 * Build a PromotionClaims update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePromotionClaims(claimId: string, data: PromotionClaimsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `promotionClaims/${claimId}`, document: doc };
}

/**
 * Two allowed update paths. (1) Backend resubmit: PROJECT_VAULT_ADDRESS (the vault-signed backend) may reset a claim back to status 'pending' to resubmit a new link; the 24h cooldown and duplicate-link check are enforced in backend code, not in the policy rule. userAddress is immutable (Address!). (2) Admin review: ADMIN_ADDRESS may set status to 'approved' or 'rejected' at any time (unchanged). pending->approved awards 1000 socialPoints + 1000 totalPoints, writes a pointsActivity entry, and sets the immutable 'awarded' guard so points can be awarded at most once per wallet. approved->rejected deducts 1000 socialPoints + 1000 totalPoints and writes a cancellation activity entry. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePromotionClaims(claimId: string, data: PromotionClaimsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`promotionClaims/${claimId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PromotionClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Claim owner or admin can read. Users see only their own claims; admin sees all.
   (Get Single Item)
 */
export async function getPromotionClaims(claimId: string): Promise<PromotionClaimsResponse | null> {
  try {
    const result = await get(`promotionClaims/${claimId}`);
    return result as PromotionClaimsResponse | null;
  } catch (error) {
    console.error(`Error getting PromotionClaims: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PromotionClaims document. (
  Read Operation Details: Claim owner or admin can read. Users see only their own claims; admin sees all.
  )
 */
export function subscribePromotionClaims(callback: (data: PromotionClaimsResponse | null) => void, claimId: string): Promise<() => Promise<void>> {
  return subscribe(`promotionClaims/${claimId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PromotionClaimsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PromotionClaims at path '${`promotionClaims/${claimId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PromotionClaims items from collection promotionClaims
 
  Read Operation Details: Claim owner or admin can read. Users see only their own claims; admin sees all.
  
 */
export async function getManyPromotionClaims(filter: string = ""): Promise<PromotionClaimsResponse[]> {
  try {
    const results = await get("promotionClaims", { prompt: filter });
    return Array.isArray(results) ? results as PromotionClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PromotionClaims collection at path 'promotionClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PromotionClaims collection at promotionClaims
 
  Read Operation Details: Claim owner or admin can read. Users see only their own claims; admin sees all.
  
 */
export function subscribeManyPromotionClaims(callback: (data: PromotionClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("promotionClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PromotionClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PromotionClaims collection at path '${"promotionClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PromotionClaims items from collection promotionClaims
 
  Read Operation Details: Claim owner or admin can read. Users see only their own claims; admin sees all.
  
 */
export async function getAllPromotionClaims(filter: string = ""): Promise<PromotionClaimsResponse[]> {
  try {
    const results = await get("promotionClaims", { prompt: filter });
    return Array.isArray(results) ? results as PromotionClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PromotionClaims collection at path 'promotionClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PromotionClaims collection at promotionClaims
 
  Read Operation Details: Claim owner or admin can read. Users see only their own claims; admin sees all.
  
 */
export function subscribeAllPromotionClaims(callback: (data: PromotionClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("promotionClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PromotionClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PromotionClaims collection at path '${"promotionClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Admin only. The admin (ADMIN_ADDRESS) can delete a promotion claim as part of wiping a user's reward data. No hooks run on delete. Rejection (without data wipe) is handled via the update rule by setting status to 'rejected'.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePromotionClaims(claimId: string): Promise<boolean> {
  try {
    const succeeded = await set(`promotionClaims/${claimId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PromotionClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PromotionClaims for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePromotionClaims(claimId: string): DocumentOperation {
  return { path: `promotionClaims/${claimId}`, document: null };
}

