// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.104Z
// Collection: socialClaims/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks one-time social rewards claimed per user (Twitter follow, Telegram join). Document ID is user's wallet address so each user gets exactly one claims record. Honor-system based since X/Telegram don't expose verified-follow data without OAuth.
 */

export interface SocialClaimsRequest {
  address: AddressType;
  twitterFollowClaimed: boolean;
  twitterFollowClaimedAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  telegramJoinClaimed: boolean;
  telegramJoinClaimedAt?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SocialClaimsResponse {
  address: string;
  twitterFollowClaimed: boolean;
  twitterFollowClaimedAt?: number;
  telegramJoinClaimed: boolean;
  telegramJoinClaimedAt?: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a SocialClaims operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSocialClaims(userAddress: string, data: SocialClaimsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `socialClaims/${userAddress}`, document: doc };
}

/**
 * Backend/vault only. The project vault writes claim records after verifying social actions off-chain. Offchain create hook auto-awards 500 socialPoints + 500 totalPoints per claim flag set to true at creation: ensures userPoints/$userAddress exists (creates with zeros if missing via putDocument), increments points per claimed flag using getAfter for staged-state arithmetic, and writes one pointsActivity entry per claim keyed by @time.now (each social reward is approved in a separate admin request at a different time, so @time.now differs naturally between rewards). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSocialClaims(userAddress: string, data: SocialClaimsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`socialClaims/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SocialClaims: ${formatError(error)}`);
    return false;
  }
}

export type SocialClaimsRequestUpdate = Partial<SocialClaimsRequest>;

/**
 * Build a SocialClaims update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSocialClaims(userAddress: string, data: SocialClaimsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `socialClaims/${userAddress}`, document: doc };
}

/**
 * Backend/vault only. Used to flip claim flags from false to true after off-chain verification. Offchain update hook detects flag flips (false → true via `@data.X == true || @newData.X != true` no-op check), ensures userPoints/$userAddress exists, awards 500 totalPoints + 500 socialPoints per newly-flipped flag, and writes one pointsActivity entry per newly-flipped flag keyed by @time.now. Already-true flags do not re-award. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSocialClaims(userAddress: string, data: SocialClaimsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`socialClaims/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating SocialClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Allows displaying claim status publicly.
   (Get Single Item)
 */
export async function getSocialClaims(userAddress: string): Promise<SocialClaimsResponse | null> {
  try {
    const result = await get(`socialClaims/${userAddress}`);
    return result as SocialClaimsResponse | null;
  } catch (error) {
    console.error(`Error getting SocialClaims: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SocialClaims document. (
  Read Operation Details: Anyone can read. Allows displaying claim status publicly.
  )
 */
export function subscribeSocialClaims(callback: (data: SocialClaimsResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`socialClaims/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SocialClaimsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SocialClaims at path '${`socialClaims/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SocialClaims items from collection socialClaims
 
  Read Operation Details: Anyone can read. Allows displaying claim status publicly.
  
 */
export async function getManySocialClaims(filter: string = ""): Promise<SocialClaimsResponse[]> {
  try {
    const results = await get("socialClaims", { prompt: filter });
    return Array.isArray(results) ? results as SocialClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SocialClaims collection at path 'socialClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SocialClaims collection at socialClaims
 
  Read Operation Details: Anyone can read. Allows displaying claim status publicly.
  
 */
export function subscribeManySocialClaims(callback: (data: SocialClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("socialClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SocialClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SocialClaims collection at path '${"socialClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SocialClaims items from collection socialClaims
 
  Read Operation Details: Anyone can read. Allows displaying claim status publicly.
  
 */
export async function getAllSocialClaims(filter: string = ""): Promise<SocialClaimsResponse[]> {
  try {
    const results = await get("socialClaims", { prompt: filter });
    return Array.isArray(results) ? results as SocialClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SocialClaims collection at path 'socialClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SocialClaims collection at socialClaims
 
  Read Operation Details: Anyone can read. Allows displaying claim status publicly.
  
 */
export function subscribeAllSocialClaims(callback: (data: SocialClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("socialClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SocialClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SocialClaims collection at path '${"socialClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SocialClaims items in collection socialClaims.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSocialClaims(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("socialClaims", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SocialClaims at path 'socialClaims': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SocialClaims items in collection socialClaims.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSocialClaims(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("socialClaims", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SocialClaims at path 'socialClaims': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only. The admin (ADMIN_ADDRESS) can delete a user's social claims record for moderation as part of wiping reward data. No hooks run on delete, so points are not affected by the deletion itself.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteSocialClaims(userAddress: string): Promise<boolean> {
  try {
    const succeeded = await set(`socialClaims/${userAddress}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting SocialClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for SocialClaims for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteSocialClaims(userAddress: string): DocumentOperation {
  return { path: `socialClaims/${userAddress}`, document: null };
}

