// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.182Z
// Collection: analysisComments/$commentId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * A comment on an analysis post. Publicly readable; only the author can create, edit, or delete. Queryable by analysisId so the frontend can load all comments for a given analysis.
 */

export interface AnalysisCommentsRequest {
  analysisId: string;
  author: AddressType;
  body: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface AnalysisCommentsResponse {
  analysisId: string;
  author: string;
  body: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a AnalysisComments operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildAnalysisComments(commentId: string, data: AnalysisCommentsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `analysisComments/${commentId}`, document: doc };
}

/**
 * Authenticated users only. The author field must equal @user.address and is immutable (Address!). Frontend sets createdAt to current server time (Unix seconds). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setAnalysisComments(commentId: string, data: AnalysisCommentsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`analysisComments/${commentId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting AnalysisComments: ${formatError(error)}`);
    return false;
  }
}

export type AnalysisCommentsRequestUpdate = Partial<AnalysisCommentsRequest>;

/**
 * Build a AnalysisComments update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateAnalysisComments(commentId: string, data: AnalysisCommentsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `analysisComments/${commentId}`, document: doc };
}

/**
 * Only the original author (@data.author == @user.address) may edit their own comment. The author field cannot be changed (readonly). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateAnalysisComments(commentId: string, data: AnalysisCommentsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`analysisComments/${commentId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating AnalysisComments: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read all comments. Frontend queries comments by analysisId to load the comment thread for a given analysis.
   (Get Single Item)
 */
export async function getAnalysisComments(commentId: string): Promise<AnalysisCommentsResponse | null> {
  try {
    const result = await get(`analysisComments/${commentId}`);
    return result as AnalysisCommentsResponse | null;
  } catch (error) {
    console.error(`Error getting AnalysisComments: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single AnalysisComments document. (
  Read Operation Details: Anyone can read all comments. Frontend queries comments by analysisId to load the comment thread for a given analysis.
  )
 */
export function subscribeAnalysisComments(callback: (data: AnalysisCommentsResponse | null) => void, commentId: string): Promise<() => Promise<void>> {
  return subscribe(`analysisComments/${commentId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as AnalysisCommentsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to AnalysisComments at path '${`analysisComments/${commentId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many AnalysisComments items from collection analysisComments
 
  Read Operation Details: Anyone can read all comments. Frontend queries comments by analysisId to load the comment thread for a given analysis.
  
 */
export async function getManyAnalysisComments(filter: string = ""): Promise<AnalysisCommentsResponse[]> {
  try {
    const results = await get("analysisComments", { prompt: filter });
    return Array.isArray(results) ? results as AnalysisCommentsResponse[] : [];
  } catch (error) {
    console.error(`Error getting AnalysisComments collection at path 'analysisComments': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in AnalysisComments collection at analysisComments
 
  Read Operation Details: Anyone can read all comments. Frontend queries comments by analysisId to load the comment thread for a given analysis.
  
 */
export function subscribeManyAnalysisComments(callback: (data: AnalysisCommentsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("analysisComments", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AnalysisCommentsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to AnalysisComments collection at path '${"analysisComments"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all AnalysisComments items from collection analysisComments
 
  Read Operation Details: Anyone can read all comments. Frontend queries comments by analysisId to load the comment thread for a given analysis.
  
 */
export async function getAllAnalysisComments(filter: string = ""): Promise<AnalysisCommentsResponse[]> {
  try {
    const results = await get("analysisComments", { prompt: filter });
    return Array.isArray(results) ? results as AnalysisCommentsResponse[] : [];
  } catch (error) {
    console.error(`Error getting AnalysisComments collection at path 'analysisComments': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in AnalysisComments collection at analysisComments
 
  Read Operation Details: Anyone can read all comments. Frontend queries comments by analysisId to load the comment thread for a given analysis.
  
 */
export function subscribeAllAnalysisComments(callback: (data: AnalysisCommentsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("analysisComments", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AnalysisCommentsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to AnalysisComments collection at path '${"analysisComments"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count AnalysisComments items in collection analysisComments.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countAnalysisComments(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("analysisComments", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting AnalysisComments at path 'analysisComments': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on AnalysisComments items in collection analysisComments.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateAnalysisComments(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("analysisComments", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating AnalysisComments at path 'analysisComments': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Only the original author (@data.author == @user.address) may delete their own comment.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAnalysisComments(commentId: string): Promise<boolean> {
  try {
    const succeeded = await set(`analysisComments/${commentId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting AnalysisComments: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for AnalysisComments for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteAnalysisComments(commentId: string): DocumentOperation {
  return { path: `analysisComments/${commentId}`, document: null };
}

