// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.182Z
// Collection: analysisVotes/$voteId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * One vote per user per analysis. Frontend keys voteId deterministically as ${analysisId}_${voterAddress} so each user has at most one vote document per analysis. value is 1 (upvote) or -1 (downvote). Queryable by analysisId so the frontend can sum scores.
 */

export interface AnalysisVotesRequest {
  analysisId: string;
  voter: AddressType;
  value: number | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface AnalysisVotesResponse {
  analysisId: string;
  voter: string;
  value: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a AnalysisVotes operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildAnalysisVotes(voteId: string, data: AnalysisVotesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `analysisVotes/${voteId}`, document: doc };
}

/**
 * Authenticated users only. The voter field must equal @user.address and is immutable (Address!). value must be exactly 1 (upvote) or -1 (downvote). Frontend keys the document as ${analysisId}_${voterAddress} so a user can only hold one vote per analysis; re-voting overwrites their own document. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setAnalysisVotes(voteId: string, data: AnalysisVotesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`analysisVotes/${voteId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting AnalysisVotes: ${formatError(error)}`);
    return false;
  }
}

export type AnalysisVotesRequestUpdate = Partial<AnalysisVotesRequest>;

/**
 * Build a AnalysisVotes update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateAnalysisVotes(voteId: string, data: AnalysisVotesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `analysisVotes/${voteId}`, document: doc };
}

/**
 * Only the original voter (@data.voter == @user.address) may change their vote, allowing them to flip between upvote (1) and downvote (-1). value must remain 1 or -1. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateAnalysisVotes(voteId: string, data: AnalysisVotesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`analysisVotes/${voteId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating AnalysisVotes: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read all votes. Frontend queries votes by analysisId and sums value fields to compute each analysis's score.
   (Get Single Item)
 */
export async function getAnalysisVotes(voteId: string): Promise<AnalysisVotesResponse | null> {
  try {
    const result = await get(`analysisVotes/${voteId}`);
    return result as AnalysisVotesResponse | null;
  } catch (error) {
    console.error(`Error getting AnalysisVotes: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single AnalysisVotes document. (
  Read Operation Details: Anyone can read all votes. Frontend queries votes by analysisId and sums value fields to compute each analysis's score.
  )
 */
export function subscribeAnalysisVotes(callback: (data: AnalysisVotesResponse | null) => void, voteId: string): Promise<() => Promise<void>> {
  return subscribe(`analysisVotes/${voteId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as AnalysisVotesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to AnalysisVotes at path '${`analysisVotes/${voteId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many AnalysisVotes items from collection analysisVotes
 
  Read Operation Details: Anyone can read all votes. Frontend queries votes by analysisId and sums value fields to compute each analysis's score.
  
 */
export async function getManyAnalysisVotes(filter: string = ""): Promise<AnalysisVotesResponse[]> {
  try {
    const results = await get("analysisVotes", { prompt: filter });
    return Array.isArray(results) ? results as AnalysisVotesResponse[] : [];
  } catch (error) {
    console.error(`Error getting AnalysisVotes collection at path 'analysisVotes': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in AnalysisVotes collection at analysisVotes
 
  Read Operation Details: Anyone can read all votes. Frontend queries votes by analysisId and sums value fields to compute each analysis's score.
  
 */
export function subscribeManyAnalysisVotes(callback: (data: AnalysisVotesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("analysisVotes", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AnalysisVotesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to AnalysisVotes collection at path '${"analysisVotes"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all AnalysisVotes items from collection analysisVotes
 
  Read Operation Details: Anyone can read all votes. Frontend queries votes by analysisId and sums value fields to compute each analysis's score.
  
 */
export async function getAllAnalysisVotes(filter: string = ""): Promise<AnalysisVotesResponse[]> {
  try {
    const results = await get("analysisVotes", { prompt: filter });
    return Array.isArray(results) ? results as AnalysisVotesResponse[] : [];
  } catch (error) {
    console.error(`Error getting AnalysisVotes collection at path 'analysisVotes': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in AnalysisVotes collection at analysisVotes
 
  Read Operation Details: Anyone can read all votes. Frontend queries votes by analysisId and sums value fields to compute each analysis's score.
  
 */
export function subscribeAllAnalysisVotes(callback: (data: AnalysisVotesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("analysisVotes", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AnalysisVotesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to AnalysisVotes collection at path '${"analysisVotes"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count AnalysisVotes items in collection analysisVotes.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countAnalysisVotes(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("analysisVotes", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting AnalysisVotes at path 'analysisVotes': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on AnalysisVotes items in collection analysisVotes.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateAnalysisVotes(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("analysisVotes", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating AnalysisVotes at path 'analysisVotes': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Only the original voter (@data.voter == @user.address) may delete their vote (un-voting).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAnalysisVotes(voteId: string): Promise<boolean> {
  try {
    const succeeded = await set(`analysisVotes/${voteId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting AnalysisVotes: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for AnalysisVotes for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteAnalysisVotes(voteId: string): DocumentOperation {
  return { path: `analysisVotes/${voteId}`, document: null };
}

