// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.181Z
// Collection: battleParticipants/$participantId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Per-trader join record + USDC escrow into the battle's PDA vault. ONCHAIN — onchain hook locks the bet in a PDA derived from battleId. Frontend builds $participantId as '{battleId}_{wallet}' (use underscores, not hyphens; account IDs allow alphanumeric + underscore/hyphen). Frontend passes equityAtStartMicro by querying perp-api.phoenix.trade for the wallet's current Phoenix equity at the moment of joining — used as the baseline to compute % PnL when the battle ends.
 */

export interface BattleParticipantsRequest {
  battleId: string;
  wallet: AddressType;
  xHandle?: string;
  betAmountMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  equityAtStartMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  joinedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface BattleParticipantsResponse {
  battleId: string;
  wallet: string;
  xHandle?: string;
  betAmountMicro: number;
  equityAtStartMicro: number;
  joinedAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a BattleParticipants operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBattleParticipants(participantId: string, data?: BattleParticipantsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `battleParticipants/${participantId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal @newData.wallet (each participant deposits for themselves). betAmountMicro must be > 0 (micro-USDC, 6 decimals). Onchain hook: (1) @AccountPlugin.createAccount(@newData.battleId) — derives/creates a Program-Derived Address (PDA) keyed by battleId; idempotent so the second participant doesn't fail. (2) @TokenPlugin.transfer moves betAmountMicro USDC from the caller's wallet into the battle's PDA vault. NOTE: betAmountMicro is stored as a field rather than read from the offchain battles collection because onchain hooks cannot read offchain data. The backend is expected to validate (off-policy) that both participants' betAmountMicro match the battle's betAmountMicro before marking the battle 'active'. equityAtStartMicro is the trader's Phoenix equity (6 decimals) at the moment of joining, used as the baseline to compute % PnL at battle end. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBattleParticipants(participantId: string, data?: BattleParticipantsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`battleParticipants/${participantId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting BattleParticipants: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read participant records. UI typically filters by battleId to show both participants of a given battle.
   (Get Single Item)
 */
export async function getBattleParticipants(participantId: string): Promise<BattleParticipantsResponse | null> {
  try {
    const result = await get(`battleParticipants/${participantId}`);
    return result as BattleParticipantsResponse | null;
  } catch (error) {
    console.error(`Error getting BattleParticipants: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single BattleParticipants document. (
  Read Operation Details: Public (onchain). Anyone can read participant records. UI typically filters by battleId to show both participants of a given battle.
  )
 */
export function subscribeBattleParticipants(callback: (data: BattleParticipantsResponse | null) => void, participantId: string): Promise<() => Promise<void>> {
  return subscribe(`battleParticipants/${participantId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BattleParticipantsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to BattleParticipants at path '${`battleParticipants/${participantId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many BattleParticipants items from collection battleParticipants
 
  Read Operation Details: Public (onchain). Anyone can read participant records. UI typically filters by battleId to show both participants of a given battle.
  
 */
export async function getManyBattleParticipants(filter: string = ""): Promise<BattleParticipantsResponse[]> {
  try {
    const results = await get("battleParticipants", { prompt: filter });
    return Array.isArray(results) ? results as BattleParticipantsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleParticipants collection at path 'battleParticipants': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleParticipants collection at battleParticipants
 
  Read Operation Details: Public (onchain). Anyone can read participant records. UI typically filters by battleId to show both participants of a given battle.
  
 */
export function subscribeManyBattleParticipants(callback: (data: BattleParticipantsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleParticipants", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleParticipantsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleParticipants collection at path '${"battleParticipants"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all BattleParticipants items from collection battleParticipants
 
  Read Operation Details: Public (onchain). Anyone can read participant records. UI typically filters by battleId to show both participants of a given battle.
  
 */
export async function getAllBattleParticipants(filter: string = ""): Promise<BattleParticipantsResponse[]> {
  try {
    const results = await get("battleParticipants", { prompt: filter });
    return Array.isArray(results) ? results as BattleParticipantsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleParticipants collection at path 'battleParticipants': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleParticipants collection at battleParticipants
 
  Read Operation Details: Public (onchain). Anyone can read participant records. UI typically filters by battleId to show both participants of a given battle.
  
 */
export function subscribeAllBattleParticipants(callback: (data: BattleParticipantsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleParticipants", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleParticipantsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleParticipants collection at path '${"battleParticipants"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count BattleParticipants items in collection battleParticipants.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBattleParticipants(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("battleParticipants", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting BattleParticipants at path 'battleParticipants': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on BattleParticipants items in collection battleParticipants.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBattleParticipants(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("battleParticipants", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating BattleParticipants at path 'battleParticipants': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin-only (cascade cleanup). Only @constants.ADMIN_ADDRESS can delete, used to clean up the offchain tracking record when an admin deletes a battle. IMPORTANT: deletion does NOT run any onchain hook and does NOT return or move escrowed USDC — funds remain locked in the battle's PDA vault. Admins only delete these for already-settled/refunded or test battles.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteBattleParticipants(participantId: string): Promise<boolean> {
  try {
    const succeeded = await set(`battleParticipants/${participantId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting BattleParticipants: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for BattleParticipants for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteBattleParticipants(participantId: string): DocumentOperation {
  return { path: `battleParticipants/${participantId}`, document: null };
}

