// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.058Z
// Collection: battleClaims/$claimId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Winner claims the prize pot. ONCHAIN — onchain hook splits the total pot (2 * betAmountMicro USDC) between the winner (98%) and the platform/admin (2% fee). $claimId should be the battleId (one claim per battle, prevents double-claim via document uniqueness). NOTE: Because the rule cannot cross-read the offchain battles collection from an onchain rule, claim authorization is gated to PROJECT_VAULT_ADDRESS — the backend verifies the winner (via Phoenix PnL evaluation) and signs the claim on the winner's behalf. The PDA still holds the funds; the program signs the outbound transfers regardless of who initiates.
 */

export interface BattleClaimsRequest {
  battleId: string;
  winner: AddressType;
  betAmountMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  claimedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface BattleClaimsResponse {
  battleId: string;
  winner: string;
  betAmountMicro: number;
  claimedAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a BattleClaims operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBattleClaims(claimId: string, data?: BattleClaimsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `battleClaims/${claimId}`, document: doc };
}

/**
 * Backend-only (PROJECT_VAULT_ADDRESS). The backend determines the winner by querying Phoenix PnL for both participants, updates battles.$battleId.winner, then creates this claim with winner = winning wallet, betAmountMicro = the battle's bet amount, and $claimId = battleId (one claim per battle). Onchain hook performs an ATOMIC two-step transfer from the battle PDA (battleId is the PDA account ID, the program signs for it): (1) transfers 98% of the total pot — (2 * betAmountMicro * 98) / 100 USDC — to @newData.winner, and (2) transfers 2% platform fee — (2 * betAmountMicro * 2) / 100 USDC — to @constants.ADMIN_ADDRESS. Both transfers must succeed (chained with &&) — if either fails the entire claim is rolled back. Integer math: multiply before divide to avoid precision loss (1 micro-USDC rounding error possible on odd pots). Backend should also update battles.status to 'claimed' after this succeeds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBattleClaims(claimId: string, data?: BattleClaimsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`battleClaims/${claimId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting BattleClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read claim records.
   (Get Single Item)
 */
export async function getBattleClaims(claimId: string): Promise<BattleClaimsResponse | null> {
  try {
    const result = await get(`battleClaims/${claimId}`);
    return result as BattleClaimsResponse | null;
  } catch (error) {
    console.error(`Error getting BattleClaims: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single BattleClaims document. (
  Read Operation Details: Public (onchain). Anyone can read claim records.
  )
 */
export function subscribeBattleClaims(callback: (data: BattleClaimsResponse | null) => void, claimId: string): Promise<() => Promise<void>> {
  return subscribe(`battleClaims/${claimId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BattleClaimsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to BattleClaims at path '${`battleClaims/${claimId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many BattleClaims items from collection battleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export async function getManyBattleClaims(filter: string = ""): Promise<BattleClaimsResponse[]> {
  try {
    const results = await get("battleClaims", { prompt: filter });
    return Array.isArray(results) ? results as BattleClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleClaims collection at path 'battleClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleClaims collection at battleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export function subscribeManyBattleClaims(callback: (data: BattleClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleClaims collection at path '${"battleClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all BattleClaims items from collection battleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export async function getAllBattleClaims(filter: string = ""): Promise<BattleClaimsResponse[]> {
  try {
    const results = await get("battleClaims", { prompt: filter });
    return Array.isArray(results) ? results as BattleClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleClaims collection at path 'battleClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleClaims collection at battleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export function subscribeAllBattleClaims(callback: (data: BattleClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleClaims collection at path '${"battleClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count BattleClaims items in collection battleClaims.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBattleClaims(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("battleClaims", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting BattleClaims at path 'battleClaims': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on BattleClaims items in collection battleClaims.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBattleClaims(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("battleClaims", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating BattleClaims at path 'battleClaims': ${formatError(error)}`);
    return { value: 0 };
  }
}

