// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: battleSpectators/$spectatorId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks wallets watching a battle live. Used for spectator count display and watch badges.
 */

export interface BattleSpectatorsRequest {
  battleId: string;
  walletAddress: AddressType;
  joinedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface BattleSpectatorsResponse {
  battleId: string;
  walletAddress: string;
  joinedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a BattleSpectators operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBattleSpectators(spectatorId: string, data?: BattleSpectatorsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `battleSpectators/${spectatorId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal @newData.walletAddress. One spectator record per wallet per battle (use battleId_walletAddress as $spectatorId to enforce uniqueness). No financial component — purely for spectator count and watch badges. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBattleSpectators(spectatorId: string, data?: BattleSpectatorsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`battleSpectators/${spectatorId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting BattleSpectators: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read spectator records. Useful for displaying live spectator counts per battle.
   (Get Single Item)
 */
export async function getBattleSpectators(spectatorId: string): Promise<BattleSpectatorsResponse | null> {
  try {
    const result = await get(`battleSpectators/${spectatorId}`);
    return result as BattleSpectatorsResponse | null;
  } catch (error) {
    console.error(`Error getting BattleSpectators: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single BattleSpectators document. (
  Read Operation Details: Anyone can read spectator records. Useful for displaying live spectator counts per battle.
  )
 */
export function subscribeBattleSpectators(callback: (data: BattleSpectatorsResponse | null) => void, spectatorId: string): Promise<() => Promise<void>> {
  return subscribe(`battleSpectators/${spectatorId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BattleSpectatorsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to BattleSpectators at path '${`battleSpectators/${spectatorId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many BattleSpectators items from collection battleSpectators
 
  Read Operation Details: Anyone can read spectator records. Useful for displaying live spectator counts per battle.
  
 */
export async function getManyBattleSpectators(filter: string = ""): Promise<BattleSpectatorsResponse[]> {
  try {
    const results = await get("battleSpectators", { prompt: filter });
    return Array.isArray(results) ? results as BattleSpectatorsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleSpectators collection at path 'battleSpectators': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleSpectators collection at battleSpectators
 
  Read Operation Details: Anyone can read spectator records. Useful for displaying live spectator counts per battle.
  
 */
export function subscribeManyBattleSpectators(callback: (data: BattleSpectatorsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleSpectators", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleSpectatorsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleSpectators collection at path '${"battleSpectators"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all BattleSpectators items from collection battleSpectators
 
  Read Operation Details: Anyone can read spectator records. Useful for displaying live spectator counts per battle.
  
 */
export async function getAllBattleSpectators(filter: string = ""): Promise<BattleSpectatorsResponse[]> {
  try {
    const results = await get("battleSpectators", { prompt: filter });
    return Array.isArray(results) ? results as BattleSpectatorsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleSpectators collection at path 'battleSpectators': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleSpectators collection at battleSpectators
 
  Read Operation Details: Anyone can read spectator records. Useful for displaying live spectator counts per battle.
  
 */
export function subscribeAllBattleSpectators(callback: (data: BattleSpectatorsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleSpectators", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleSpectatorsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleSpectators collection at path '${"battleSpectators"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count BattleSpectators items in collection battleSpectators.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBattleSpectators(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("battleSpectators", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting BattleSpectators at path 'battleSpectators': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on BattleSpectators items in collection battleSpectators.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBattleSpectators(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("battleSpectators", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating BattleSpectators at path 'battleSpectators': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: A spectator can remove their own record (stop watching), OR @constants.ADMIN_ADDRESS can delete for cascade cleanup when an admin deletes a battle. Offchain spectator tracking, safe to delete.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteBattleSpectators(spectatorId: string): Promise<boolean> {
  try {
    const succeeded = await set(`battleSpectators/${spectatorId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting BattleSpectators: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for BattleSpectators for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteBattleSpectators(spectatorId: string): DocumentOperation {
  return { path: `battleSpectators/${spectatorId}`, document: null };
}

