// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.182Z
// Collection: battleRefunds/$refundId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Royal Rumble participant refund when a rumble is cancelled (insufficient participants). Backend-only. One refund per participant per battle.
 */

export interface BattleRefundsRequest {
  battleId: string;
  wallet: AddressType;
  amountMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  refundedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface BattleRefundsResponse {
  battleId: string;
  wallet: string;
  amountMicro: number;
  refundedAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a BattleRefunds operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBattleRefunds(refundId: string, data?: BattleRefundsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `battleRefunds/${refundId}`, document: doc };
}

/**
 * Backend-only (PROJECT_VAULT_ADDRESS). Created by the battle-resolver when cancelling a Royal Rumble that expired without enough participants. One refund record per participant (ID = {battleId}_{walletAddress}). Onchain hook transfers amountMicro USDC from the battle PDA back to @newData.wallet. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBattleRefunds(refundId: string, data?: BattleRefundsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`battleRefunds/${refundId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting BattleRefunds: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read refund records.
   (Get Single Item)
 */
export async function getBattleRefunds(refundId: string): Promise<BattleRefundsResponse | null> {
  try {
    const result = await get(`battleRefunds/${refundId}`);
    return result as BattleRefundsResponse | null;
  } catch (error) {
    console.error(`Error getting BattleRefunds: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single BattleRefunds document. (
  Read Operation Details: Public (onchain). Anyone can read refund records.
  )
 */
export function subscribeBattleRefunds(callback: (data: BattleRefundsResponse | null) => void, refundId: string): Promise<() => Promise<void>> {
  return subscribe(`battleRefunds/${refundId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BattleRefundsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to BattleRefunds at path '${`battleRefunds/${refundId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many BattleRefunds items from collection battleRefunds
 
  Read Operation Details: Public (onchain). Anyone can read refund records.
  
 */
export async function getManyBattleRefunds(filter: string = ""): Promise<BattleRefundsResponse[]> {
  try {
    const results = await get("battleRefunds", { prompt: filter });
    return Array.isArray(results) ? results as BattleRefundsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleRefunds collection at path 'battleRefunds': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleRefunds collection at battleRefunds
 
  Read Operation Details: Public (onchain). Anyone can read refund records.
  
 */
export function subscribeManyBattleRefunds(callback: (data: BattleRefundsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleRefunds", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleRefundsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleRefunds collection at path '${"battleRefunds"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all BattleRefunds items from collection battleRefunds
 
  Read Operation Details: Public (onchain). Anyone can read refund records.
  
 */
export async function getAllBattleRefunds(filter: string = ""): Promise<BattleRefundsResponse[]> {
  try {
    const results = await get("battleRefunds", { prompt: filter });
    return Array.isArray(results) ? results as BattleRefundsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BattleRefunds collection at path 'battleRefunds': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BattleRefunds collection at battleRefunds
 
  Read Operation Details: Public (onchain). Anyone can read refund records.
  
 */
export function subscribeAllBattleRefunds(callback: (data: BattleRefundsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("battleRefunds", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BattleRefundsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BattleRefunds collection at path '${"battleRefunds"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count BattleRefunds items in collection battleRefunds.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBattleRefunds(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("battleRefunds", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting BattleRefunds at path 'battleRefunds': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on BattleRefunds items in collection battleRefunds.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBattleRefunds(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("battleRefunds", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating BattleRefunds at path 'battleRefunds': ${formatError(error)}`);
    return { value: 0 };
  }
}

