// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: leaderboardPrivacy/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Per-user privacy preference for the public PnL leaderboard. Document ID is the user's own wallet address so each user gets exactly one preference record. When hidePnl is true, the backend Heartbeat task still includes the user on the leaderboard (rank + name preserved) but withholds the real realizedPnlUsdCents value. All fields are freely re-writable (no immutable modifiers) because users toggle this preference repeatedly, which means repeated UPDATEs over the same wallet-keyed doc.
 */

export interface LeaderboardPrivacyRequest {
  hidePnl: boolean;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface LeaderboardPrivacyResponse {
  hidePnl: boolean;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a LeaderboardPrivacy operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildLeaderboardPrivacy(userAddress: string, data: LeaderboardPrivacyRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `leaderboardPrivacy/${userAddress}`, document: doc };
}

/**
 * Authenticated user only, and only for their OWN doc: caller wallet (@user.address) must equal the document key ($userAddress). hidePnl is a required Bool (true = hide my PnL number). updatedAt is a required UInt (Unix seconds). No fields are immutable. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setLeaderboardPrivacy(userAddress: string, data: LeaderboardPrivacyRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`leaderboardPrivacy/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting LeaderboardPrivacy: ${formatError(error)}`);
    return false;
  }
}

export type LeaderboardPrivacyRequestUpdate = Partial<LeaderboardPrivacyRequest>;

/**
 * Build a LeaderboardPrivacy update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateLeaderboardPrivacy(userAddress: string, data: LeaderboardPrivacyRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `leaderboardPrivacy/${userAddress}`, document: doc };
}

/**
 * Owner only: caller wallet must equal the document key ($userAddress). Used to toggle hidePnl on/off repeatedly. All fields are freely re-writable since no field is marked immutable. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateLeaderboardPrivacy(userAddress: string, data: LeaderboardPrivacyRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`leaderboardPrivacy/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating LeaderboardPrivacy: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Must be public so both the leaderboard UI and the backend Heartbeat task can read each user's privacy preference.
   (Get Single Item)
 */
export async function getLeaderboardPrivacy(userAddress: string): Promise<LeaderboardPrivacyResponse | null> {
  try {
    const result = await get(`leaderboardPrivacy/${userAddress}`);
    return result as LeaderboardPrivacyResponse | null;
  } catch (error) {
    console.error(`Error getting LeaderboardPrivacy: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single LeaderboardPrivacy document. (
  Read Operation Details: Anyone can read. Must be public so both the leaderboard UI and the backend Heartbeat task can read each user's privacy preference.
  )
 */
export function subscribeLeaderboardPrivacy(callback: (data: LeaderboardPrivacyResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`leaderboardPrivacy/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as LeaderboardPrivacyResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to LeaderboardPrivacy at path '${`leaderboardPrivacy/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many LeaderboardPrivacy items from collection leaderboardPrivacy
 
  Read Operation Details: Anyone can read. Must be public so both the leaderboard UI and the backend Heartbeat task can read each user's privacy preference.
  
 */
export async function getManyLeaderboardPrivacy(filter: string = ""): Promise<LeaderboardPrivacyResponse[]> {
  try {
    const results = await get("leaderboardPrivacy", { prompt: filter });
    return Array.isArray(results) ? results as LeaderboardPrivacyResponse[] : [];
  } catch (error) {
    console.error(`Error getting LeaderboardPrivacy collection at path 'leaderboardPrivacy': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in LeaderboardPrivacy collection at leaderboardPrivacy
 
  Read Operation Details: Anyone can read. Must be public so both the leaderboard UI and the backend Heartbeat task can read each user's privacy preference.
  
 */
export function subscribeManyLeaderboardPrivacy(callback: (data: LeaderboardPrivacyResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("leaderboardPrivacy", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LeaderboardPrivacyResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to LeaderboardPrivacy collection at path '${"leaderboardPrivacy"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all LeaderboardPrivacy items from collection leaderboardPrivacy
 
  Read Operation Details: Anyone can read. Must be public so both the leaderboard UI and the backend Heartbeat task can read each user's privacy preference.
  
 */
export async function getAllLeaderboardPrivacy(filter: string = ""): Promise<LeaderboardPrivacyResponse[]> {
  try {
    const results = await get("leaderboardPrivacy", { prompt: filter });
    return Array.isArray(results) ? results as LeaderboardPrivacyResponse[] : [];
  } catch (error) {
    console.error(`Error getting LeaderboardPrivacy collection at path 'leaderboardPrivacy': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in LeaderboardPrivacy collection at leaderboardPrivacy
 
  Read Operation Details: Anyone can read. Must be public so both the leaderboard UI and the backend Heartbeat task can read each user's privacy preference.
  
 */
export function subscribeAllLeaderboardPrivacy(callback: (data: LeaderboardPrivacyResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("leaderboardPrivacy", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LeaderboardPrivacyResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to LeaderboardPrivacy collection at path '${"leaderboardPrivacy"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count LeaderboardPrivacy items in collection leaderboardPrivacy.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countLeaderboardPrivacy(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("leaderboardPrivacy", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting LeaderboardPrivacy at path 'leaderboardPrivacy': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on LeaderboardPrivacy items in collection leaderboardPrivacy.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateLeaderboardPrivacy(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("leaderboardPrivacy", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating LeaderboardPrivacy at path 'leaderboardPrivacy': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Owner only, or the backend vault (PROJECT_VAULT_ADDRESS) for cleanup. Removing the doc reverts the user to the default (PnL shown).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteLeaderboardPrivacy(userAddress: string): Promise<boolean> {
  try {
    const succeeded = await set(`leaderboardPrivacy/${userAddress}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting LeaderboardPrivacy: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for LeaderboardPrivacy for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteLeaderboardPrivacy(userAddress: string): DocumentOperation {
  return { path: `leaderboardPrivacy/${userAddress}`, document: null };
}

