// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: monthlyRewardDeposit/$depositId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin deposits one token into a given calendar month's prize pot PDA. ONCHAIN passthrough — each deposit is its own immutable record; the onchain hook creates/keys a PDA by potAccountId and transfers the token INTO it. Admin may deposit multiple times and multiple distinct tokens into the same month (same potAccountId). Frontend builds $depositId as '{potAccountId}_{timestamp}' (underscores only). monthKey uses UNDERSCORE format e.g. '2026_06'. potAccountId is deterministic from monthKey e.g. 'monthlyPot_2026_06' (alphanumeric + underscore only — safe as an AccountPlugin account id). mint = @constants.SOL for native test-SOL, or any SPL mint address. amount is in that token's base units (lamports for SOL, micro-units for SPL).
 */

export interface MonthlyRewardDepositRequest {
  monthKey: string;
  potAccountId: string;
  mint: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  depositor: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MonthlyRewardDepositResponse {
  monthKey: string;
  potAccountId: string;
  mint: string;
  amount: number;
  depositor: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a MonthlyRewardDeposit operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMonthlyRewardDeposit(depositId: string, data?: MonthlyRewardDepositRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `monthlyRewardDeposit/${depositId}`, document: doc };
}

/**
 * Admin-only (@constants.ADMIN_ADDRESS). depositor must equal the caller, amount > 0. Onchain hook: (1) @AccountPlugin.createAccount(@newData.potAccountId) idempotently derives/creates the PDA vault keyed by potAccountId (deterministic from monthKey). (2) @TokenPlugin.transfer moves `amount` base units of `mint` from the admin into that PDA. Pass @constants.SOL as mint for native test-SOL deposits. Multiple deposits (different mints / repeated) accumulate in the SAME PDA because potAccountId is identical across a month. CAP: keep distinct mints per month <= MONTHLY_REWARD_MAX_TOKENS (5) — enforced off-policy by the deposit UI so the fixed-slot finalization can represent every token. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMonthlyRewardDeposit(depositId: string, data?: MonthlyRewardDepositRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`monthlyRewardDeposit/${depositId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting MonthlyRewardDeposit: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read deposit records. UI sums deposits by potAccountId+mint to show the current pot composition per month.
   (Get Single Item)
 */
export async function getMonthlyRewardDeposit(depositId: string): Promise<MonthlyRewardDepositResponse | null> {
  try {
    const result = await get(`monthlyRewardDeposit/${depositId}`);
    return result as MonthlyRewardDepositResponse | null;
  } catch (error) {
    console.error(`Error getting MonthlyRewardDeposit: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single MonthlyRewardDeposit document. (
  Read Operation Details: Public (onchain). Anyone can read deposit records. UI sums deposits by potAccountId+mint to show the current pot composition per month.
  )
 */
export function subscribeMonthlyRewardDeposit(callback: (data: MonthlyRewardDepositResponse | null) => void, depositId: string): Promise<() => Promise<void>> {
  return subscribe(`monthlyRewardDeposit/${depositId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MonthlyRewardDepositResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to MonthlyRewardDeposit at path '${`monthlyRewardDeposit/${depositId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many MonthlyRewardDeposit items from collection monthlyRewardDeposit
 
  Read Operation Details: Public (onchain). Anyone can read deposit records. UI sums deposits by potAccountId+mint to show the current pot composition per month.
  
 */
export async function getManyMonthlyRewardDeposit(filter: string = ""): Promise<MonthlyRewardDepositResponse[]> {
  try {
    const results = await get("monthlyRewardDeposit", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardDepositResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardDeposit collection at path 'monthlyRewardDeposit': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardDeposit collection at monthlyRewardDeposit
 
  Read Operation Details: Public (onchain). Anyone can read deposit records. UI sums deposits by potAccountId+mint to show the current pot composition per month.
  
 */
export function subscribeManyMonthlyRewardDeposit(callback: (data: MonthlyRewardDepositResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardDeposit", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardDepositResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardDeposit collection at path '${"monthlyRewardDeposit"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all MonthlyRewardDeposit items from collection monthlyRewardDeposit
 
  Read Operation Details: Public (onchain). Anyone can read deposit records. UI sums deposits by potAccountId+mint to show the current pot composition per month.
  
 */
export async function getAllMonthlyRewardDeposit(filter: string = ""): Promise<MonthlyRewardDepositResponse[]> {
  try {
    const results = await get("monthlyRewardDeposit", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardDepositResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardDeposit collection at path 'monthlyRewardDeposit': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardDeposit collection at monthlyRewardDeposit
 
  Read Operation Details: Public (onchain). Anyone can read deposit records. UI sums deposits by potAccountId+mint to show the current pot composition per month.
  
 */
export function subscribeAllMonthlyRewardDeposit(callback: (data: MonthlyRewardDepositResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardDeposit", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardDepositResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardDeposit collection at path '${"monthlyRewardDeposit"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count MonthlyRewardDeposit items in collection monthlyRewardDeposit.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countMonthlyRewardDeposit(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("monthlyRewardDeposit", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting MonthlyRewardDeposit at path 'monthlyRewardDeposit': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on MonthlyRewardDeposit items in collection monthlyRewardDeposit.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateMonthlyRewardDeposit(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("monthlyRewardDeposit", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating MonthlyRewardDeposit at path 'monthlyRewardDeposit': ${formatError(error)}`);
    return { value: 0 };
  }
}

/** Arguments accepted by the "getPotVaultAddress" query on MonthlyRewardDeposit. */
interface MonthlyRewardDepositGetPotVaultAddressArgs {
  potAccountId: string;
}

/**
 * Runs the "getPotVaultAddress" query on MonthlyRewardDeposit.
 * Query Logic: @AccountPlugin.getAccountAddress(@newData.potAccountId)
 */
export async function runGetPotVaultAddressQueryForMonthlyRewardDeposit(depositId: string, args: MonthlyRewardDepositGetPotVaultAddressArgs): Promise<string> {
  try {
    const result = await runQuery(`monthlyRewardDeposit/${depositId}`, "getPotVaultAddress", args);
    return result as string;
  } catch (error) {
    console.error(`Error running query "getPotVaultAddress" on MonthlyRewardDeposit: ${formatError(error)}`);
    throw error;
  }
}

