// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.182Z
// Collection: monthlyRewardWinners/$monthKey
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * OFFCHAIN. Backend Heartbeat writes ONE doc per finalized month (document id = monthKey, e.g. '2026_06'). Snapshot of the finalized result for display: the 3 winner addresses and the pot composition at finalization (up to 5 token slots, each with mint + total base-unit amount in the pot). The per-winner split amounts that actually authorize on-chain payouts live in monthlyRewardAllotment (onchain), because onchain claim hooks cannot read this offchain doc.
 */

export interface MonthlyRewardWinnersRequest {
  monthKey: string;
  potAccountId: string;
  winner1: AddressType;
  winner2: AddressType;
  winner3: AddressType;
  tokenCount: number | TimeOperation | IncrementOperation | TokenAmount;
  mint1?: AddressType;
  total1?: number | TimeOperation | IncrementOperation | TokenAmount;
  mint2?: AddressType;
  total2?: number | TimeOperation | IncrementOperation | TokenAmount;
  mint3?: AddressType;
  total3?: number | TimeOperation | IncrementOperation | TokenAmount;
  mint4?: AddressType;
  total4?: number | TimeOperation | IncrementOperation | TokenAmount;
  mint5?: AddressType;
  total5?: number | TimeOperation | IncrementOperation | TokenAmount;
  finalizedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MonthlyRewardWinnersResponse {
  monthKey: string;
  potAccountId: string;
  winner1: string;
  winner2: string;
  winner3: string;
  tokenCount: number;
  mint1?: string;
  total1?: number;
  mint2?: string;
  total2?: number;
  mint3?: string;
  total3?: number;
  mint4?: string;
  total4?: number;
  mint5?: string;
  total5?: number;
  finalizedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a MonthlyRewardWinners operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMonthlyRewardWinners(monthKey: string, data?: MonthlyRewardWinnersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `monthlyRewardWinners/${monthKey}`, document: doc };
}

/**
 * Backend Heartbeat only (PROJECT_VAULT_ADDRESS). Written once when a month is finalized. Stores the 3 winner wallets, potAccountId, tokenCount (1..5), and up to 5 (mint, total) pairs describing the pot at finalization. totalN base units are the FULL pot amount for slot N (not yet split). Display-only; authorization for payout lives in monthlyRewardAllotment. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMonthlyRewardWinners(monthKey: string, data?: MonthlyRewardWinnersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`monthlyRewardWinners/${monthKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting MonthlyRewardWinners: ${formatError(error)}`);
    return false;
  }
}

export type MonthlyRewardWinnersRequestUpdate = Partial<MonthlyRewardWinnersRequest>;

/**
 * Build a MonthlyRewardWinners update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateMonthlyRewardWinners(monthKey: string, data: MonthlyRewardWinnersRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `monthlyRewardWinners/${monthKey}`, document: doc };
}

/**
 * Backend only (PROJECT_VAULT_ADDRESS). Allows correcting a finalization snapshot before claims are processed. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateMonthlyRewardWinners(monthKey: string, data: MonthlyRewardWinnersRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`monthlyRewardWinners/${monthKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating MonthlyRewardWinners: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public. Anyone can read the finalized monthly results and pot composition for display.
   (Get Single Item)
 */
export async function getMonthlyRewardWinners(monthKey: string): Promise<MonthlyRewardWinnersResponse | null> {
  try {
    const result = await get(`monthlyRewardWinners/${monthKey}`);
    return result as MonthlyRewardWinnersResponse | null;
  } catch (error) {
    console.error(`Error getting MonthlyRewardWinners: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single MonthlyRewardWinners document. (
  Read Operation Details: Public. Anyone can read the finalized monthly results and pot composition for display.
  )
 */
export function subscribeMonthlyRewardWinners(callback: (data: MonthlyRewardWinnersResponse | null) => void, monthKey: string): Promise<() => Promise<void>> {
  return subscribe(`monthlyRewardWinners/${monthKey}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MonthlyRewardWinnersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to MonthlyRewardWinners at path '${`monthlyRewardWinners/${monthKey}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many MonthlyRewardWinners items from collection monthlyRewardWinners
 
  Read Operation Details: Public. Anyone can read the finalized monthly results and pot composition for display.
  
 */
export async function getManyMonthlyRewardWinners(filter: string = ""): Promise<MonthlyRewardWinnersResponse[]> {
  try {
    const results = await get("monthlyRewardWinners", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardWinnersResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardWinners collection at path 'monthlyRewardWinners': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardWinners collection at monthlyRewardWinners
 
  Read Operation Details: Public. Anyone can read the finalized monthly results and pot composition for display.
  
 */
export function subscribeManyMonthlyRewardWinners(callback: (data: MonthlyRewardWinnersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardWinners", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardWinnersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardWinners collection at path '${"monthlyRewardWinners"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all MonthlyRewardWinners items from collection monthlyRewardWinners
 
  Read Operation Details: Public. Anyone can read the finalized monthly results and pot composition for display.
  
 */
export async function getAllMonthlyRewardWinners(filter: string = ""): Promise<MonthlyRewardWinnersResponse[]> {
  try {
    const results = await get("monthlyRewardWinners", { prompt: filter });
    return Array.isArray(results) ? results as MonthlyRewardWinnersResponse[] : [];
  } catch (error) {
    console.error(`Error getting MonthlyRewardWinners collection at path 'monthlyRewardWinners': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MonthlyRewardWinners collection at monthlyRewardWinners
 
  Read Operation Details: Public. Anyone can read the finalized monthly results and pot composition for display.
  
 */
export function subscribeAllMonthlyRewardWinners(callback: (data: MonthlyRewardWinnersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("monthlyRewardWinners", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MonthlyRewardWinnersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MonthlyRewardWinners collection at path '${"monthlyRewardWinners"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count MonthlyRewardWinners items in collection monthlyRewardWinners.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countMonthlyRewardWinners(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("monthlyRewardWinners", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting MonthlyRewardWinners at path 'monthlyRewardWinners': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on MonthlyRewardWinners items in collection monthlyRewardWinners.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateMonthlyRewardWinners(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("monthlyRewardWinners", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating MonthlyRewardWinners at path 'monthlyRewardWinners': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Backend only (PROJECT_VAULT_ADDRESS). For cleanup of test/erroneous finalizations.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteMonthlyRewardWinners(monthKey: string): Promise<boolean> {
  try {
    const succeeded = await set(`monthlyRewardWinners/${monthKey}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting MonthlyRewardWinners: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for MonthlyRewardWinners for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteMonthlyRewardWinners(monthKey: string): DocumentOperation {
  return { path: `monthlyRewardWinners/${monthKey}`, document: null };
}

