// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: pendingSocialClaims/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Queue for social reward claims awaiting admin approval. Users write their intention to claim Twitter follow or Telegram join rewards here. An admin/backend then reviews and approves by writing to the privileged socialClaims collection, which triggers point-award hooks.
 */

export interface PendingSocialClaimsRequest {
  address: AddressType;
  twitterFollowPending: boolean;
  twitterFollowRequestedAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  telegramJoinPending: boolean;
  telegramJoinRequestedAt?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PendingSocialClaimsResponse {
  address: string;
  twitterFollowPending: boolean;
  twitterFollowRequestedAt?: number;
  telegramJoinPending: boolean;
  telegramJoinRequestedAt?: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PendingSocialClaims operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPendingSocialClaims(userAddress: string, data: PendingSocialClaimsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `pendingSocialClaims/${userAddress}`, document: doc };
}

/**
 * Owner or backend vault can create. Backend creates on behalf of users via the POST /api/social/claim/twitter and /telegram API routes. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPendingSocialClaims(userAddress: string, data: PendingSocialClaimsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`pendingSocialClaims/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PendingSocialClaims: ${formatError(error)}`);
    return false;
  }
}

export type PendingSocialClaimsRequestUpdate = Partial<PendingSocialClaimsRequest>;

/**
 * Build a PendingSocialClaims update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePendingSocialClaims(userAddress: string, data: PendingSocialClaimsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `pendingSocialClaims/${userAddress}`, document: doc };
}

/**
 * Owner, backend vault, or admin can update. Owner updates their own pending claim record; backend vault for administrative purposes. Admin can reject a pending social claim by clearing its pending flags (twitterFollowPending / telegramJoinPending to false) without awarding points — this collection has NO hooks, so clearing flags has no point side-effects (reject = no points; user can re-submit). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePendingSocialClaims(userAddress: string, data: PendingSocialClaimsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`pendingSocialClaims/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PendingSocialClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Admin, backend vault, and the document owner can read. Owner needs to see their pending status on the Rewards page.
   (Get Single Item)
 */
export async function getPendingSocialClaims(userAddress: string): Promise<PendingSocialClaimsResponse | null> {
  try {
    const result = await get(`pendingSocialClaims/${userAddress}`);
    return result as PendingSocialClaimsResponse | null;
  } catch (error) {
    console.error(`Error getting PendingSocialClaims: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PendingSocialClaims document. (
  Read Operation Details: Admin, backend vault, and the document owner can read. Owner needs to see their pending status on the Rewards page.
  )
 */
export function subscribePendingSocialClaims(callback: (data: PendingSocialClaimsResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`pendingSocialClaims/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PendingSocialClaimsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PendingSocialClaims at path '${`pendingSocialClaims/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PendingSocialClaims items from collection pendingSocialClaims
 
  Read Operation Details: Admin, backend vault, and the document owner can read. Owner needs to see their pending status on the Rewards page.
  
 */
export async function getManyPendingSocialClaims(filter: string = ""): Promise<PendingSocialClaimsResponse[]> {
  try {
    const results = await get("pendingSocialClaims", { prompt: filter });
    return Array.isArray(results) ? results as PendingSocialClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PendingSocialClaims collection at path 'pendingSocialClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PendingSocialClaims collection at pendingSocialClaims
 
  Read Operation Details: Admin, backend vault, and the document owner can read. Owner needs to see their pending status on the Rewards page.
  
 */
export function subscribeManyPendingSocialClaims(callback: (data: PendingSocialClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("pendingSocialClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PendingSocialClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PendingSocialClaims collection at path '${"pendingSocialClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PendingSocialClaims items from collection pendingSocialClaims
 
  Read Operation Details: Admin, backend vault, and the document owner can read. Owner needs to see their pending status on the Rewards page.
  
 */
export async function getAllPendingSocialClaims(filter: string = ""): Promise<PendingSocialClaimsResponse[]> {
  try {
    const results = await get("pendingSocialClaims", { prompt: filter });
    return Array.isArray(results) ? results as PendingSocialClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PendingSocialClaims collection at path 'pendingSocialClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PendingSocialClaims collection at pendingSocialClaims
 
  Read Operation Details: Admin, backend vault, and the document owner can read. Owner needs to see their pending status on the Rewards page.
  
 */
export function subscribeAllPendingSocialClaims(callback: (data: PendingSocialClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("pendingSocialClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PendingSocialClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PendingSocialClaims collection at path '${"pendingSocialClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Admin only. The admin (ADMIN_ADDRESS) can delete a user's pending claim record as part of wiping all reward data.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePendingSocialClaims(userAddress: string): Promise<boolean> {
  try {
    const succeeded = await set(`pendingSocialClaims/${userAddress}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PendingSocialClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PendingSocialClaims for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePendingSocialClaims(userAddress: string): DocumentOperation {
  return { path: `pendingSocialClaims/${userAddress}`, document: null };
}

