// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.181Z
// Collection: phoenixWithdraw/$withdrawId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Withdraw Phoenix margin back to USDC (margin -> PhUSD -> USDC). Transient onchain action — no permanent state stored.
 */

export interface PhoenixWithdrawRequest {
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixWithdrawResponse {
  amt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixWithdraw operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixWithdraw(withdrawId: string, data?: PhoenixWithdrawRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixWithdraw/${withdrawId}`, document: doc };
}

/**
 * Authenticated users only. Withdraws Phoenix margin back to USDC for the caller. Chains withdrawFunds (margin -> PhUSD) and emberWithdraw (PhUSD -> USDC). Fails if open positions require the margin (all-or-nothing). `amt` is in PhUSD/USDC smallest units (6 decimals). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixWithdraw(withdrawId: string, data?: PhoenixWithdrawRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixWithdraw/${withdrawId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixWithdraw: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
   (Get Single Item)
 */
export async function getPhoenixWithdraw(withdrawId: string): Promise<PhoenixWithdrawResponse | null> {
  try {
    const result = await get(`phoenixWithdraw/${withdrawId}`);
    return result as PhoenixWithdrawResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixWithdraw: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixWithdraw document. (
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  )
 */
export function subscribePhoenixWithdraw(callback: (data: PhoenixWithdrawResponse | null) => void, withdrawId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixWithdraw/${withdrawId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixWithdrawResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixWithdraw at path '${`phoenixWithdraw/${withdrawId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixWithdraw items from collection phoenixWithdraw
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getManyPhoenixWithdraw(filter: string = ""): Promise<PhoenixWithdrawResponse[]> {
  try {
    const results = await get("phoenixWithdraw", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixWithdrawResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixWithdraw collection at path 'phoenixWithdraw': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixWithdraw collection at phoenixWithdraw
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeManyPhoenixWithdraw(callback: (data: PhoenixWithdrawResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixWithdraw", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixWithdrawResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixWithdraw collection at path '${"phoenixWithdraw"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixWithdraw items from collection phoenixWithdraw
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getAllPhoenixWithdraw(filter: string = ""): Promise<PhoenixWithdrawResponse[]> {
  try {
    const results = await get("phoenixWithdraw", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixWithdrawResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixWithdraw collection at path 'phoenixWithdraw': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixWithdraw collection at phoenixWithdraw
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeAllPhoenixWithdraw(callback: (data: PhoenixWithdrawResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixWithdraw", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixWithdrawResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixWithdraw collection at path '${"phoenixWithdraw"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixWithdraw items in collection phoenixWithdraw.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixWithdraw(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixWithdraw", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixWithdraw at path 'phoenixWithdraw': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixWithdraw items in collection phoenixWithdraw.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixWithdraw(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixWithdraw", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixWithdraw at path 'phoenixWithdraw': ${formatError(error)}`);
    return { value: 0 };
  }
}

