// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.058Z
// Collection: phoenixIsolatedRegister/$registerId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Register and sync an isolated subaccount on Phoenix Perps. Bootstrap step before isolated trading.
 */

export interface PhoenixIsolatedRegisterRequest {
  subaccountIndex: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixIsolatedRegisterResponse {
  subaccountIndex: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixIsolatedRegister operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixIsolatedRegister(registerId: string, data?: PhoenixIsolatedRegisterRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixIsolatedRegister/${registerId}`, document: doc };
}

/**
 * Authenticated users only. Registers an isolated subaccount for the caller via @PhoenixPerpsPlugin.registerTrader(wallet, subaccountIndex) and then syncs parent-to-child capabilities via syncParentToChild(wallet, subaccountIndex). subaccountIndex must be > 0. User must already have collateral in cross-margin before this step. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixIsolatedRegister(registerId: string, data?: PhoenixIsolatedRegisterRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixIsolatedRegister/${registerId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixIsolatedRegister: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
   (Get Single Item)
 */
export async function getPhoenixIsolatedRegister(registerId: string): Promise<PhoenixIsolatedRegisterResponse | null> {
  try {
    const result = await get(`phoenixIsolatedRegister/${registerId}`);
    return result as PhoenixIsolatedRegisterResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedRegister: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixIsolatedRegister document. (
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  )
 */
export function subscribePhoenixIsolatedRegister(callback: (data: PhoenixIsolatedRegisterResponse | null) => void, registerId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixIsolatedRegister/${registerId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixIsolatedRegisterResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixIsolatedRegister at path '${`phoenixIsolatedRegister/${registerId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixIsolatedRegister items from collection phoenixIsolatedRegister
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getManyPhoenixIsolatedRegister(filter: string = ""): Promise<PhoenixIsolatedRegisterResponse[]> {
  try {
    const results = await get("phoenixIsolatedRegister", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsolatedRegisterResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedRegister collection at path 'phoenixIsolatedRegister': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsolatedRegister collection at phoenixIsolatedRegister
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeManyPhoenixIsolatedRegister(callback: (data: PhoenixIsolatedRegisterResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsolatedRegister", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsolatedRegisterResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsolatedRegister collection at path '${"phoenixIsolatedRegister"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixIsolatedRegister items from collection phoenixIsolatedRegister
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getAllPhoenixIsolatedRegister(filter: string = ""): Promise<PhoenixIsolatedRegisterResponse[]> {
  try {
    const results = await get("phoenixIsolatedRegister", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsolatedRegisterResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsolatedRegister collection at path 'phoenixIsolatedRegister': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsolatedRegister collection at phoenixIsolatedRegister
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeAllPhoenixIsolatedRegister(callback: (data: PhoenixIsolatedRegisterResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsolatedRegister", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsolatedRegisterResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsolatedRegister collection at path '${"phoenixIsolatedRegister"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixIsolatedRegister items in collection phoenixIsolatedRegister.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixIsolatedRegister(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixIsolatedRegister", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixIsolatedRegister at path 'phoenixIsolatedRegister': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixIsolatedRegister items in collection phoenixIsolatedRegister.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixIsolatedRegister(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixIsolatedRegister", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixIsolatedRegister at path 'phoenixIsolatedRegister': ${formatError(error)}`);
    return { value: 0 };
  }
}

