// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.182Z
// Collection: phoenixTradeRecord/$recordId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Offchain record of a completed Phoenix perps trade, written ONLY by the backend (PROJECT_VAULT_ADDRESS) AFTER it verifies the on-chain order tx (placed via the Rise Flight SDK on the frontend) actually confirmed. Mirrors the legacy onchain phoenixOrder fields so the UI can render identical order history, plus the on-chain tx signature and a timestamp. On create, the offchain hook awards trading points ($1 of notional sizeUsd = 1 point) and appends a pointsActivity entry — replicating the points logic that previously lived in phoenixOrder's offchain create hook. Users cannot self-write these records, preventing points farming.
 */

export interface PhoenixTradeRecordRequest {
  trader: AddressType;
  market: AddressType;
  symbol: string;
  side: string;
  sizeBaseLots: number | TimeOperation | IncrementOperation | TokenAmount;
  leverage: number | TimeOperation | IncrementOperation | TokenAmount;
  orderType: string;
  limitPrice?: number | TimeOperation | IncrementOperation | TokenAmount;
  stopLoss?: number | TimeOperation | IncrementOperation | TokenAmount;
  takeProfit?: number | TimeOperation | IncrementOperation | TokenAmount;
  subaccountIndex: number | TimeOperation | IncrementOperation | TokenAmount;
  sizeUsd: number | TimeOperation | IncrementOperation | TokenAmount;
  txSignature: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixTradeRecordResponse {
  trader: string;
  market: string;
  symbol: string;
  side: string;
  sizeBaseLots: number;
  leverage: number;
  orderType: string;
  limitPrice?: number;
  stopLoss?: number;
  takeProfit?: number;
  subaccountIndex: number;
  sizeUsd: number;
  txSignature: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PhoenixTradeRecord operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixTradeRecord(recordId: string, data?: PhoenixTradeRecordRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixTradeRecord/${recordId}`, document: doc };
}

/**
 * ONLY the backend vault (PROJECT_VAULT_ADDRESS) can create — enforced by @user.address == @constants.PROJECT_VAULT_ADDRESS. The backend writes this record only AFTER verifying the on-chain Phoenix order tx (placed via the Rise Flight SDK on the frontend) actually confirmed, then includes txSignature. Users CANNOT self-write records, preventing points farming. On create, the offchain hook awards trading points equal to sizeUsd (notional USD, $1 = 1 point): it increments tradingPoints/totalPoints on the existing /userPoints/{trader} document or creates it if missing, updates updatedAt, and appends a /pointsActivity entry keyed by @time.now. sizeUsd MUST be the floor of the notional USD value. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixTradeRecord(recordId: string, data?: PhoenixTradeRecordRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixTradeRecord/${recordId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixTradeRecord: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read (order history is public, same as phoenixOrder). UI typically filters by @data.trader == current wallet to show that user's order history.
   (Get Single Item)
 */
export async function getPhoenixTradeRecord(recordId: string): Promise<PhoenixTradeRecordResponse | null> {
  try {
    const result = await get(`phoenixTradeRecord/${recordId}`);
    return result as PhoenixTradeRecordResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixTradeRecord: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixTradeRecord document. (
  Read Operation Details: Anyone can read (order history is public, same as phoenixOrder). UI typically filters by @data.trader == current wallet to show that user's order history.
  )
 */
export function subscribePhoenixTradeRecord(callback: (data: PhoenixTradeRecordResponse | null) => void, recordId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixTradeRecord/${recordId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixTradeRecordResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixTradeRecord at path '${`phoenixTradeRecord/${recordId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixTradeRecord items from collection phoenixTradeRecord
 
  Read Operation Details: Anyone can read (order history is public, same as phoenixOrder). UI typically filters by @data.trader == current wallet to show that user's order history.
  
 */
export async function getManyPhoenixTradeRecord(filter: string = ""): Promise<PhoenixTradeRecordResponse[]> {
  try {
    const results = await get("phoenixTradeRecord", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixTradeRecordResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixTradeRecord collection at path 'phoenixTradeRecord': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixTradeRecord collection at phoenixTradeRecord
 
  Read Operation Details: Anyone can read (order history is public, same as phoenixOrder). UI typically filters by @data.trader == current wallet to show that user's order history.
  
 */
export function subscribeManyPhoenixTradeRecord(callback: (data: PhoenixTradeRecordResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixTradeRecord", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixTradeRecordResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixTradeRecord collection at path '${"phoenixTradeRecord"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixTradeRecord items from collection phoenixTradeRecord
 
  Read Operation Details: Anyone can read (order history is public, same as phoenixOrder). UI typically filters by @data.trader == current wallet to show that user's order history.
  
 */
export async function getAllPhoenixTradeRecord(filter: string = ""): Promise<PhoenixTradeRecordResponse[]> {
  try {
    const results = await get("phoenixTradeRecord", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixTradeRecordResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixTradeRecord collection at path 'phoenixTradeRecord': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixTradeRecord collection at phoenixTradeRecord
 
  Read Operation Details: Anyone can read (order history is public, same as phoenixOrder). UI typically filters by @data.trader == current wallet to show that user's order history.
  
 */
export function subscribeAllPhoenixTradeRecord(callback: (data: PhoenixTradeRecordResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixTradeRecord", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixTradeRecordResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixTradeRecord collection at path '${"phoenixTradeRecord"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixTradeRecord items in collection phoenixTradeRecord.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixTradeRecord(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixTradeRecord", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixTradeRecord at path 'phoenixTradeRecord': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixTradeRecord items in collection phoenixTradeRecord.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixTradeRecord(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixTradeRecord", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixTradeRecord at path 'phoenixTradeRecord': ${formatError(error)}`);
    return { value: 0 };
  }
}

