// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: phoenixIsoTrade/$tradeId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Atomic isolated-margin order entry. A single onchain CREATE hook bundles registerTrader + syncParentToChild + transferToIsolated + placeLong/placeShort in one Phoenix CPI transaction, so RiskView always evaluates the order AFTER the transferred collateral has landed in the isolated subaccount. Replaces the old multi-tx flow (phoenixIsolatedRegister -> phoenixSubaccount sync -> phoenixIsolatedTransfer -> phoenixOrder + 120s polling). Passthrough: stores only the fields needed to drive the hook and let the frontend read back the result (notably tarobase_transaction_hash). Trading points ARE awarded directly by this collection's own offchain CREATE hook: it increments the trader's tradingPoints (and totalPoints) in userPoints by the trade's USD size (sizeUsd) and writes a pointsActivity record. Isolated-margin trades do NOT go through the phoenixTradeRecord collection at all. Cross-margin trading continues to use phoenixOrder unchanged.
 */

export interface PhoenixIsoTradeRequest {
  trader: AddressType;
  market: AddressType;
  symbol: string;
  side: string;
  sizeBaseLots: number | TimeOperation | IncrementOperation | TokenAmount;
  leverage: number | TimeOperation | IncrementOperation | TokenAmount;
  subaccountIndex: number | TimeOperation | IncrementOperation | TokenAmount;
  transferAmt: number | TimeOperation | IncrementOperation | TokenAmount;
  sizeUsd: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PhoenixIsoTradeResponse {
  trader: string;
  market: string;
  symbol: string;
  side: string;
  sizeBaseLots: number;
  leverage: number;
  subaccountIndex: number;
  transferAmt: number;
  sizeUsd: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PhoenixIsoTrade operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPhoenixIsoTrade(tradeId: string, data?: PhoenixIsoTradeRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `phoenixIsoTrade/${tradeId}`, document: doc };
}

/**
 * Authenticated users only. Caller wallet (@user.address) must equal @newData.trader. side must be exactly 'long' or 'short'. subaccountIndex must be > 0 (isolated subaccount; 0 is reserved for cross-margin). transferAmt (PhUSD/USDC base units, 6 decimals) must be > 0. The market pubkey is NOT enumerated against a per-market whitelist — any live Phoenix market is accepted so newly-listed markets work without policy edits. SECURITY: this is safe because the collateral-moving leg transferToIsolated does NOT take @newData.market; its destination is fully derived from @user.address (the signer, enforced by @user.address==@newData.trader) and @newData.subaccountIndex, so an attacker-supplied market pubkey cannot redirect collateral. @newData.market is consumed ONLY by the final placeLong/placeShort leg, where the Phoenix on-chain program validates the orderbook account; a bogus market account reverts the entire atomic CPI tx (transferToIsolated reverts too), so the worst case is a self-DoS, never fund diversion. The single onchain hook runs four Phoenix steps atomically in one CPI tx, in order: (1) registerTrader (idempotent), (2) syncParentToChild, (3) transferToIsolated (cross -> isolated subaccount), (4) placeLong/placeShort with sizeBaseLots on the subaccountIndex. RiskView always sees post-transfer collateral. User must already have transferAmt of free cross-margin collateral. Trading points awarded by this collection's offchain hook (sizeUsd). No backend/vault writes — user-signed from frontend. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPhoenixIsoTrade(tradeId: string, data?: PhoenixIsoTradeRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`phoenixIsoTrade/${tradeId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PhoenixIsoTrade: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read (onchain data is public). UI filters by @data.trader == current wallet. The resulting Phoenix CPI transaction signature is available on the standard tarobase_transaction_hash field of the created document.
   (Get Single Item)
 */
export async function getPhoenixIsoTrade(tradeId: string): Promise<PhoenixIsoTradeResponse | null> {
  try {
    const result = await get(`phoenixIsoTrade/${tradeId}`);
    return result as PhoenixIsoTradeResponse | null;
  } catch (error) {
    console.error(`Error getting PhoenixIsoTrade: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PhoenixIsoTrade document. (
  Read Operation Details: Anyone can read (onchain data is public). UI filters by @data.trader == current wallet. The resulting Phoenix CPI transaction signature is available on the standard tarobase_transaction_hash field of the created document.
  )
 */
export function subscribePhoenixIsoTrade(callback: (data: PhoenixIsoTradeResponse | null) => void, tradeId: string): Promise<() => Promise<void>> {
  return subscribe(`phoenixIsoTrade/${tradeId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PhoenixIsoTradeResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PhoenixIsoTrade at path '${`phoenixIsoTrade/${tradeId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PhoenixIsoTrade items from collection phoenixIsoTrade
 
  Read Operation Details: Anyone can read (onchain data is public). UI filters by @data.trader == current wallet. The resulting Phoenix CPI transaction signature is available on the standard tarobase_transaction_hash field of the created document.
  
 */
export async function getManyPhoenixIsoTrade(filter: string = ""): Promise<PhoenixIsoTradeResponse[]> {
  try {
    const results = await get("phoenixIsoTrade", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsoTradeResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsoTrade collection at path 'phoenixIsoTrade': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsoTrade collection at phoenixIsoTrade
 
  Read Operation Details: Anyone can read (onchain data is public). UI filters by @data.trader == current wallet. The resulting Phoenix CPI transaction signature is available on the standard tarobase_transaction_hash field of the created document.
  
 */
export function subscribeManyPhoenixIsoTrade(callback: (data: PhoenixIsoTradeResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsoTrade", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsoTradeResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsoTrade collection at path '${"phoenixIsoTrade"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PhoenixIsoTrade items from collection phoenixIsoTrade
 
  Read Operation Details: Anyone can read (onchain data is public). UI filters by @data.trader == current wallet. The resulting Phoenix CPI transaction signature is available on the standard tarobase_transaction_hash field of the created document.
  
 */
export async function getAllPhoenixIsoTrade(filter: string = ""): Promise<PhoenixIsoTradeResponse[]> {
  try {
    const results = await get("phoenixIsoTrade", { prompt: filter });
    return Array.isArray(results) ? results as PhoenixIsoTradeResponse[] : [];
  } catch (error) {
    console.error(`Error getting PhoenixIsoTrade collection at path 'phoenixIsoTrade': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PhoenixIsoTrade collection at phoenixIsoTrade
 
  Read Operation Details: Anyone can read (onchain data is public). UI filters by @data.trader == current wallet. The resulting Phoenix CPI transaction signature is available on the standard tarobase_transaction_hash field of the created document.
  
 */
export function subscribeAllPhoenixIsoTrade(callback: (data: PhoenixIsoTradeResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("phoenixIsoTrade", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PhoenixIsoTradeResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PhoenixIsoTrade collection at path '${"phoenixIsoTrade"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PhoenixIsoTrade items in collection phoenixIsoTrade.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPhoenixIsoTrade(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("phoenixIsoTrade", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PhoenixIsoTrade at path 'phoenixIsoTrade': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PhoenixIsoTrade items in collection phoenixIsoTrade.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePhoenixIsoTrade(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("phoenixIsoTrade", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PhoenixIsoTrade at path 'phoenixIsoTrade': ${formatError(error)}`);
    return { value: 0 };
  }
}

