// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: promotionLinkRegistry/$linkHash
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Backend-managed registry mapping a normalized promotion-link hash ($linkHash = SHA-256 hex of the normalized link, computed by the backend) to the wallet that first submitted that link. Used as an anti-farming integrity gate so the same promotion link cannot be claimed by more than one wallet. Only the PROJECT_VAULT_ADDRESS backend writes/clears this registry; everyone can read.
 */

export interface PromotionLinkRegistryRequest {
  link: string;
  owner: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PromotionLinkRegistryResponse {
  link: string;
  owner: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PromotionLinkRegistry operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPromotionLinkRegistry(linkHash: string, data: PromotionLinkRegistryRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `promotionLinkRegistry/${linkHash}`, document: doc };
}

/**
 * Backend only. Only the PROJECT_VAULT_ADDRESS (the vault-signed Cloudflare Worker) may create a registry entry. $linkHash is the SHA-256 hex of the normalized link computed server-side; owner is the wallet that first submitted the link. Users cannot write this directly. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPromotionLinkRegistry(linkHash: string, data: PromotionLinkRegistryRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`promotionLinkRegistry/${linkHash}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PromotionLinkRegistry: ${formatError(error)}`);
    return false;
  }
}

export type PromotionLinkRegistryRequestUpdate = Partial<PromotionLinkRegistryRequest>;

/**
 * Build a PromotionLinkRegistry update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePromotionLinkRegistry(linkHash: string, data: PromotionLinkRegistryRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `promotionLinkRegistry/${linkHash}`, document: doc };
}

/**
 * Backend only. Only PROJECT_VAULT_ADDRESS may update a registry entry (e.g. to re-point or correct ownership). owner is readonly (Address!) and cannot be changed after creation. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePromotionLinkRegistry(linkHash: string, data: PromotionLinkRegistryRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`promotionLinkRegistry/${linkHash}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PromotionLinkRegistry: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Exposes link, owner, and createdAt for the duplicate-link integrity check.
   (Get Single Item)
 */
export async function getPromotionLinkRegistry(linkHash: string): Promise<PromotionLinkRegistryResponse | null> {
  try {
    const result = await get(`promotionLinkRegistry/${linkHash}`);
    return result as PromotionLinkRegistryResponse | null;
  } catch (error) {
    console.error(`Error getting PromotionLinkRegistry: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PromotionLinkRegistry document. (
  Read Operation Details: Anyone can read. Exposes link, owner, and createdAt for the duplicate-link integrity check.
  )
 */
export function subscribePromotionLinkRegistry(callback: (data: PromotionLinkRegistryResponse | null) => void, linkHash: string): Promise<() => Promise<void>> {
  return subscribe(`promotionLinkRegistry/${linkHash}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PromotionLinkRegistryResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PromotionLinkRegistry at path '${`promotionLinkRegistry/${linkHash}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PromotionLinkRegistry items from collection promotionLinkRegistry
 
  Read Operation Details: Anyone can read. Exposes link, owner, and createdAt for the duplicate-link integrity check.
  
 */
export async function getManyPromotionLinkRegistry(filter: string = ""): Promise<PromotionLinkRegistryResponse[]> {
  try {
    const results = await get("promotionLinkRegistry", { prompt: filter });
    return Array.isArray(results) ? results as PromotionLinkRegistryResponse[] : [];
  } catch (error) {
    console.error(`Error getting PromotionLinkRegistry collection at path 'promotionLinkRegistry': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PromotionLinkRegistry collection at promotionLinkRegistry
 
  Read Operation Details: Anyone can read. Exposes link, owner, and createdAt for the duplicate-link integrity check.
  
 */
export function subscribeManyPromotionLinkRegistry(callback: (data: PromotionLinkRegistryResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("promotionLinkRegistry", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PromotionLinkRegistryResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PromotionLinkRegistry collection at path '${"promotionLinkRegistry"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PromotionLinkRegistry items from collection promotionLinkRegistry
 
  Read Operation Details: Anyone can read. Exposes link, owner, and createdAt for the duplicate-link integrity check.
  
 */
export async function getAllPromotionLinkRegistry(filter: string = ""): Promise<PromotionLinkRegistryResponse[]> {
  try {
    const results = await get("promotionLinkRegistry", { prompt: filter });
    return Array.isArray(results) ? results as PromotionLinkRegistryResponse[] : [];
  } catch (error) {
    console.error(`Error getting PromotionLinkRegistry collection at path 'promotionLinkRegistry': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PromotionLinkRegistry collection at promotionLinkRegistry
 
  Read Operation Details: Anyone can read. Exposes link, owner, and createdAt for the duplicate-link integrity check.
  
 */
export function subscribeAllPromotionLinkRegistry(callback: (data: PromotionLinkRegistryResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("promotionLinkRegistry", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PromotionLinkRegistryResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PromotionLinkRegistry collection at path '${"promotionLinkRegistry"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PromotionLinkRegistry items in collection promotionLinkRegistry.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPromotionLinkRegistry(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("promotionLinkRegistry", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PromotionLinkRegistry at path 'promotionLinkRegistry': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PromotionLinkRegistry items in collection promotionLinkRegistry.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePromotionLinkRegistry(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("promotionLinkRegistry", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PromotionLinkRegistry at path 'promotionLinkRegistry': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Backend only. Only PROJECT_VAULT_ADDRESS may delete a registry entry (e.g. clearing a link so it can be reused).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePromotionLinkRegistry(linkHash: string): Promise<boolean> {
  try {
    const succeeded = await set(`promotionLinkRegistry/${linkHash}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PromotionLinkRegistry: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PromotionLinkRegistry for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePromotionLinkRegistry(linkHash: string): DocumentOperation {
  return { path: `promotionLinkRegistry/${linkHash}`, document: null };
}

