// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: rumbleClaims/$claimId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Royal Rumble 3-winner payout claim. Backend-only. One claim per battle (claimId = battleId). Splits total pot 49.5% / 34.65% / 14.85% / 1% platform fee.
 */

export interface RumbleClaimsRequest {
  battleId: string;
  winner1: AddressType;
  winner2: AddressType;
  winner3: AddressType;
  totalPotMicro: number | TimeOperation | IncrementOperation | TokenAmount;
  claimedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface RumbleClaimsResponse {
  battleId: string;
  winner1: string;
  winner2: string;
  winner3: string;
  totalPotMicro: number;
  claimedAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a RumbleClaims operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildRumbleClaims(claimId: string, data?: RumbleClaimsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `rumbleClaims/${claimId}`, document: doc };
}

/**
 * Backend-only (PROJECT_VAULT_ADDRESS). The battle-resolver determines top 3 by PnL%, computes totalPotMicro by summing all battleParticipants bets + potContributions for this battle, then creates this claim. Onchain hook performs 4 atomic transfers from the battle PDA: 49.5% to winner1, 34.65% to winner2, 14.85% to winner3, 1% platform fee to ADMIN_ADDRESS. Integer math: multiply before divide (4950/10000, 3465/10000, 1485/10000, 100/10000). All 4 transfers must succeed or the entire claim rolls back. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setRumbleClaims(claimId: string, data?: RumbleClaimsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`rumbleClaims/${claimId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting RumbleClaims: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public (onchain). Anyone can read claim records.
   (Get Single Item)
 */
export async function getRumbleClaims(claimId: string): Promise<RumbleClaimsResponse | null> {
  try {
    const result = await get(`rumbleClaims/${claimId}`);
    return result as RumbleClaimsResponse | null;
  } catch (error) {
    console.error(`Error getting RumbleClaims: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single RumbleClaims document. (
  Read Operation Details: Public (onchain). Anyone can read claim records.
  )
 */
export function subscribeRumbleClaims(callback: (data: RumbleClaimsResponse | null) => void, claimId: string): Promise<() => Promise<void>> {
  return subscribe(`rumbleClaims/${claimId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as RumbleClaimsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to RumbleClaims at path '${`rumbleClaims/${claimId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many RumbleClaims items from collection rumbleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export async function getManyRumbleClaims(filter: string = ""): Promise<RumbleClaimsResponse[]> {
  try {
    const results = await get("rumbleClaims", { prompt: filter });
    return Array.isArray(results) ? results as RumbleClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting RumbleClaims collection at path 'rumbleClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RumbleClaims collection at rumbleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export function subscribeManyRumbleClaims(callback: (data: RumbleClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("rumbleClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RumbleClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RumbleClaims collection at path '${"rumbleClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all RumbleClaims items from collection rumbleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export async function getAllRumbleClaims(filter: string = ""): Promise<RumbleClaimsResponse[]> {
  try {
    const results = await get("rumbleClaims", { prompt: filter });
    return Array.isArray(results) ? results as RumbleClaimsResponse[] : [];
  } catch (error) {
    console.error(`Error getting RumbleClaims collection at path 'rumbleClaims': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RumbleClaims collection at rumbleClaims
 
  Read Operation Details: Public (onchain). Anyone can read claim records.
  
 */
export function subscribeAllRumbleClaims(callback: (data: RumbleClaimsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("rumbleClaims", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RumbleClaimsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RumbleClaims collection at path '${"rumbleClaims"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count RumbleClaims items in collection rumbleClaims.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countRumbleClaims(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("rumbleClaims", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting RumbleClaims at path 'rumbleClaims': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on RumbleClaims items in collection rumbleClaims.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateRumbleClaims(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("rumbleClaims", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating RumbleClaims at path 'rumbleClaims': ${formatError(error)}`);
    return { value: 0 };
  }
}

