// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: socialLinks/$storageKey
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Stores a user's linked social account (e.g. X/Twitter) from Poof's OAuth flow. Document ID ($storageKey) follows the format social:{wallet}:{provider}. Written by the partyserver OAuth callback and social-links routes (signed by PROJECT_VAULT_ADDRESS). Publicly readable so the leaderboard can show each user's connected X avatar and username alongside their wallet.
 */

export interface SocialLinksRequest {
  wallet: AddressType;
  provider: string;
  profile: string;
  linkedAt: number | IncrementOperation | TokenAmount;
}

export interface SocialLinksResponse {
  wallet: string;
  provider: string;
  profile: string;
  linkedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a SocialLinks operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSocialLinks(storageKey: string, data: SocialLinksRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `socialLinks/${storageKey}`, document: doc };
}

/**
 * Created by the OAuth callback route (partyserver), which signs Tarobase requests as PROJECT_VAULT_ADDRESS; the owning wallet (@newData.wallet) is also permitted. storageKey format is social:{wallet}:{provider} using colon separators. Exactly 4 fields are allowed: wallet (Address), provider (String), profile (JSON String), linkedAt (Int Unix ms). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSocialLinks(storageKey: string, data: SocialLinksRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`socialLinks/${storageKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SocialLinks: ${formatError(error)}`);
    return false;
  }
}

export type SocialLinksRequestUpdate = Partial<SocialLinksRequest>;

/**
 * Build a SocialLinks update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSocialLinks(storageKey: string, data: SocialLinksRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `socialLinks/${storageKey}`, document: doc };
}

/**
 * Updated by the server (PROJECT_VAULT_ADDRESS) to refresh profile data, or by the owning wallet (@data.wallet). No other users may update. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSocialLinks(storageKey: string, data: SocialLinksRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`socialLinks/${storageKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating SocialLinks: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public. Anyone can read any social link record. The leaderboard reads everyone's linked X profile (avatar + username) to display alongside wallet addresses. Profile is a JSON string containing id, username, email, avatar, displayName, metadata.
   (Get Single Item)
 */
export async function getSocialLinks(storageKey: string): Promise<SocialLinksResponse | null> {
  try {
    const result = await get(`socialLinks/${storageKey}`);
    return result as SocialLinksResponse | null;
  } catch (error) {
    console.error(`Error getting SocialLinks: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SocialLinks document. (
  Read Operation Details: Public. Anyone can read any social link record. The leaderboard reads everyone's linked X profile (avatar + username) to display alongside wallet addresses. Profile is a JSON string containing id, username, email, avatar, displayName, metadata.
  )
 */
export function subscribeSocialLinks(callback: (data: SocialLinksResponse | null) => void, storageKey: string): Promise<() => Promise<void>> {
  return subscribe(`socialLinks/${storageKey}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SocialLinksResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SocialLinks at path '${`socialLinks/${storageKey}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SocialLinks items from collection socialLinks
 
  Read Operation Details: Public. Anyone can read any social link record. The leaderboard reads everyone's linked X profile (avatar + username) to display alongside wallet addresses. Profile is a JSON string containing id, username, email, avatar, displayName, metadata.
  
 */
export async function getManySocialLinks(filter: string = ""): Promise<SocialLinksResponse[]> {
  try {
    const results = await get("socialLinks", { prompt: filter });
    return Array.isArray(results) ? results as SocialLinksResponse[] : [];
  } catch (error) {
    console.error(`Error getting SocialLinks collection at path 'socialLinks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SocialLinks collection at socialLinks
 
  Read Operation Details: Public. Anyone can read any social link record. The leaderboard reads everyone's linked X profile (avatar + username) to display alongside wallet addresses. Profile is a JSON string containing id, username, email, avatar, displayName, metadata.
  
 */
export function subscribeManySocialLinks(callback: (data: SocialLinksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("socialLinks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SocialLinksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SocialLinks collection at path '${"socialLinks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SocialLinks items from collection socialLinks
 
  Read Operation Details: Public. Anyone can read any social link record. The leaderboard reads everyone's linked X profile (avatar + username) to display alongside wallet addresses. Profile is a JSON string containing id, username, email, avatar, displayName, metadata.
  
 */
export async function getAllSocialLinks(filter: string = ""): Promise<SocialLinksResponse[]> {
  try {
    const results = await get("socialLinks", { prompt: filter });
    return Array.isArray(results) ? results as SocialLinksResponse[] : [];
  } catch (error) {
    console.error(`Error getting SocialLinks collection at path 'socialLinks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SocialLinks collection at socialLinks
 
  Read Operation Details: Public. Anyone can read any social link record. The leaderboard reads everyone's linked X profile (avatar + username) to display alongside wallet addresses. Profile is a JSON string containing id, username, email, avatar, displayName, metadata.
  
 */
export function subscribeAllSocialLinks(callback: (data: SocialLinksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("socialLinks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SocialLinksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SocialLinks collection at path '${"socialLinks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SocialLinks items in collection socialLinks.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSocialLinks(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("socialLinks", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SocialLinks at path 'socialLinks': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SocialLinks items in collection socialLinks.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSocialLinks(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("socialLinks", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SocialLinks at path 'socialLinks': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Deleted by the server (PROJECT_VAULT_ADDRESS) when a user disconnects via the social-links API, or by the owning wallet (@data.wallet). No other users may delete.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteSocialLinks(storageKey: string): Promise<boolean> {
  try {
    const succeeded = await set(`socialLinks/${storageKey}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting SocialLinks: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for SocialLinks for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteSocialLinks(storageKey: string): DocumentOperation {
  return { path: `socialLinks/${storageKey}`, document: null };
}

