// Generated by TaroBase SDK Generator: 2026-06-16T00:49:17.059Z
// Collection: solTransfer/$transferId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Send native SOL from the caller's connected wallet to an arbitrary recipient address. Transient onchain passthrough action — no permanent state stored.
 */

export interface SolTransferRequest {
  recipient: AddressType;
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SolTransferResponse {
  recipient: string;
  amt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SolTransfer operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSolTransfer(transferId: string, data: SolTransferRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `solTransfer/${transferId}`, document: doc };
}

/**
 * Authenticated users only. Performs a user-signed native SOL transfer from the caller's own connected wallet (@user.address is the source and signer) to the arbitrary recipient address provided in @newData.recipient. Uses @TokenPlugin.transfer with the native SOL mint (@constants.SOL). `amt` is in lamports (9 decimals: 1 SOL = 1,000,000,000 lamports); the frontend must convert the human SOL amount to lamports before calling. The SOL is deducted from the caller's wallet; the frontend should leave headroom for transaction fees and not attempt to send the entire balance. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSolTransfer(transferId: string, data: SolTransferRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`solTransfer/${transferId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SolTransfer: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
   (Get Single Item)
 */
export async function getSolTransfer(transferId: string): Promise<SolTransferResponse | null> {
  try {
    const result = await get(`solTransfer/${transferId}`);
    return result as SolTransferResponse | null;
  } catch (error) {
    console.error(`Error getting SolTransfer: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SolTransfer document. (
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  )
 */
export function subscribeSolTransfer(callback: (data: SolTransferResponse | null) => void, transferId: string): Promise<() => Promise<void>> {
  return subscribe(`solTransfer/${transferId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SolTransferResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SolTransfer at path '${`solTransfer/${transferId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SolTransfer items from collection solTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getManySolTransfer(filter: string = ""): Promise<SolTransferResponse[]> {
  try {
    const results = await get("solTransfer", { prompt: filter });
    return Array.isArray(results) ? results as SolTransferResponse[] : [];
  } catch (error) {
    console.error(`Error getting SolTransfer collection at path 'solTransfer': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SolTransfer collection at solTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeManySolTransfer(callback: (data: SolTransferResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("solTransfer", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SolTransferResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SolTransfer collection at path '${"solTransfer"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SolTransfer items from collection solTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export async function getAllSolTransfer(filter: string = ""): Promise<SolTransferResponse[]> {
  try {
    const results = await get("solTransfer", { prompt: filter });
    return Array.isArray(results) ? results as SolTransferResponse[] : [];
  } catch (error) {
    console.error(`Error getting SolTransfer collection at path 'solTransfer': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SolTransfer collection at solTransfer
 
  Read Operation Details: Anyone can read. Passthrough — no permanent document stored.
  
 */
export function subscribeAllSolTransfer(callback: (data: SolTransferResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("solTransfer", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SolTransferResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SolTransfer collection at path '${"solTransfer"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SolTransfer items in collection solTransfer.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSolTransfer(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("solTransfer", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SolTransfer at path 'solTransfer': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SolTransfer items in collection solTransfer.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSolTransfer(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("solTransfer", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SolTransfer at path 'solTransfer': ${formatError(error)}`);
    return { value: 0 };
  }
}

