// Generated by TaroBase SDK Generator: 2026-06-30T08:20:39.181Z
// Collection: userPoints/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks total and category-specific points per user. Used for leaderboards and rewards. Backend (PROJECT_VAULT_ADDRESS) awards points; users cannot self-award.
 */

export interface UserPointsRequest {
  address: AddressType;
  totalPoints: number | TimeOperation | IncrementOperation | TokenAmount;
  tradingPoints: number | TimeOperation | IncrementOperation | TokenAmount;
  battlePoints: number | TimeOperation | IncrementOperation | TokenAmount;
  socialPoints: number | TimeOperation | IncrementOperation | TokenAmount;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface UserPointsResponse {
  address: string;
  totalPoints: number;
  tradingPoints: number;
  battlePoints: number;
  socialPoints: number;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a UserPoints operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUserPoints(userAddress: string, data: UserPointsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `userPoints/${userAddress}`, document: doc };
}

/**
 * Only the backend vault (PROJECT_VAULT_ADDRESS) or admin can create points records. Users cannot self-award points. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setUserPoints(userAddress: string, data: UserPointsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`userPoints/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting UserPoints: ${formatError(error)}`);
    return false;
  }
}

export type UserPointsRequestUpdate = Partial<UserPointsRequest>;

/**
 * Build a UserPoints update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateUserPoints(userAddress: string, data: UserPointsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `userPoints/${userAddress}`, document: doc };
}

/**
 * Only the backend vault (PROJECT_VAULT_ADDRESS) or admin can update points. Users earn points exclusively through controlled upstream hooks (trades, battles, social claims). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateUserPoints(userAddress: string, data: UserPointsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`userPoints/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating UserPoints: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read. Needed for leaderboard display.
   (Get Single Item)
 */
export async function getUserPoints(userAddress: string): Promise<UserPointsResponse | null> {
  try {
    const result = await get(`userPoints/${userAddress}`);
    return result as UserPointsResponse | null;
  } catch (error) {
    console.error(`Error getting UserPoints: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single UserPoints document. (
  Read Operation Details: Anyone can read. Needed for leaderboard display.
  )
 */
export function subscribeUserPoints(callback: (data: UserPointsResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`userPoints/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as UserPointsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to UserPoints at path '${`userPoints/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many UserPoints items from collection userPoints
 
  Read Operation Details: Anyone can read. Needed for leaderboard display.
  
 */
export async function getManyUserPoints(filter: string = ""): Promise<UserPointsResponse[]> {
  try {
    const results = await get("userPoints", { prompt: filter });
    return Array.isArray(results) ? results as UserPointsResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserPoints collection at path 'userPoints': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserPoints collection at userPoints
 
  Read Operation Details: Anyone can read. Needed for leaderboard display.
  
 */
export function subscribeManyUserPoints(callback: (data: UserPointsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("userPoints", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserPointsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserPoints collection at path '${"userPoints"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all UserPoints items from collection userPoints
 
  Read Operation Details: Anyone can read. Needed for leaderboard display.
  
 */
export async function getAllUserPoints(filter: string = ""): Promise<UserPointsResponse[]> {
  try {
    const results = await get("userPoints", { prompt: filter });
    return Array.isArray(results) ? results as UserPointsResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserPoints collection at path 'userPoints': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserPoints collection at userPoints
 
  Read Operation Details: Anyone can read. Needed for leaderboard display.
  
 */
export function subscribeAllUserPoints(callback: (data: UserPointsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("userPoints", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserPointsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserPoints collection at path '${"userPoints"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count UserPoints items in collection userPoints.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countUserPoints(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("userPoints", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting UserPoints at path 'userPoints': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on UserPoints items in collection userPoints.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateUserPoints(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("userPoints", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating UserPoints at path 'userPoints': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Admin only. The admin (ADMIN_ADDRESS) can delete a user's points record for moderation, which removes them from the leaderboard. Otherwise records are kept for audit and leaderboard integrity.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteUserPoints(userAddress: string): Promise<boolean> {
  try {
    const succeeded = await set(`userPoints/${userAddress}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting UserPoints: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for UserPoints for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteUserPoints(userAddress: string): DocumentOperation {
  return { path: `userPoints/${userAddress}`, document: null };
}

